import type { RawTitle } from "../shape";

/** Batch 001 — pipeline smoke test + first pass at closing the Apple TV / Disney+ Hotstar /
 * Prime Video gap left by the core seed (which skews heavily Netflix/HBO Max/Crunchyroll). */
export const RAW: RawTitle[] = [
  {
    id: "silo", name: "Silo", type: "show",
    plot: "In a massive underground silo where 10,000 people have lived for generations after the surface became toxic, an engineer investigates a series of deaths that expose cracks in everything she was taught to believe.",
    cast: ["Rebecca Ferguson", "Common", "Rashida Jones"], seasons: 2, episodes: 20, year: 2023,
    platforms: ["Apple TV"], genre: ["sci-fi", "mystery", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["multi-season"], love: ["world-building", "plot-twists"],
  },
  {
    id: "the-morning-show", name: "The Morning Show", type: "show",
    plot: "Two co-anchors fight for control of a national morning show after their male anchor is fired amid a #MeToo scandal, as the network's rot goes a lot deeper than one bad man.",
    cast: ["Jennifer Aniston", "Reese Witherspoon", "Steve Carell"], seasons: 3, episodes: 30, year: 2019,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["multi-season"], love: ["characters", "emotional-weight"],
  },
  {
    id: "coda", name: "CODA", type: "movie",
    plot: "The only hearing member of a deaf family, a teenage girl has always been the family's interpreter and lifeline to the hearing world — until a music teacher convinces her she has a shot at a singing career of her own.",
    cast: ["Emilia Jones", "Troy Kotsur", "Marlee Matlin"], runtime: 111, year: 2021,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "loki", name: "Loki", type: "show",
    plot: "Plucked out of his own timeline right after the events of Avengers: Endgame, the God of Mischief is recruited by a bureaucratic agency that polices time itself — and starts to suspect he's being used.",
    cast: ["Tom Hiddleston", "Owen Wilson", "Sophia Di Martino"], seasons: 2, episodes: 12, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "fantasy", "action"], mood: ["funny-witty", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "andor", name: "Andor", type: "show",
    plot: "Years before he steals the Death Star plans, small-time smuggler Cassian Andor gets pulled into the earliest stirrings of the Rebellion, and finds out just how much an ordinary person can be asked to sacrifice.",
    cast: ["Diego Luna", "Stellan Skarsgård", "Genevieve O'Reilly"], seasons: 2, episodes: 24, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "drama", "thriller"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "encanto", name: "Encanto", type: "movie",
    plot: "Every child in the magical Madrigal family is blessed with a unique gift — except Mirabel, who has to find out why the family's magic is dying out before it takes the whole house down with it.",
    cast: ["Stephanie Beatriz", "María Cecilia Botero", "John Leguizamo"], runtime: 102, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "fallout", name: "Fallout", type: "show",
    plot: "When her father is kidnapped, a vault dweller leaves the safety of underground Vault 33 for the first time and finds a post-nuclear wasteland full of factions, mutants, and people who all want something from her.",
    cast: ["Ella Purnell", "Aaron Moten", "Walton Goggins"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Prime Video"], genre: ["sci-fi", "action", "drama"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["world-building", "characters"],
  },
  {
    id: "the-wheel-of-time", name: "The Wheel of Time", type: "show",
    plot: "A powerful sorceress leads five young villagers across a vast fantasy world, convinced one of them is the reincarnation of a prophesied hero who will either save humanity or destroy it.",
    cast: ["Rosamund Pike", "Daniel Henney", "Zoë Robins"], seasons: 3, episodes: 24, year: 2021,
    platforms: ["Prime Video"], genre: ["fantasy", "action"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["multi-season"], love: ["world-building", "plot-twists"],
  },
  {
    id: "upload", name: "Upload", type: "show",
    plot: "After a fatal self-driving car crash, a young man has his consciousness uploaded to a luxury digital afterlife he can't really afford, and starts falling for the customer-service rep managing his account from the real world.",
    cast: ["Robbie Amell", "Andy Allo", "Allegra Edwards"], seasons: 3, episodes: 24, year: 2020,
    platforms: ["Prime Video"], genre: ["comedy", "sci-fi", "romance"], mood: ["funny-witty", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["multi-season"], love: ["humor", "world-building"],
  },
  {
    id: "community", name: "Community", type: "show",
    plot: "A disbarred lawyer forced back into community college for a real degree forms a chaotic study group with six other misfits, and their Spanish-class friendship spirals into paintball wars, clip-show parodies, and stop-motion Christmas specials.",
    cast: ["Joel McHale", "Danny Pudi", "Alison Brie"], seasons: 6, episodes: 110, year: 2009,
    platforms: ["Netflix", "Hulu"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["humor", "characters"],
  },
];
