import type { RawTitle } from "../shape";

/** Batch 002 — Apple TV+ focus (the thinnest platform in the core seed). */
export const RAW: RawTitle[] = [
  {
    id: "for-all-mankind", name: "For All Mankind", type: "show",
    plot: "An alternate history where the Soviet Union beats America to the moon, so NASA never stands down — pushing the space race decades further than it really went, with all the political and personal fallout that comes with it.",
    cast: ["Joel Kinnaman", "Michael Dorman", "Sarah Jones"], seasons: 4, episodes: 40, year: 2019,
    platforms: ["Apple TV"], genre: ["sci-fi", "drama"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["world-building", "characters"],
  },
  {
    id: "shrinking", name: "Shrinking", type: "show",
    plot: "A grieving therapist starts breaking every rule in the book — telling his clients exactly what he thinks — and the results are messier, funnier, and more helpful than his careful old approach ever was.",
    cast: ["Jason Segel", "Harrison Ford", "Jessica Williams"], seasons: 2, episodes: 22, year: 2023,
    platforms: ["Apple TV"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "bad-sisters", name: "Bad Sisters", type: "show",
    plot: "Five tight-knit Irish sisters are suspects when their universally despised brother-in-law turns up dead — told in flashback as the insurance investigators dig into just how many of them wanted him gone.",
    cast: ["Sharon Horgan", "Anne-Marie Duff", "Eve Hewson"], seasons: 2, episodes: 20, year: 2022,
    platforms: ["Apple TV"], genre: ["comedy", "thriller", "mystery"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "presumed-innocent", name: "Presumed Innocent", type: "show",
    plot: "A Chicago prosecutor becomes the lead suspect when his colleague and former mistress is found murdered, and has to defend himself in the same courthouse where he used to put people away.",
    cast: ["Jake Gyllenhaal", "Ruth Negga", "Peter Sarsgaard"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Apple TV"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "masters-of-the-air", name: "Masters of the Air", type: "show",
    plot: "The Band of Brothers team follows a US Army bomber squadron flying deep into occupied Europe during WWII, where survival odds were brutal and every mission could be the last.",
    cast: ["Austin Butler", "Callum Turner", "Anthony Boyle"], seasons: 1, episodes: 9, year: 2024,
    platforms: ["Apple TV"], genre: ["drama", "action"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "constellation", name: "Constellation", type: "show",
    plot: "An astronaut returns to Earth from a disaster in orbit and starts noticing small things that don't match her memory — the beginning of a slow unraveling of what's actually real.",
    cast: ["Noomi Rapace", "Jonathan Banks", "James D'Arcy"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Apple TV"], genre: ["sci-fi", "thriller", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "platonic", name: "Platonic", type: "show",
    plot: "Two former best friends reconnect after years of drifting apart and immediately fall back into the kind of chaotic, no-boundaries friendship that neither of their marriages is fully ready for.",
    cast: ["Seth Rogen", "Rose Byrne", "Luke Macfarlane"], seasons: 2, episodes: 16, year: 2023,
    platforms: ["Apple TV"], genre: ["comedy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "mythic-quest", name: "Mythic Quest", type: "show",
    plot: "The dysfunctional team behind a wildly successful video game studio has to keep shipping content, managing egos, and surviving each other, one disastrous update at a time.",
    cast: ["Rob McElhenney", "Charlotte Nicdao", "Danny Pudi"], seasons: 4, episodes: 39, year: 2020,
    platforms: ["Apple TV"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["humor", "characters"],
  },
  {
    id: "see", name: "See", type: "show",
    plot: "Centuries after a virus wipes out sight itself, humanity has rebuilt a world without vision — until a set of twins is born who can see, threatening every power structure built on blindness.",
    cast: ["Jason Momoa", "Alfre Woodard", "Sylvia Hoeks"], seasons: 3, episodes: 24, year: 2019,
    platforms: ["Apple TV"], genre: ["sci-fi", "fantasy", "action"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["world-building", "plot-twists"],
  },
  {
    id: "foundation", name: "Foundation", type: "show",
    plot: "A mathematician predicts the fall of a galaxy-spanning empire centuries in advance and sets up a colony to preserve civilization through the coming dark age — if the empire doesn't kill her for the prophecy first.",
    cast: ["Jared Harris", "Lee Pace", "Lou Llobell"], seasons: 3, episodes: 30, year: 2021,
    platforms: ["Apple TV"], genre: ["sci-fi"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["world-building", "plot-twists"],
  },
  {
    id: "defending-jacob", name: "Defending Jacob", type: "show",
    plot: "A well-liked assistdistrict attorney's world implodes when his own teenage son becomes the prime suspect in a classmate's murder, forcing him to decide how far he'll go to protect his family.",
    cast: ["Chris Evans", "Michelle Dockery", "Jaeden Martell"], seasons: 1, episodes: 8, year: 2020,
    platforms: ["Apple TV"], genre: ["thriller", "drama", "mystery"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "truth-be-told", name: "Truth Be Told", type: "show",
    plot: "A true-crime podcaster who helped put a man in prison years ago starts to doubt his guilt, and has to reckon with the damage her own show did in the name of certainty.",
    cast: ["Octavia Spencer", "Aaron Paul", "Lizzy Caplan"], seasons: 3, episodes: 27, year: 2019,
    platforms: ["Apple TV"], genre: ["mystery", "drama", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["plot-twists", "characters"],
  },
  {
    id: "pachinko", name: "Pachinko", type: "show",
    plot: "Spanning four generations of a Korean family from Japanese-occupied Korea to 1980s Japan, one woman's early choices ripple down through her descendants' very different lives.",
    cast: ["Youn Yuh-jung", "Lee Min-ho", "Kim Min-ha"], seasons: 2, episodes: 16, year: 2022,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "lessons-in-chemistry", name: "Lessons in Chemistry", type: "show",
    plot: "A brilliant 1950s chemist is forced out of the lab for being a woman and ends up hosting a cooking show instead — and uses it to secretly teach an entire generation of housewives real science.",
    cast: ["Brie Larson", "Lewis Pullman", "Aja Naomi King"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["intense", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "palm-royale", name: "Palm Royale", type: "show",
    plot: "A determined social climber in 1969 Palm Beach will do absolutely anything to claw her way into the ultra-exclusive country-club set, one scheme and one stolen identity at a time.",
    cast: ["Kristen Wiig", "Laura Dern", "Ricky Martin"], seasons: 1, episodes: 10, year: 2024,
    platforms: ["Apple TV"], genre: ["comedy", "drama"], mood: ["funny-witty", "light"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "dark-matter-apple", name: "Dark Matter", type: "show",
    plot: "A physicist is abducted into a parallel version of his own life, and has to find his way back through an infinite multiverse of alternate choices to the one family that's actually his.",
    cast: ["Joel Edgerton", "Jennifer Connelly", "Alice Braga"], seasons: 1, episodes: 9, year: 2024,
    platforms: ["Apple TV"], genre: ["sci-fi", "thriller"], mood: ["cerebral-ideas", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "monarch-legacy-of-monsters", name: "Monarch: Legacy of Monsters", type: "show",
    plot: "Two half-siblings dig into their father's secret history with the shadowy organization Monarch, uncovering decades of buried evidence about Godzilla and the giant monsters that have always shared our world.",
    cast: ["Kurt Russell", "Wyatt Russell", "Anna Sawai"], seasons: 1, episodes: 10, year: 2023,
    platforms: ["Apple TV"], genre: ["sci-fi", "action", "mystery"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "manhunt-apple", name: "Manhunt", type: "show",
    plot: "In the chaotic twelve days after Lincoln's assassination, the war secretary leads a desperate nationwide hunt for John Wilkes Booth while trying to hold a fractured country together.",
    cast: ["Tobias Menzies", "Anthony Boyle", "Hamish Linklater"], seasons: 1, episodes: 7, year: 2024,
    platforms: ["Apple TV"], genre: ["thriller", "drama"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "bad-monkey", name: "Bad Monkey", type: "show",
    plot: "A disgraced Miami detective demoted to restaurant inspector can't let go of a severed arm that washed up on a beach, and drags his ex-wife, a witch doctor, and an actual monkey into the case.",
    cast: ["Vince Vaughn", "Meredith Hagner", "Rob Delaney"], seasons: 1, episodes: 10, year: 2024,
    platforms: ["Apple TV"], genre: ["comedy", "mystery"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["humor", "plot-twists"],
  },
  {
    id: "sugar", name: "Sugar", type: "show",
    plot: "A courteous, old-fashioned private investigator takes the case of a missing Hollywood starlet, following clues through LA's underbelly while hiding a secret about himself that reframes everything.",
    cast: ["Colin Farrell", "Kirby", "Amy Ryan"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Apple TV"], genre: ["mystery", "thriller"], mood: ["cerebral-mystery", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "little-america", name: "Little America", type: "show",
    plot: "An anthology of true stories about immigrants building unlikely lives in the US — a Ugandan teen learning to ski, a Nigerian widow fighting to keep her motel — each one small, specific, and quietly moving.",
    cast: ["Multiple leads per episode"], seasons: 2, episodes: 17, year: 2020,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["feel-good", "comfort-escapist"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "dickinson", name: "Dickinson", type: "show",
    plot: "A wildly anachronistic take on the young Emily Dickinson's life, dropping modern slang, needle drops, and a very frank queer romance into 1850s Amherst without ever losing the poetry.",
    cast: ["Hailee Steinfeld", "Jane Krakowski", "Toby Huss"], seasons: 3, episodes: 30, year: 2019,
    platforms: ["Apple TV"], genre: ["comedy", "drama"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["humor", "characters"],
  },
  {
    id: "killers-of-the-flower-moon", name: "Killers of the Flower Moon", type: "movie",
    plot: "In 1920s Oklahoma, a string of murders targeting the newly oil-rich Osage Nation exposes a conspiracy running through an entire white community, including the husband of one of the victims' own family.",
    cast: ["Leonardo DiCaprio", "Lily Gladstone", "Robert De Niro"], runtime: 206, year: 2023,
    platforms: ["Apple TV"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "napoleon", name: "Napoleon", type: "movie",
    plot: "A sweeping, unglamorous look at Napoleon Bonaparte's rise from obscurity to emperor, told largely through his volatile, all-consuming relationship with Josephine.",
    cast: ["Joaquin Phoenix", "Vanessa Kirby", "Tahar Rahim"], runtime: 158, year: 2023,
    platforms: ["Apple TV"], genre: ["drama", "action"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "causeway", name: "Causeway", type: "movie",
    plot: "A soldier returns home to New Orleans after a traumatic brain injury and slowly forms a wary friendship with a mechanic who's carrying his own quiet grief, neither of them able to say out loud what they need.",
    cast: ["Jennifer Lawrence", "Brian Tyree Henry"], runtime: 92, year: 2022,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "wolfwalkers", name: "Wolfwalkers", type: "movie",
    plot: "A young hunter's apprentice in 17th-century Ireland befriends a wild girl who can transform into a wolf, and starts to question everything the English occupiers taught her about the forest.",
    cast: ["Honor Kneafsey", "Eva Whittaker", "Sean Bean"], runtime: 103, year: 2020,
    platforms: ["Apple TV"], genre: ["fantasy", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "greyhound", name: "Greyhound", type: "movie",
    plot: "A first-time navy captain leads an Allied convoy across the Atlantic in WWII, hunted the entire way by a wolfpack of German U-boats, with no time to sleep and no room for a single mistake.",
    cast: ["Tom Hanks", "Stephen Graham", "Elisabeth Shue"], runtime: 91, year: 2020,
    platforms: ["Apple TV"], genre: ["action", "drama"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "on-the-rocks", name: "On the Rocks", type: "movie",
    plot: "A young mother starts suspecting her husband is having an affair, and lets her charming, incorrigible playboy father talk her into an amateur stakeout across Manhattan.",
    cast: ["Rashida Jones", "Bill Murray", "Marlon Wayans"], runtime: 96, year: 2020,
    platforms: ["Apple TV"], genre: ["comedy", "drama"], mood: ["light", "funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "swan-song-apple", name: "Swan Song", type: "movie",
    plot: "A terminally ill man is offered a secret service that will clone him and let the copy quietly take over his life, sparing his family the grief — if he can bring himself to actually go through with it.",
    cast: ["Mahershala Ali", "Naomie Harris", "Awkwafina"], runtime: 112, year: 2021,
    platforms: ["Apple TV"], genre: ["sci-fi", "drama"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "the-tragedy-of-macbeth", name: "The Tragedy of Macbeth", type: "movie",
    plot: "A stark, high-contrast black-and-white staging of Shakespeare's tragedy, following a Scottish lord and his wife as prophecy and ambition push them toward murder and madness.",
    cast: ["Denzel Washington", "Frances McDormand", "Kathryn Hunter"], runtime: 105, year: 2021,
    platforms: ["Apple TV"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "argylle", name: "Argylle", type: "movie",
    plot: "A reclusive spy novelist discovers the plots of her bestselling books are eerily predicting the actions of a real, active espionage syndicate — and gets swept into a mission alongside an actual spy.",
    cast: ["Bryce Dallas Howard", "Sam Rockwell", "Henry Cavill"], runtime: 139, year: 2024,
    platforms: ["Apple TV"], genre: ["action", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "humor"],
  },
  {
    id: "fly-me-to-the-moon", name: "Fly Me to the Moon", type: "movie",
    plot: "A brilliant marketing whiz is brought in to sell a skeptical public on the Apollo 11 moon landing, and gets tangled up with a NASA launch director in a scheme to secretly film a fake backup version — just in case.",
    cast: ["Scarlett Johansson", "Channing Tatum", "Woody Harrelson"], runtime: 132, year: 2024,
    platforms: ["Apple TV"], genre: ["comedy", "romance"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "wolfs", name: "Wolfs", type: "movie",
    plot: "Two rival fixers are both called in to clean up the same messy cover-up, and neither one is willing to admit they might actually need the other's help to pull it off.",
    cast: ["George Clooney", "Brad Pitt", "Amy Ryan"], runtime: 108, year: 2024,
    platforms: ["Apple TV"], genre: ["action", "comedy", "thriller"], mood: ["funny-witty", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["humor", "plot-twists"],
  },
  {
    id: "blitz", name: "Blitz", type: "movie",
    plot: "During the London Blitz, a mother sends her young son to safety in the countryside — but he jumps off the train to make his own way back home through a city being bombed nightly.",
    cast: ["Saoirse Ronan", "Elliott Heffernan", "Harris Dickinson"], runtime: 120, year: 2024,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "sharper", name: "Sharper", type: "movie",
    plot: "A New York con told in overlapping chapters from each grifter's point of view, where every character turns out to be running a longer, sharper scheme than the one before them realized.",
    cast: ["Julianne Moore", "Sebastian Stan", "Justice Smith"], runtime: 116, year: 2023,
    platforms: ["Apple TV"], genre: ["thriller", "drama"], mood: ["cerebral-mystery", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "ghosted", name: "Ghosted", type: "movie",
    plot: "A guy falls hard for a woman after one perfect date, then flies across the world to surprise her — only to discover she's secretly a globe-trotting spy, and now he's caught in her mission.",
    cast: ["Chris Evans", "Ana de Armas", "Adrien Brody"], runtime: 116, year: 2023,
    platforms: ["Apple TV"], genre: ["action", "romance", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "plot-twists"],
  },
  {
    id: "spirited", name: "Spirited", type: "movie",
    plot: "A modern musical spin on A Christmas Carol where the Ghost of Christmas Present picks this year's target for reform — and, for the first time ever, the target starts trying to reform him right back.",
    cast: ["Will Ferrell", "Ryan Reynolds", "Octavia Spencer"], runtime: 127, year: 2022,
    platforms: ["Apple TV"], genre: ["comedy", "fantasy"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "luck-apple", name: "Luck", type: "movie",
    plot: "The unluckiest girl in the world stumbles into the magical Land of Luck, where she has to team up with a black cat and a giant dragon to fix her fortune before it's too late.",
    cast: ["Eva Noblezada", "Simon Pegg", "Jane Fonda"], runtime: 104, year: 2022,
    platforms: ["Apple TV"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "humor"],
  },
  {
    id: "cherry", name: "Cherry", type: "movie",
    plot: "A young man's life spirals from Army medic in Iraq to opioid addiction to a string of desperate bank robberies, tracing exactly how each stage led straight into the next.",
    cast: ["Tom Holland", "Ciara Bravo"], runtime: 141, year: 2021,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "the-banker", name: "The Banker", type: "movie",
    plot: "Two Black entrepreneurs in the 1960s train a white man to pose as the face of their real-estate empire, since no bank of the era would ever knowingly do business with them directly.",
    cast: ["Anthony Mackie", "Samuel L. Jackson", "Nicholas Hoult"], runtime: 120, year: 2020,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["intense", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "finch", name: "Finch", type: "movie",
    plot: "One of the last survivors of a solar catastrophe builds a robot to protect his dog after he's gone, and sets out across a ruined America to teach the robot everything it needs to know before he dies.",
    cast: ["Tom Hanks", "Caleb Landry Jones"], runtime: 115, year: 2021,
    platforms: ["Apple TV"], genre: ["sci-fi", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
];
