import type { RawTitle } from "../shape";

/** Batch 003 — Disney+ Hotstar focus: Marvel/Star Wars series, Pixar/Disney animation. */
export const RAW: RawTitle[] = [
  {
    id: "wandavision", name: "WandaVision", type: "show",
    plot: "A grieving Avenger and her android partner find themselves living out a string of classic sitcom decades in a picture-perfect suburban town — until cracks start showing in exactly how fake it all is.",
    cast: ["Elizabeth Olsen", "Paul Bettany", "Kathryn Hahn"], seasons: 1, episodes: 9, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "fantasy", "mystery"], mood: ["cerebral-mystery", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "the-falcon-and-the-winter-soldier", name: "The Falcon and the Winter Soldier", type: "show",
    plot: "Two of Captain America's closest allies grapple with what it means to carry on his legacy while hunting a radical group of super-soldiers and confronting the government's own troubled history with the serum.",
    cast: ["Anthony Mackie", "Sebastian Stan", "Daniel Brühl"], seasons: 1, episodes: 6, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["action", "drama"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "hawkeye", name: "Hawkeye", type: "show",
    plot: "A retired Avenger trying to get home for Christmas gets tangled up with a sharp-shooting young fan whose vigilante hobby has drawn some very dangerous attention from the criminal underworld.",
    cast: ["Jeremy Renner", "Hailee Steinfeld", "Vera Farmiga"], seasons: 1, episodes: 6, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["action", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "moon-knight", name: "Moon Knight", type: "show",
    plot: "A mild-mannered museum gift-shop worker discovers he's sharing his body with a mercenary alter-ego and an ancient Egyptian moon god, and has to figure out which of them is actually in control.",
    cast: ["Oscar Isaac", "May Calamawy", "Ethan Hawke"], seasons: 1, episodes: 6, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["action", "fantasy", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "ms-marvel", name: "Ms. Marvel", type: "show",
    plot: "A Jersey City teenager and superfan of the Avengers discovers she has real superpowers of her own, tied to a family bracelet with roots going back to her grandmother's Partition-era past.",
    cast: ["Iman Vellani", "Matt Lintz", "Yasmeen Fletcher"], seasons: 1, episodes: 6, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["action", "fantasy", "comedy"], mood: ["light", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "she-hulk-attorney-at-law", name: "She-Hulk: Attorney at Law", type: "show",
    plot: "A lawyer who inherits her cousin's Hulk powers would honestly rather just keep her normal life and career than become a full-time superhero, but the universe keeps making that impossible.",
    cast: ["Tatiana Maslany", "Mark Ruffalo", "Tim Roth"], seasons: 1, episodes: 9, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "action"], mood: ["funny-witty", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "ahsoka", name: "Ahsoka", type: "show",
    plot: "Former Jedi Ahsoka Tano tracks down a missing map that could lead to the return of Grand Admiral Thrawn, gathering old allies for a fight that could restart the war she thought was finally over.",
    cast: ["Rosario Dawson", "Natasha Liu Bordizzo", "Mary Elizabeth Winstead"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "action", "fantasy"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "the-bad-batch", name: "Star Wars: The Bad Batch", type: "show",
    plot: "A squad of genetically defective clone troopers goes rogue right as the Republic falls and the Empire rises, trying to find a place in a galaxy that no longer has any use for men built only for war.",
    cast: ["Dee Bradley Baker", "Michelle Ang"], seasons: 3, episodes: 47, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "action"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["characters", "world-building"],
  },
  {
    id: "obi-wan-kenobi", name: "Obi-Wan Kenobi", type: "show",
    plot: "Years into hiding on Tatooine, a broken Obi-Wan Kenobi is pulled back into the fight when Princess Leia is kidnapped, forcing a reckoning with the apprentice he failed to save.",
    cast: ["Ewan McGregor", "Hayden Christensen", "Vivien Lyra Blair"], seasons: 1, episodes: 6, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "action"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "x-men-97", name: "X-Men '97", type: "show",
    plot: "The mutant team picks up right where the beloved '90s cartoon left off, reeling from Xavier's apparent death and forced to decide what the X-Men stand for without him.",
    cast: ["Ray Chase", "Jennifer Hale", "Cal Dodd"], seasons: 1, episodes: 10, year: 2024,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi", "drama"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "what-if", name: "What If...?", type: "show",
    plot: "A cosmic watcher narrates an anthology of single decisions rippling out into radically different timelines across the Marvel universe — what if Peggy Carter took the super-soldier serum instead of Steve Rogers?",
    cast: ["Jeffrey Wright", "Hayley Atwell"], seasons: 3, episodes: 32, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "action"], mood: ["cerebral-ideas", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "percy-jackson-and-the-olympians", name: "Percy Jackson and the Olympians", type: "show",
    plot: "A twelve-year-old discovers he's actually the son of Poseidon, gets accused of stealing Zeus's master lightning bolt, and sets off on a cross-country quest to clear his name before the Greek gods start a war.",
    cast: ["Walker Scobell", "Leah Sava Jeffries", "Aryan Simhadri"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "action"], mood: ["light", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "bluey", name: "Bluey", type: "show",
    plot: "A boundlessly energetic six-year-old Blue Heeler puppy turns every ordinary afternoon into an elaborate game of pretend with her family, and somehow each seven-minute episode says something real about parenting along the way.",
    cast: ["Melanie Zanetti", "David McCormack"], seasons: 3, episodes: 154, year: 2018,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "slice-of-life"], mood: ["feel-good", "comfort-background"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["long-runner"], love: ["humor", "emotional-weight"],
  },
  {
    id: "the-simpsons", name: "The Simpsons", type: "show",
    plot: "The longest-running sitcom on television, following the yellow, perpetually-not-aging Simpson family through Springfield's endless supply of absurd jobs, neighbors, and civic disasters.",
    cast: ["Dan Castellaneta", "Julie Kavner", "Nancy Cartwright"], seasons: 36, episodes: 780, year: 1989,
    platforms: ["Disney+ Hotstar"], genre: ["comedy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["classic"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "daredevil-born-again", name: "Daredevil: Born Again", type: "show",
    plot: "Matt Murdock tries to leave his vigilante life behind for good, but a newly elected, increasingly authoritarian mayor of New York — his old enemy Wilson Fisk — makes staying retired impossible.",
    cast: ["Charlie Cox", "Vincent D'Onofrio", "Margarita Levieva"], seasons: 1, episodes: 9, year: 2025,
    platforms: ["Disney+ Hotstar"], genre: ["action", "drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "moana", name: "Moana", type: "movie",
    plot: "A headstrong island chief's daughter sets sail across the open ocean with a washed-up demigod to save her people, guided only by the ocean itself and her own stubborn sense of purpose.",
    cast: ["Auli'i Cravalho", "Dwayne Johnson", "Rachel House"], runtime: 107, year: 2016,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "frozen-ii", name: "Frozen II", type: "movie",
    plot: "Elsa hears a mysterious voice calling her north into an enchanted forest, where the truth about her kingdom's founding — and her own powers — turns out to be a lot more complicated than she knew.",
    cast: ["Idina Menzel", "Kristen Bell", "Jonathan Groff"], runtime: 103, year: 2019,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy"], mood: ["feel-good", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "luca", name: "Luca", type: "movie",
    plot: "A young sea monster spends a secret summer as a human boy on the Italian coast, chasing a Vespa dream with his new best friend while hiding what he really is from an entire town of monster-hunters.",
    cast: ["Jacob Tremblay", "Jack Dylan Grazer", "Emma Berman"], runtime: 95, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "turning-red", name: "Turning Red", type: "movie",
    plot: "A thirteen-year-old discovers that intense emotions turn her into a giant red panda — an inconvenient family curse that lands right in the middle of boy-band obsessions, first crushes, and her mother's suffocating expectations.",
    cast: ["Rosalie Chiang", "Sandra Oh", "Ava Morse"], runtime: 100, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "zootopia", name: "Zootopia", type: "movie",
    plot: "The first rabbit cop on the force teams up with a small-time fox con artist to crack a missing-persons case that unravels into a conspiracy exposing the whole city's buried prejudices.",
    cast: ["Ginnifer Goodwin", "Jason Bateman", "Idris Elba"], runtime: 108, year: 2016,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "mystery"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "inside-out", name: "Inside Out", type: "movie",
    plot: "Inside the mind of an eleven-year-old uprooted by a cross-country move, five personified emotions scramble to keep her stable — and Joy has to learn that Sadness isn't the enemy she thinks she is.",
    cast: ["Amy Poehler", "Phyllis Smith", "Bill Hader"], runtime: 95, year: 2015,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "the-lion-king-2019", name: "The Lion King", type: "movie",
    plot: "A photorealistic retelling of the young lion prince Simba's journey from exile to reclaiming his father's throne from the uncle who murdered him.",
    cast: ["Donald Glover", "Beyoncé", "Chiwetel Ejiofor"], runtime: 118, year: 2019,
    platforms: ["Disney+ Hotstar"], genre: ["drama", "fantasy"], mood: ["intense", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "guardians-of-the-galaxy-vol-3", name: "Guardians of the Galaxy Vol. 3", type: "movie",
    plot: "The Guardians go all-in on a dangerous mission to save Rocket's life, forcing a confrontation with the geneticist who engineered him and the cruelty he never fully escaped.",
    cast: ["Chris Pratt", "Zoe Saldaña", "Dave Bautista"], runtime: 150, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi", "comedy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "doctor-strange-multiverse-of-madness", name: "Doctor Strange in the Multiverse of Madness", type: "movie",
    plot: "Doctor Strange teams up with a teenager who can travel between universes to protect her from a former ally corrupted by dark magic and hell-bent on stealing her powers.",
    cast: ["Benedict Cumberbatch", "Elizabeth Olsen", "Xochitl Gomez"], runtime: 126, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["action", "fantasy", "horror"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "thor-ragnarok", name: "Thor: Ragnarok", type: "movie",
    plot: "Stripped of his hammer and his home, Thor is thrown into gladiatorial combat on a trash-planet run by an eccentric collector, and has to team up with the Hulk to stop his own sister from destroying Asgard.",
    cast: ["Chris Hemsworth", "Tom Hiddleston", "Cate Blanchett"], runtime: 130, year: 2017,
    platforms: ["Disney+ Hotstar"], genre: ["action", "comedy", "sci-fi"], mood: ["funny-witty", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "black-widow-marvel", name: "Black Widow", type: "movie",
    plot: "Years before her death, Natasha Romanoff confronts the family she never chose — a fractured team of Soviet-trained spies — to bring down the man who trained them all as weapons.",
    cast: ["Scarlett Johansson", "Florence Pugh", "David Harbour"], runtime: 134, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["action", "thriller"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "shang-chi", name: "Shang-Chi and the Legend of the Ten Rings", type: "movie",
    plot: "A San Francisco valet is forced to confront the past he ran from when his estranged father — the immortal leader of a criminal dynasty — comes looking to pull him back in.",
    cast: ["Simu Liu", "Awkwafina", "Tony Leung"], runtime: 132, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["action", "fantasy"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "eternals", name: "Eternals", type: "movie",
    plot: "A team of god-like immortals who've secretly shaped human history for 7,000 years has to reunite and reveal themselves to stop an ancient threat they were actually forbidden to interfere with.",
    cast: ["Gemma Chan", "Richard Madden", "Angelina Jolie"], runtime: 157, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi", "drama"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "raya-and-the-last-dragon", name: "Raya and the Last Dragon", type: "movie",
    plot: "In a fantasy land shattered by ancient monsters and centuries-old mistrust, a lone warrior sets off to find the last dragon and prove that trusting people again might actually be worth the risk.",
    cast: ["Kelly Marie Tran", "Awkwafina", "Gemma Chan"], runtime: 107, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "action"], mood: ["feel-good", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "elemental", name: "Elemental", type: "movie",
    plot: "In a city where fire, water, land, and air residents all live side by side, a hotheaded young flame-woman and a go-with-the-flow water-guy fall for each other despite everyone insisting their elements just don't mix.",
    cast: ["Leah Lewis", "Mamoudou Athie"], runtime: 102, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["romance", "fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "the-little-mermaid-2023", name: "The Little Mermaid", type: "movie",
    plot: "A live-action retelling of the mermaid princess who trades her voice to a sea witch for a chance at legs, human legs, and the surface-world prince she can't stop thinking about.",
    cast: ["Halle Bailey", "Jonah Hauer-King", "Melissa McCarthy"], runtime: 135, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "romance"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "cruella", name: "Cruella", type: "movie",
    plot: "In 1970s punk-era London, a gifted young fashion talent transforms from small-time grifter into the flamboyant, ruthless designer the world will come to know as Cruella de Vil.",
    cast: ["Emma Stone", "Emma Thompson", "Joel Fry"], runtime: 134, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["drama", "comedy"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "pinocchio-2022", name: "Pinocchio", type: "movie",
    plot: "A live-action retelling of the wooden puppet brought to life by a wishing star, who has to prove himself brave, truthful, and unselfish before he can become a real boy.",
    cast: ["Tom Hanks", "Benjamin Evan Ainsworth", "Joseph Gordon-Levitt"], runtime: 105, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "up", name: "Up", type: "movie",
    plot: "A cranky 78-year-old widower ties thousands of balloons to his house to finally chase the childhood adventure he and his late wife always promised each other — and finds an accidental stowaway kid already on board.",
    cast: ["Ed Asner", "Jordan Nagai", "Christopher Plummer"], runtime: 96, year: 2009,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "toy-story", name: "Toy Story", type: "movie",
    plot: "A cowboy doll's cushy status as a kid's favorite toy is threatened by the arrival of a flashy new space ranger action figure, and the two rivals have to survive being lost together to become friends.",
    cast: ["Tom Hanks", "Tim Allen", "Don Rickles"], runtime: 81, year: 1995,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "finding-nemo", name: "Finding Nemo", type: "movie",
    plot: "An overprotective clownfish crosses the entire ocean to find his son after he's captured by a diver, teaming up with a forgetful blue tang who might be more help than he expects.",
    cast: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould"], runtime: 100, year: 2003,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "wall-e", name: "WALL-E", type: "movie",
    plot: "The last working robot on a trash-covered, abandoned Earth falls for a sleek scout robot sent from space, and inadvertently leads all of humanity back home along the way.",
    cast: ["Ben Burtt", "Elissa Knight", "Jeff Garlin"], runtime: 98, year: 2008,
    platforms: ["Disney+ Hotstar"], genre: ["sci-fi", "romance"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "ratatouille", name: "Ratatouille", type: "movie",
    plot: "A rat with a genius palate and dreams of becoming a chef teams up with a hapless kitchen boy in Paris, secretly controlling his cooking from underneath his toque to save a failing restaurant.",
    cast: ["Patton Oswalt", "Lou Romano", "Ian Holm"], runtime: 111, year: 2007,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
];
