import type { RawTitle } from "../shape";

/** Batch 004 — Prime Video focus. */
export const RAW: RawTitle[] = [
  {
    id: "the-rings-of-power", name: "The Lord of the Rings: The Rings of Power", type: "show",
    plot: "Thousands of years before Frodo's journey, elves, dwarves, and humans face the first stirrings of a rising darkness — and a mysterious figure of great power moves quietly among them.",
    cast: ["Morfydd Clark", "Robert Aramayo", "Charlie Vickers"], seasons: 2, episodes: 16, year: 2022,
    platforms: ["Prime Video"], genre: ["fantasy", "action"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["multi-season"], love: ["world-building", "plot-twists"],
  },
  {
    id: "reacher", name: "Reacher", type: "show",
    plot: "A drifting ex-military cop with nothing but a toothbrush and his fists gets arrested for a murder he didn't commit, and ends up unraveling a conspiracy that goes straight to the top of the town he's passing through.",
    cast: ["Alan Ritchson", "Malcolm Goodwin", "Willa Fitzgerald"], seasons: 3, episodes: 24, year: 2022,
    platforms: ["Prime Video"], genre: ["action", "thriller", "mystery"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["multi-season"], love: ["plot-twists", "characters"],
  },
  {
    id: "gen-v", name: "Gen V", type: "show",
    plot: "At the first-ever college for young superheroes, a new class of students competes for a spot on the top hero team — and quickly discovers the school is hiding something far darker than any of them expected.",
    cast: ["Jaz Sinclair", "Chance Perdomo", "Lizze Broadway"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Prime Video"], genre: ["action", "drama", "horror"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "clarksons-farm", name: "Clarkson's Farm", type: "show",
    plot: "A famously loud car-show host buys a 1,000-acre farm with zero experience and documents every disastrous, hilarious lesson British agriculture has to teach him about weather, bureaucracy, and sheep.",
    cast: ["Jeremy Clarkson", "Kaleb Cooper", "Lisa Hogan"], seasons: 3, episodes: 24, year: 2021,
    platforms: ["Prime Video"], genre: ["comedy", "documentary"], mood: ["funny-witty", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "daisy-jones-and-the-six", name: "Daisy Jones & The Six", type: "show",
    plot: "Told as a documentary decades after the fact, a magnetic singer and a fiercely talented band ride a meteoric rise to 1970s rock stardom that implodes right at the peak of their success.",
    cast: ["Riley Keough", "Sam Claflin", "Camila Morrone"], seasons: 1, episodes: 10, year: 2023,
    platforms: ["Prime Video"], genre: ["drama", "romance"], mood: ["intense", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-terminal-list", name: "The Terminal List", type: "show",
    plot: "A Navy SEAL commander returns from a mission gone wrong that killed his entire platoon, and starts pulling on threads that suggest the ambush wasn't an accident at all.",
    cast: ["Chris Pratt", "Constance Wu", "Taylor Kitsch"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Prime Video"], genre: ["action", "thriller"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "hunters", name: "Hunters", type: "show",
    plot: "In 1970s New York, a ragtag band of Nazi hunters recruits a young comic-book nerd into their crusade to track down high-ranking Nazis who've been secretly living free in America for decades.",
    cast: ["Al Pacino", "Logan Lerman", "Jerrika Hinton"], seasons: 2, episodes: 18, year: 2020,
    platforms: ["Prime Video"], genre: ["thriller", "action", "drama"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "bosch", name: "Bosch", type: "show",
    plot: "A dogged LA homicide detective works cases the department would rather leave closed, bending every rule he can to get justice for people no one else is fighting for.",
    cast: ["Titus Welliver", "Jamie Hector", "Amy Aquino"], seasons: 7, episodes: 68, year: 2014,
    platforms: ["Prime Video"], genre: ["mystery", "thriller", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["plot-twists", "characters"],
  },
  {
    id: "good-omens", name: "Good Omens", type: "show",
    plot: "An angel and a demon who've grown a little too fond of Earth team up to sabotage the apocalypse, since neither of them is actually looking forward to the end of the world they've come to enjoy.",
    cast: ["David Tennant", "Michael Sheen", "Jon Hamm"], seasons: 2, episodes: 12, year: 2019,
    platforms: ["Prime Video"], genre: ["comedy", "fantasy"], mood: ["funny-witty", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "the-grand-tour", name: "The Grand Tour", type: "show",
    plot: "Three middle-aged car obsessives travel the globe destroying, racing, and generally misusing an endless parade of absurd vehicles, bickering with each other the entire time.",
    cast: ["Jeremy Clarkson", "Richard Hammond", "James May"], seasons: 5, episodes: 46, year: 2016,
    platforms: ["Prime Video"], genre: ["comedy", "documentary"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["humor", "characters"],
  },
  {
    id: "carnival-row", name: "Carnival Row", type: "show",
    plot: "In a Victorian-flavored city where refugee fairies and other mythical creatures live as an oppressed underclass, a human detective and a fae woman he once loved end up on opposite sides of a string of murders.",
    cast: ["Orlando Bloom", "Cara Delevingne", "David Gyasi"], seasons: 2, episodes: 18, year: 2019,
    platforms: ["Prime Video"], genre: ["fantasy", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "jury-duty", name: "Jury Duty", type: "show",
    plot: "One ordinary guy thinks he's serving on a real jury trial for weeks straight — every other juror, lawyer, and witness is secretly an actor, and only he doesn't know it's all an elaborate hidden-camera prank.",
    cast: ["Ronald Gladden", "James Marsden"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Prime Video"], genre: ["comedy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "citadel", name: "Citadel", type: "show",
    plot: "Two elite spies for a fallen global agency lost all memory of their old lives when it collapsed — until one of their oldest enemies resurfaces and drags them both back into the fight.",
    cast: ["Priyanka Chopra Jonas", "Richard Madden", "Stanley Tucci"], seasons: 1, episodes: 6, year: 2023,
    platforms: ["Prime Video"], genre: ["action", "thriller"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-summer-i-turned-pretty", name: "The Summer I Turned Pretty", type: "show",
    plot: "A teenage girl's yearly summer at the beach house with her mom's best friend's family turns complicated the year she finally starts noticing the two brothers she grew up with as something more than friends.",
    cast: ["Lola Tung", "Christopher Briney", "Gavin Casalegno"], seasons: 3, episodes: 22, year: 2022,
    platforms: ["Prime Video"], genre: ["romance", "drama"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "them", name: "Them", type: "show",
    plot: "A Black family relocating to an all-white 1950s Los Angeles neighborhood during the Great Migration faces escalating, increasingly supernatural terror from neighbors determined to drive them out.",
    cast: ["Deborah Ayorinde", "Ashley Thomas", "Alison Pill"], seasons: 2, episodes: 18, year: 2021,
    platforms: ["Prime Video"], genre: ["horror", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "plot-twists"],
  },
  {
    id: "mr-and-mrs-smith-2024", name: "Mr. & Mrs. Smith", type: "show",
    plot: "Two strangers are paired up as an arranged spy couple for a mysterious agency, taking on outlandish global missions together while their fake marriage keeps threatening to become uncomfortably real.",
    cast: ["Donald Glover", "Maya Erskine"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Prime Video"], genre: ["action", "comedy", "romance"], mood: ["funny-witty", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "my-lady-jane", name: "My Lady Jane", type: "show",
    plot: "A wildly revisionist, funny take on the nine-day queen of England, reimagined with magic, shapeshifters, and a much, much happier ending than the real Lady Jane Grey ever got.",
    cast: ["Emily Bader", "Edward Bluemel", "Jordan Peters"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Prime Video"], genre: ["fantasy", "romance", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "the-tomorrow-war", name: "The Tomorrow War", type: "movie",
    plot: "Soldiers from thirty years in the future arrive with a desperate message: humanity is losing a war against an alien species, and they need to draft people from the present to help fight it.",
    cast: ["Chris Pratt", "Yvonne Strahovski", "J.K. Simmons"], runtime: 138, year: 2021,
    platforms: ["Prime Video"], genre: ["sci-fi", "action"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "air", name: "Air", type: "movie",
    plot: "A Nike talent scout makes a risky, career-defining pitch to sign an unproven rookie named Michael Jordan, betting the company's entire basketball future on one unconventional deal.",
    cast: ["Matt Damon", "Ben Affleck", "Viola Davis"], runtime: 111, year: 2023,
    platforms: ["Prime Video"], genre: ["drama"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "road-house-2024", name: "Road House", type: "movie",
    plot: "An ex-UFC fighter takes a job as a bouncer at a rough Florida Keys roadhouse, only to find the town's real problems go a lot deeper than a few bar fights.",
    cast: ["Jake Gyllenhaal", "Daniela Melchior", "Conor McGregor"], runtime: 121, year: 2024,
    platforms: ["Prime Video"], genre: ["action"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "saltburn", name: "Saltburn", type: "movie",
    plot: "A scholarship student at Oxford gets invited to spend the summer at his wealthy new friend's sprawling estate, and his fascination with the family curdles into something much more dangerous.",
    cast: ["Barry Keoghan", "Jacob Elordi", "Rosamund Pike"], runtime: 131, year: 2023,
    platforms: ["Prime Video"], genre: ["thriller", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "my-policeman", name: "My Policeman", type: "movie",
    plot: "Told across two timelines, a 1950s policeman's marriage is complicated by his secret, illegal relationship with a museum curator — a decision whose consequences all three of them are still living with decades later.",
    cast: ["Harry Styles", "Emma Corrin", "David Dawson"], runtime: 113, year: 2022,
    platforms: ["Prime Video"], genre: ["romance", "drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "being-the-ricardos", name: "Being the Ricardos", type: "movie",
    plot: "Over one high-pressure production week on I Love Lucy, Lucille Ball and Desi Arnaz face a Communist accusation, tabloid rumors, and a marriage under real strain, all while still having to be funny on camera.",
    cast: ["Nicole Kidman", "Javier Bardem", "J.K. Simmons"], runtime: 132, year: 2021,
    platforms: ["Prime Video"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "coming-2-america", name: "Coming 2 America", type: "movie",
    plot: "The now-king of Zamunda learns he has a long-lost son in Queens and has to bring him back home to be trained up as a proper prince, whether the kid actually wants the crown or not.",
    cast: ["Eddie Murphy", "Arsenio Hall", "Jermaine Fowler"], runtime: 110, year: 2021,
    platforms: ["Prime Video"], genre: ["comedy"], mood: ["funny-silly", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "borat-subsequent-moviefilm", name: "Borat Subsequent Moviefilm", type: "movie",
    plot: "Kazakhstan's disgraced star journalist returns to America to deliver a bribe on behalf of his nation, dragging his teenage daughter along for an even more chaotic sequel to his first disastrous trip.",
    cast: ["Sacha Baron Cohen", "Maria Bakalova"], runtime: 96, year: 2020,
    platforms: ["Prime Video"], genre: ["comedy"], mood: ["funny-silly"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "plot-twists"],
  },
  {
    id: "sound-of-metal", name: "Sound of Metal", type: "movie",
    plot: "A heavy-metal drummer's world falls apart when he suddenly starts losing his hearing, forcing him into a deaf recovery community that teaches him silence isn't the same thing as loss.",
    cast: ["Riz Ahmed", "Olivia Cooke", "Paul Raci"], runtime: 120, year: 2019,
    platforms: ["Prime Video"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "manchester-by-the-sea", name: "Manchester by the Sea", type: "movie",
    plot: "A withdrawn Boston handyman is forced to return to his hometown and become guardian to his teenage nephew after his brother dies, dragging him back into a grief he's spent years trying to outrun.",
    cast: ["Casey Affleck", "Michelle Williams", "Lucas Hedges"], runtime: 137, year: 2016,
    platforms: ["Prime Video"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-big-sick", name: "The Big Sick", type: "movie",
    plot: "A Pakistani-American comedian's budding relationship with a grad student hits a wall over his family's expectations for an arranged marriage — right before she's suddenly put into a medically induced coma.",
    cast: ["Kumail Nanjiani", "Zoe Kazan", "Holly Hunter"], runtime: 119, year: 2017,
    platforms: ["Prime Video"], genre: ["romance", "comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "you-were-never-really-here", name: "You Were Never Really Here", type: "movie",
    plot: "A traumatized hitman who specializes in rescuing trafficked girls takes a job to find a senator's missing daughter, and finds the conspiracy underneath it reaches further than he's prepared for.",
    cast: ["Joaquin Phoenix", "Ekaterina Samsonov"], runtime: 89, year: 2017,
    platforms: ["Prime Video"], genre: ["thriller", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "late-night", name: "Late Night", type: "movie",
    plot: "A legendary but fading late-night host hires her show's only female writer specifically to look progressive — and the writer has to prove she's more than a token before the show gets cancelled around both of them.",
    cast: ["Emma Thompson", "Mindy Kaling", "John Lithgow"], runtime: 102, year: 2019,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
];
