import type { RawTitle } from "../shape";

/** Batch 005 — Hulu focus. */
export const RAW: RawTitle[] = [
  {
    id: "its-always-sunny-in-philadelphia", name: "It's Always Sunny in Philadelphia", type: "show",
    plot: "Five deeply selfish, scheming friends run a barely-functioning Irish bar in Philadelphia, and their get-rich-quick schemes and petty rivalries somehow keep getting worse with every season.",
    cast: ["Rob McElhenney", "Charlie Day", "Glenn Howerton"], seasons: 16, episodes: 172, year: 2005,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-silly", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["classic"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "american-horror-story", name: "American Horror Story", type: "show",
    plot: "An anthology series that reinvents itself every season with a new cast, setting, and flavor of horror — a haunted house, an asylum, a witch coven, a freak show — all told by mostly the same rotating troupe of actors.",
    cast: ["Sarah Paulson", "Evan Peters", "Jessica Lange"], seasons: 12, episodes: 129, year: 2011,
    platforms: ["Hulu"], genre: ["horror"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["classic"],
    length: ["long-runner"], love: ["world-building", "characters"],
  },
  {
    id: "solar-opposites", name: "Solar Opposites", type: "show",
    plot: "A family of aliens stranded on Earth after their home planet blows up have wildly different opinions on whether human life is even worth preserving, while a shrunken pod of exiled family members wages tiny wars in the wall.",
    cast: ["Justin Roiland", "Thomas Middleditch", "Sean Giambrone"], seasons: 5, episodes: 48, year: 2020,
    platforms: ["Hulu"], genre: ["comedy", "sci-fi"], mood: ["funny-silly", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["humor", "world-building"],
  },
  {
    id: "futurama", name: "Futurama", type: "show",
    plot: "A hapless 1999 pizza-delivery guy is cryogenically frozen and wakes up 1,000 years later, taking a job delivering packages across the galaxy for his mutant descendant's shipping company.",
    cast: ["Billy West", "Katey Sagal", "John DiMaggio"], seasons: 12, episodes: 169, year: 1999,
    platforms: ["Hulu"], genre: ["comedy", "sci-fi"], mood: ["funny-witty", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["episodic"], completion: ["ongoing"], recency: ["classic"],
    length: ["long-runner"], love: ["humor", "world-building"],
  },
  {
    id: "shogun", name: "Shogun", type: "show",
    plot: "A shipwrecked English navigator becomes an unwilling pawn in a brutal feudal power struggle in 1600s Japan, caught between rival warlords all maneuvering for the position of supreme military ruler.",
    cast: ["Hiroyuki Sanada", "Anna Sawai", "Cosmo Jarvis"], seasons: 1, episodes: 10, year: 2024,
    platforms: ["Hulu"], genre: ["drama", "action"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "cruel-summer", name: "Cruel Summer", type: "show",
    plot: "Told across three summers, a once-invisible teenager becomes the town pariah when she's accused of doing nothing to help a missing classmate — and the truth turns out to be far messier than anyone assumed.",
    cast: ["Chiara Aurelia", "Olivia Holt", "Froy Gutierrez"], seasons: 2, episodes: 20, year: 2021,
    platforms: ["Hulu"], genre: ["mystery", "thriller", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "nine-perfect-strangers", name: "Nine Perfect Strangers", type: "show",
    plot: "Nine stressed-out strangers check into an exclusive wellness retreat looking for healing, unaware the charismatic director running it has some deeply unconventional, unauthorized methods planned for them.",
    cast: ["Nicole Kidman", "Melissa McCarthy", "Michael Shannon"], seasons: 2, episodes: 17, year: 2021,
    platforms: ["Hulu"], genre: ["drama", "mystery", "thriller"], mood: ["cerebral-mystery", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "little-fires-everywhere", name: "Little Fires Everywhere", type: "show",
    plot: "A carefully controlled suburban mother and the free-spirited artist renting her guest house form a tense, complicated friendship that ends up burning down more than just the family's house.",
    cast: ["Reese Witherspoon", "Kerry Washington", "Joshua Jackson"], seasons: 1, episodes: 8, year: 2020,
    platforms: ["Hulu"], genre: ["drama", "mystery"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "normal-people", name: "Normal People", type: "show",
    plot: "Two Irish teenagers from opposite ends of their small town's social ladder fall into an on-again, off-again relationship that follows them from secondary school all the way through university.",
    cast: ["Daisy Edgar-Jones", "Paul Mescal"], seasons: 1, episodes: 12, year: 2020,
    platforms: ["Hulu"], genre: ["romance", "drama"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-great", name: "The Great", type: "show",
    plot: "A wildly fictionalized, gleefully anachronistic account of how a naive young Catherine the Great plotted a coup against her idiot husband Peter III to seize the Russian throne for herself.",
    cast: ["Elle Fanning", "Nicholas Hoult", "Phoebe Fox"], seasons: 3, episodes: 30, year: 2020,
    platforms: ["Hulu"], genre: ["comedy", "drama"], mood: ["funny-witty", "dark"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["humor", "characters"],
  },
  {
    id: "pen15", name: "PEN15", type: "show",
    plot: "Two thirty-something women play their own thirteen-year-old selves, cast among actual middle-schoolers, reliving every mortifying, hilarious detail of being an awkward seventh grader in the year 2000.",
    cast: ["Maya Erskine", "Anna Konkle"], seasons: 2, episodes: 28, year: 2019,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "emotional-weight"],
  },
  {
    id: "ramy", name: "Ramy", type: "show",
    plot: "A first-generation Egyptian-American in New Jersey stumbles his way through faith, family, and dating, trying to reconcile being a good Muslim with basically every impulse he actually has.",
    cast: ["Ramy Youssef", "Hiam Abbass", "Amr Waked"], seasons: 3, episodes: 30, year: 2019,
    platforms: ["Hulu"], genre: ["comedy", "drama"], mood: ["funny-witty", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "dave", name: "Dave", type: "show",
    plot: "A neurotic rapper with an oversized ego and an undersized reputation tries to actually make it in the industry, loosely based on the real early career of rapper Lil Dicky.",
    cast: ["Dave Burd", "GaTa", "Taylor Misiak"], seasons: 4, episodes: 40, year: 2020,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "what-we-do-in-the-shadows", name: "What We Do in the Shadows", type: "show",
    plot: "A documentary crew follows four vampire roommates sharing a run-down Staten Island house, struggling with roommate chores, ancient rivalries, and the occasional attempt at world domination.",
    cast: ["Kayvan Novak", "Matt Berry", "Natasia Demetriou"], seasons: 6, episodes: 60, year: 2019,
    platforms: ["Hulu"], genre: ["comedy", "horror"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "kindred", name: "Kindred", type: "show",
    plot: "A young Black woman in modern LA is repeatedly and violently yanked back in time to a pre-Civil-War plantation, where she has to keep an enslaved ancestor alive long enough to secure her own existence.",
    cast: ["Mallori Johnson", "Micah Stock", "Ryan Kwanten"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Hulu"], genre: ["sci-fi", "drama", "horror"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "plot-twists"],
  },
  {
    id: "devs", name: "Devs", type: "show",
    plot: "A software engineer at a secretive quantum-computing company investigates her boyfriend's mysterious death, uncovering a hidden research project that claims to be able to predict — and maybe control — the future.",
    cast: ["Sonoya Mizuno", "Nick Offerman", "Zach Grenier"], seasons: 1, episodes: 8, year: 2020,
    platforms: ["Hulu"], genre: ["sci-fi", "mystery", "thriller"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "high-fidelity", name: "High Fidelity", type: "show",
    plot: "A Brooklyn record-store owner obsessed with top-five lists digs back through her worst breakups trying to figure out the actual pattern behind why her relationships keep failing.",
    cast: ["Zoë Kravitz", "David H. Holmes", "Da'Vine Joy Randolph"], seasons: 1, episodes: 10, year: 2020,
    platforms: ["Hulu"], genre: ["comedy", "romance", "drama"], mood: ["funny-witty", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "under-the-bridge", name: "Under the Bridge", type: "show",
    plot: "Based on a true case, a journalist returning to her hometown gets pulled into the investigation of a teenage girl's murder, uncovering how a close-knit group of friends turned violently against one of their own.",
    cast: ["Riley Keough", "Lily Gladstone", "Chloe Guidry"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Hulu"], genre: ["drama", "mystery", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["emotional-weight", "plot-twists"],
  },
  {
    id: "woke", name: "Woke", type: "show",
    plot: "A politically neutral Black cartoonist has a public run-in with police brutality that shatters his previous ambivalence, and he starts literally hearing his art supplies talk to him about it.",
    cast: ["Lamorne Morris", "Sasheer Zamata", "T. Murph"], seasons: 2, episodes: 16, year: 2020,
    platforms: ["Hulu"], genre: ["comedy", "drama"], mood: ["funny-witty", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "prey-2022", name: "Prey", type: "movie",
    plot: "In the Comanche Nation 300 years ago, a skilled young woman determined to prove herself as a hunter finds herself facing off against an alien predator hunting her tribe's land.",
    cast: ["Amber Midthunder", "Dakota Beavers"], runtime: 100, year: 2022,
    platforms: ["Hulu"], genre: ["action", "horror", "sci-fi"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "no-one-will-save-you", name: "No One Will Save You", type: "movie",
    plot: "A reclusive young woman living alone in a quiet house has to fight off an alien home invasion almost entirely without dialogue, relying purely on wits and physical instinct to survive the night.",
    cast: ["Kaitlyn Dever"], runtime: 93, year: 2023,
    platforms: ["Hulu"], genre: ["horror", "sci-fi"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "quiz-lady", name: "Quiz Lady", type: "movie",
    plot: "A quiz-show-obsessed woman reluctantly teams up with her estranged, chaotic sister to pay off their mother's gambling debt by getting her onto her favorite trivia show before loan sharks catch up with them.",
    cast: ["Awkwafina", "Sandra Oh", "Will Ferrell"], runtime: 92, year: 2023,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "theater-camp", name: "Theater Camp", type: "movie",
    plot: "When the beloved founder of a scrappy performing-arts summer camp falls into a coma, her clueless influencer son has to keep the place running with the help of the eccentric, fiercely devoted staff.",
    cast: ["Molly Gordon", "Ben Platt", "Noah Galvin"], runtime: 94, year: 2023,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "rye-lane", name: "Rye Lane", type: "movie",
    plot: "Two twenty-somethings both nursing fresh breakups meet at an art show and spend one long, wandering day walking around South London together, falling for each other without quite admitting it.",
    cast: ["David Jonsson", "Vivian Oparah"], runtime: 82, year: 2023,
    platforms: ["Hulu"], genre: ["romance", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
];
