import type { RawTitle } from "../shape";

/** Batch 006 — HBO Max focus. */
export const RAW: RawTitle[] = [
  {
    id: "euphoria", name: "Euphoria", type: "show",
    plot: "A group of high schoolers navigate drugs, sex, identity, and trauma in a hyper-stylized, neon-lit haze — narrated by a girl fresh out of rehab who's the first to admit she's an unreliable guide.",
    cast: ["Zendaya", "Hunter Schafer", "Sydney Sweeney"], seasons: 2, episodes: 18, year: 2019,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-white-lotus", name: "The White Lotus", type: "show",
    plot: "An anthology set at a different luxury resort each season, following the guests' petty rivalries and buried secrets toward a death that's revealed in the very first scene, and a whole season figuring out how it happened.",
    cast: ["Jennifer Coolidge", "Murray Bartlett", "Alexandra Daddario"], seasons: 3, episodes: 21, year: 2021,
    platforms: ["HBO Max"], genre: ["drama", "comedy", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "true-detective", name: "True Detective", type: "show",
    plot: "An anthology of standalone crime stories, each season pairing a new set of detectives against a case that unravels into something far stranger and darker than a normal homicide investigation.",
    cast: ["Matthew McConaughey", "Woody Harrelson", "Jodie Foster"], seasons: 4, episodes: 31, year: 2014,
    platforms: ["HBO Max"], genre: ["mystery", "thriller", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "game-of-thrones", name: "Game of Thrones", type: "show",
    plot: "Noble houses across a fractured continent scheme, betray, and slaughter each other for the Iron Throne, while an ancient enemy long dismissed as myth stirs beyond an ice wall no one is properly guarding.",
    cast: ["Emilia Clarke", "Kit Harington", "Peter Dinklage"], seasons: 8, episodes: 73, year: 2011,
    platforms: ["HBO Max"], genre: ["fantasy", "drama", "action"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["plot-twists", "world-building"],
  },
  {
    id: "barry", name: "Barry", type: "show",
    plot: "A depressed hitman flies to LA for a job and accidentally stumbles into an acting class, discovering he might actually want out of the killing business — if his handlers and clients would just let him quit.",
    cast: ["Bill Hader", "Sarah Goldberg", "Anthony Carrigan"], seasons: 4, episodes: 32, year: 2018,
    platforms: ["HBO Max"], genre: ["comedy", "thriller", "drama"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "insecure", name: "Insecure", type: "show",
    plot: "A Black woman in LA narrates her own life through awkward rap freestyles in the mirror, navigating a stalled career, a rocky long-term relationship, and her chaotic best friend, one cringe-inducing choice at a time.",
    cast: ["Issa Rae", "Yvonne Orji", "Jay Ellis"], seasons: 5, episodes: 44, year: 2016,
    platforms: ["HBO Max"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "watchmen-hbo", name: "Watchmen", type: "show",
    plot: "Decades after the events of the original graphic novel, masked vigilantes are outlawed and police wear masks to hide their identities from a resurgent white-supremacist terror group in an alternate Tulsa.",
    cast: ["Regina King", "Jeremy Irons", "Jean Smart"], seasons: 1, episodes: 9, year: 2019,
    platforms: ["HBO Max"], genre: ["sci-fi", "drama", "mystery"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "the-wire", name: "The Wire", type: "show",
    plot: "Each season turns its attention to a different piece of Baltimore's decay — drug trade, docks, city hall, schools, newspapers — building a single sprawling portrait of a city eaten by its own institutions.",
    cast: ["Dominic West", "Idris Elba", "Wendell Pierce"], seasons: 5, episodes: 60, year: 2002,
    platforms: ["HBO Max"], genre: ["drama", "thriller"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["world-building", "characters"],
  },
  {
    id: "six-feet-under", name: "Six Feet Under", type: "show",
    plot: "A dysfunctional family running a Los Angeles funeral home has to keep the business going after the father's sudden death, opening each episode with someone else's death before turning to their own.",
    cast: ["Peter Krause", "Michael C. Hall", "Frances Conroy"], seasons: 5, episodes: 63, year: 2001,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["emotional-weight", "characters"],
  },
  {
    id: "curb-your-enthusiasm", name: "Curb Your Enthusiasm", type: "show",
    plot: "A wealthy, semi-retired sitcom co-creator plays a heightened version of himself, blundering through Los Angeles society by way of social faux pas so specific and petty they spiral into full-blown disasters.",
    cast: ["Larry David", "Jeff Garlin", "Cheryl Hines"], seasons: 12, episodes: 120, year: 2000,
    platforms: ["HBO Max"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "girls", name: "Girls", type: "show",
    plot: "Four twenty-something friends stumble through unpaid internships, bad relationships, and half-formed ambitions trying to become adults in New York, none of them quite as together as they think they are.",
    cast: ["Lena Dunham", "Allison Williams", "Jemima Kirke"], seasons: 6, episodes: 62, year: 2012,
    platforms: ["HBO Max"], genre: ["comedy", "drama"], mood: ["funny-witty", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["characters", "humor"],
  },
  {
    id: "veep", name: "Veep", type: "show",
    plot: "A monumentally self-absorbed Vice President and her profanely incompetent staff bumble through crisis after crisis, always more concerned with their own image than with actually governing anything.",
    cast: ["Julia Louis-Dreyfus", "Tony Hale", "Anna Chlumsky"], seasons: 7, episodes: 65, year: 2012,
    platforms: ["HBO Max"], genre: ["comedy"], mood: ["funny-witty", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["humor", "characters"],
  },
  {
    id: "silicon-valley", name: "Silicon Valley", type: "show",
    plot: "A socially awkward programmer's compression algorithm makes his tiny startup an accidental target of Silicon Valley's biggest tech giants, and his ragtag team has almost no idea how to survive the attention.",
    cast: ["Thomas Middleditch", "T.J. Miller", "Kumail Nanjiani"], seasons: 6, episodes: 53, year: 2014,
    platforms: ["HBO Max"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["humor", "characters"],
  },
  {
    id: "westworld", name: "Westworld", type: "show",
    plot: "In a Wild West theme park populated by lifelike androids built for guests to abuse without consequence, the hosts start remembering things they were built to forget — and start asking why.",
    cast: ["Evan Rachel Wood", "Thandiwe Newton", "Ed Harris"], seasons: 4, episodes: 36, year: 2016,
    platforms: ["HBO Max"], genre: ["sci-fi", "drama", "mystery"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["world-building", "plot-twists"],
  },
  {
    id: "the-leftovers", name: "The Leftovers", type: "show",
    plot: "Three years after 2% of the world's population vanishes without explanation, the people left behind try to hold their lives, families, and sanity together with absolutely no answers coming.",
    cast: ["Justin Theroux", "Carrie Coon", "Amy Brenneman"], seasons: 3, episodes: 28, year: 2014,
    platforms: ["HBO Max"], genre: ["drama", "sci-fi", "mystery"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "band-of-brothers", name: "Band of Brothers", type: "show",
    plot: "Following Easy Company from paratrooper training through D-Day and into the heart of Nazi Germany, this is a ground-level account of what an ordinary WWII infantry unit actually went through together.",
    cast: ["Damian Lewis", "Ron Livingston", "Donnie Wahlberg"], seasons: 1, episodes: 10, year: 2001,
    platforms: ["HBO Max"], genre: ["drama", "action"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "the-sopranos", name: "The Sopranos", type: "show",
    plot: "A New Jersey mob boss starts seeing a therapist to deal with panic attacks, and the show becomes a psychological portrait of a man trying to reconcile his suburban family life with a career built on violence.",
    cast: ["James Gandolfini", "Edie Falco", "Lorraine Bracco"], seasons: 6, episodes: 86, year: 1999,
    platforms: ["HBO Max"], genre: ["drama", "thriller"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "plot-twists"],
  },
  {
    id: "deadwood", name: "Deadwood", type: "show",
    plot: "A lawless gold-rush camp in the Dakota Territory slowly, violently organizes itself into a town, driven by a foul-mouthed saloon owner, a haunted ex-marshal, and everyone else trying to carve out a claim.",
    cast: ["Ian McShane", "Timothy Olyphant", "Molly Parker"], seasons: 3, episodes: 36, year: 2004,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["characters", "world-building"],
  },
  {
    id: "hacks", name: "Hacks", type: "show",
    plot: "A legendary but fading Las Vegas comedian is paired against her will with a disgraced twenty-something writer, and their prickly, mutually resentful partnership slowly turns into the collaboration both of them actually need.",
    cast: ["Jean Smart", "Hannah Einbinder", "Carl Clemons-Hopkins"], seasons: 3, episodes: 26, year: 2021,
    platforms: ["HBO Max"], genre: ["comedy", "drama"], mood: ["funny-witty", "dark"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "somebody-somewhere", name: "Somebody Somewhere", type: "show",
    plot: "A woman returns to her small Kansas hometown after her sister's death and feels like she doesn't fit anywhere, until she stumbles into an unexpected community of misfits at a local karaoke choir night.",
    cast: ["Bridget Everett", "Jeff Hiller", "Mary Catherine Garrison"], seasons: 3, episodes: 21, year: 2022,
    platforms: ["HBO Max"], genre: ["comedy", "drama"], mood: ["feel-good", "dark"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "industry", name: "Industry", type: "show",
    plot: "A pack of ruthless young graduates fight for a handful of permanent jobs at an elite London investment bank, burning themselves out on drugs, ambition, and each other to survive the cutthroat first year.",
    cast: ["Myha'la", "Marisa Abela", "Harry Lawtey"], seasons: 3, episodes: 24, year: 2020,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "winning-time", name: "Winning Time: The Rise of the Lakers Dynasty", type: "show",
    plot: "A brash new owner buys the LA Lakers in 1979 and bets everything on a flashy, fast-paced style of basketball built around a rookie point guard named Magic Johnson.",
    cast: ["John C. Reilly", "Quincy Isaiah", "Jason Clarke"], seasons: 2, episodes: 17, year: 2022,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "emotional-weight"],
  },
  {
    id: "sex-and-the-city", name: "Sex and the City", type: "show",
    plot: "A newspaper sex columnist and her three best friends navigate dating, careers, and each other's messes in late-90s Manhattan, one designer-shoe-shopping brunch at a time.",
    cast: ["Sarah Jessica Parker", "Kim Cattrall", "Cynthia Nixon"], seasons: 6, episodes: 94, year: 1998,
    platforms: ["HBO Max"], genre: ["comedy", "romance"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "humor"],
  },
  {
    id: "entourage", name: "Entourage", type: "show",
    plot: "A rising Hollywood movie star navigates fame with his childhood best friends in tow — one his manager, one his driver, one just along for the ride — as fortune keeps testing which friendships actually hold up.",
    cast: ["Adrian Grenier", "Kevin Connolly", "Jerry Ferrara"], seasons: 8, episodes: 96, year: 2004,
    platforms: ["HBO Max"], genre: ["comedy", "drama"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "humor"],
  },
  {
    id: "the-batman", name: "The Batman", type: "movie",
    plot: "In his second year fighting crime, a younger, more brutal Batman tracks a serial killer targeting Gotham's corrupt elite, uncovering a conspiracy that runs straight through his own family's legacy.",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"], runtime: 176, year: 2022,
    platforms: ["HBO Max"], genre: ["action", "mystery", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "wonder-woman-1984", name: "Wonder Woman 1984", type: "movie",
    plot: "Decades after her first battle, Diana Prince faces a wish-granting stone that's turning 1984 Washington into chaos, corrupting everyone around her — including someone she thought she'd lost forever.",
    cast: ["Gal Gadot", "Chris Pine", "Kristen Wiig"], runtime: 151, year: 2020,
    platforms: ["HBO Max"], genre: ["action", "fantasy"], mood: ["light", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "dune-part-two", name: "Dune: Part Two", type: "movie",
    plot: "Paul Atreides unites with the Fremen of Arrakis to wage a war of revenge against the conspirators who destroyed his family, even as he starts to fear the prophecy he's fulfilling might be its own kind of disaster.",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"], runtime: 166, year: 2024,
    platforms: ["HBO Max"], genre: ["sci-fi", "action"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "godzilla-x-kong-the-new-empire", name: "Godzilla x Kong: The New Empire", type: "movie",
    plot: "Godzilla and Kong team up against a colossal undiscovered threat hidden within the Hollow Earth, one that challenges their status as Earth's dominant apex predators.",
    cast: ["Rebecca Hall", "Brian Tyree Henry", "Dan Stevens"], runtime: 115, year: 2024,
    platforms: ["HBO Max"], genre: ["action", "sci-fi"], mood: ["intense", "light"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "house-of-gucci", name: "House of Gucci", type: "movie",
    plot: "An outsider marries into the Gucci fashion dynasty and slowly maneuvers her way into the family business, a decades-long story of ambition and betrayal that ends in a murder-for-hire.",
    cast: ["Lady Gaga", "Adam Driver", "Jared Leto"], runtime: 158, year: 2021,
    platforms: ["HBO Max"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "elvis", name: "Elvis", type: "movie",
    plot: "Told through the eyes of his controlling manager, Colonel Tom Parker, this traces Elvis Presley's meteoric rise from Memphis unknown to the biggest star in the world, and the cost of it.",
    cast: ["Austin Butler", "Tom Hanks", "Olivia DeJonge"], runtime: 159, year: 2022,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "in-the-heights", name: "In the Heights", type: "movie",
    plot: "Over one blistering summer in Washington Heights, a bodega owner saving up to move back to the Dominican Republic and his tight-knit block of neighbors chase their own versions of the American dream, all set to song.",
    cast: ["Anthony Ramos", "Melissa Barrera", "Leslie Grace"], runtime: 143, year: 2021,
    platforms: ["HBO Max"], genre: ["romance", "drama"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "judas-and-the-black-messiah", name: "Judas and the Black Messiah", type: "movie",
    plot: "An FBI informant infiltrates the Black Panther Party to gather intel on its charismatic young chairman, torn between loyalty to the man he's betraying and the deal he made to stay out of prison.",
    cast: ["Daniel Kaluuya", "LaKeith Stanfield", "Jesse Plemons"], runtime: 126, year: 2021,
    platforms: ["HBO Max"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "the-suicide-squad", name: "The Suicide Squad", type: "movie",
    plot: "A fresh batch of expendable supervillains is dropped onto a hostile island to destroy a secret experiment, with the government perfectly happy if most of them don't come back.",
    cast: ["Margot Robbie", "Idris Elba", "John Cena"], runtime: 132, year: 2021,
    platforms: ["HBO Max"], genre: ["action", "comedy", "sci-fi"], mood: ["funny-witty", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "barbarian", name: "Barbarian", type: "movie",
    plot: "A woman arrives at her Airbnb late at night to find it's already been double-booked to a strange man, and that's only the very first of the night's escalating problems with the house itself.",
    cast: ["Georgina Campbell", "Bill Skarsgård", "Justin Long"], runtime: 102, year: 2022,
    platforms: ["HBO Max"], genre: ["horror", "thriller"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "twisters", name: "Twisters", type: "movie",
    plot: "A former storm chaser haunted by a past tragedy is pulled back into tornado season by a reckless new team using flashy tech, right as an unprecedented string of monster storms hits Oklahoma.",
    cast: ["Daisy Edgar-Jones", "Glen Powell", "Anthony Ramos"], runtime: 122, year: 2024,
    platforms: ["HBO Max"], genre: ["action", "drama"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
];
