import type { RawTitle } from "../shape";

/** Batch 007 — Crunchyroll / anime focus (still the thinnest category by volume). */
export const RAW: RawTitle[] = [
  {
    id: "bleach", name: "Bleach", type: "anime",
    plot: "An ordinary teenager gains soul-reaper powers after saving his family from a monstrous spirit, and takes on the job of guiding lost souls to the afterlife and fighting the monsters that prey on them.",
    cast: ["Masakazu Morita", "Fumiko Orikasa"], seasons: 17, episodes: 366, year: 2004,
    platforms: ["Crunchyroll"], genre: ["action", "fantasy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "dragon-ball-z", name: "Dragon Ball Z", type: "anime",
    plot: "Earth's strongest warrior discovers he's actually an alien from a nearly extinct warrior race, and has to keep pushing past his own limits to protect the planet from an escalating parade of galactic threats.",
    cast: ["Masako Nozawa", "Ryō Horikawa"], seasons: 9, episodes: 291, year: 1989,
    platforms: ["Crunchyroll"], genre: ["action", "fantasy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "code-geass", name: "Code Geass", type: "anime",
    plot: "An exiled prince gains a power that lets him command anyone to obey a single order, and uses it to lead a masked rebellion against the empire that conquered his homeland and killed his mother.",
    cast: ["Jun Fukuyama", "Fumiko Orikasa"], seasons: 2, episodes: 50, year: 2006,
    platforms: ["Crunchyroll"], genre: ["sci-fi", "action", "drama"], mood: ["cerebral-ideas", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["multi-season"], love: ["plot-twists", "characters"],
  },
  {
    id: "fairy-tail", name: "Fairy Tail", type: "anime",
    plot: "A teenage wizard joins the rowdy, close-knit mages of the Fairy Tail guild, taking on increasingly dangerous jobs together while looking for her missing dragon-parent across a world full of magic.",
    cast: ["Tetsuya Kakihara", "Sayaka Ohara"], seasons: 9, episodes: 328, year: 2009,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "comedy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "black-clover", name: "Black Clover", type: "anime",
    plot: "Born with zero magical power in a world where magic is everything, an orphan boy stubbornly refuses to give up on his dream of becoming the strongest mage alive, the Wizard King.",
    cast: ["Gakuto Kajiwara", "Nobunaga Shimazaki"], seasons: 4, episodes: 170, year: 2017,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "tokyo-revengers", name: "Tokyo Revengers", type: "anime",
    plot: "A washed-up 26-year-old discovers he can time-leap back into his middle-school body, and uses it to try to save his ex-girlfriend from a fate tied to the violent gang he used to run with.",
    cast: ["Yuki Shin", "Ayumu Murase"], seasons: 3, episodes: 62, year: 2021,
    platforms: ["Crunchyroll"], genre: ["action", "drama", "sci-fi"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "jojos-bizarre-adventure", name: "JoJo's Bizarre Adventure", type: "anime",
    plot: "Across multiple generations of the Joestar family, each new hero has to master a bizarre supernatural power to defeat an immortal vampire and his ever more theatrically posed enemies.",
    cast: ["Daisuke Ono", "Tomokazu Seki"], seasons: 6, episodes: 190, year: 2012,
    platforms: ["Crunchyroll"], genre: ["action", "fantasy", "horror"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "mushoku-tensei", name: "Mushoku Tensei: Jobless Reincarnation", type: "anime",
    plot: "A shut-in who wasted his entire life is reborn as a baby in a magical fantasy world, determined to actually make something of this second chance instead of repeating his old mistakes.",
    cast: ["Yumi Uchiyama", "Ai Kayano"], seasons: 2, episodes: 23, year: 2021,
    platforms: ["Crunchyroll"], genre: ["fantasy", "drama"], mood: ["cerebral-ideas", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "that-time-i-got-reincarnated-as-a-slime", name: "That Time I Got Reincarnated as a Slime", type: "anime",
    plot: "A regular office worker is killed and reborn as a slime monster in a fantasy world, and instead of panicking, immediately sets about building an entire kingdom of monsters, one friendly recruit at a time.",
    cast: ["Miho Okasaki", "Chika Anzai"], seasons: 3, episodes: 61, year: 2018,
    platforms: ["Crunchyroll"], genre: ["fantasy", "comedy", "action"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["world-building", "humor"],
  },
  {
    id: "the-rising-of-the-shield-hero", name: "The Rising of the Shield Hero", type: "anime",
    plot: "Summoned to a fantasy world as one of four legendary heroes, a college student is immediately betrayed and framed, left with only a useless-seeming shield and a fierce grudge to build his way back up from nothing.",
    cast: ["Kaito Ishikawa", "Asami Seto"], seasons: 3, episodes: 38, year: 2019,
    platforms: ["Crunchyroll", "HIDIVE"], genre: ["fantasy", "action"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "konosuba", name: "KonoSuba: God's Blessing on This Wonderful World!", type: "anime",
    plot: "A shut-in gamer dies an embarrassing death and gets a second chance in a fantasy world, but the useless goddess he brings along and the incompetent party he assembles make every quest a comedy of errors.",
    cast: ["Jun Fukushima", "Sora Amamiya"], seasons: 3, episodes: 30, year: 2016,
    platforms: ["Crunchyroll"], genre: ["comedy", "fantasy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "overlord", name: "Overlord", type: "anime",
    plot: "When a beloved MMO finally shuts down its servers, one loyal player finds himself trapped inside as his undead sorcerer avatar, now leading an army of powerful NPCs in a game world that's become frighteningly real.",
    cast: ["Satoshi Hino", "Yumi Hara"], seasons: 4, episodes: 52, year: 2015,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "characters"],
  },
  {
    id: "blue-lock", name: "Blue Lock", type: "anime",
    plot: "After a national soccer humiliation, Japan locks 300 of its most promising strikers in an isolated training facility with one brutal rule: only one of them will survive the cut to become the country's new ego-driven number nine.",
    cast: ["Kazuki Ura", "Tasuku Kaito"], seasons: 2, episodes: 24, year: 2022,
    platforms: ["Crunchyroll"], genre: ["drama", "action"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "solo-leveling", name: "Solo Leveling", type: "anime",
    plot: "The weakest hunter alive is left near death after a catastrophic dungeon raid, only to wake up with a mysterious system that lets him level up without limit — unlike everyone else in his world.",
    cast: ["Taito Ban", "Genki Muro"], seasons: 1, episodes: 12, year: 2024,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "dandadan", name: "Dandadan", type: "anime",
    plot: "A girl who believes in ghosts and a boy who believes in aliens make a bet to prove each other wrong, and immediately end up dragged into supernatural chaos involving both at once.",
    cast: ["Shion Wakayama", "Natsuki Hanae"], seasons: 1, episodes: 12, year: 2024,
    platforms: ["Crunchyroll"], genre: ["comedy", "action", "horror"], mood: ["funny-silly", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "oshi-no-ko", name: "Oshi no Ko", type: "anime",
    plot: "A doctor and his patient are murdered and reincarnated as the twin children of the pop idol they idolized, growing up inside the entertainment industry to uncover who was really responsible for her death.",
    cast: ["Takeo Otsuka", "Rie Takahashi"], seasons: 2, episodes: 22, year: 2023,
    platforms: ["Crunchyroll"], genre: ["drama", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "bocchi-the-rock", name: "Bocchi the Rock!", type: "anime",
    plot: "A crushingly shy guitarist who's never had a friend joins a high school rock band, and every rehearsal becomes an exercise in barely surviving her own social anxiety long enough to actually play.",
    cast: ["Yōmi Ise", "Sayumi Suzushiro"], seasons: 1, episodes: 12, year: 2022,
    platforms: ["Crunchyroll"], genre: ["comedy", "slice-of-life"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "ranking-of-kings", name: "Ranking of Kings", type: "anime",
    plot: "A deaf, powerless young prince too small to even lift a sword is universally underestimated by his kingdom, but his kindness earns him allies who help him prove he might be the greatest king of all.",
    cast: ["Ayumu Murase", "Yuko Sanpei"], seasons: 1, episodes: 23, year: 2021,
    platforms: ["Crunchyroll"], genre: ["fantasy", "drama"], mood: ["feel-good", "intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "horimiya", name: "Horimiya", type: "anime",
    plot: "A popular girl and a quiet, pierced-and-tattooed boy from school discover completely different secret sides of each other by accident, and start a relationship built on being the only ones who see the real version.",
    cast: ["Haruka Shiraishi", "Shun Horie"], seasons: 1, episodes: 13, year: 2021,
    platforms: ["Crunchyroll"], genre: ["romance", "comedy", "slice-of-life"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "kaguya-sama-love-is-war", name: "Kaguya-sama: Love Is War", type: "anime",
    plot: "Two elite student council officers are secretly, madly in love with each other, but both are far too proud to confess first — so every episode is an elaborate psychological chess match to make the other crack.",
    cast: ["Aoi Koga", "Makoto Furukawa"], seasons: 4, episodes: 37, year: 2019,
    platforms: ["Crunchyroll", "HIDIVE"], genre: ["romance", "comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "given", name: "Given", type: "anime",
    plot: "A guitarist finds a boy sleeping in the school stairwell cradling a broken guitar and eventually invites him into his band, not realizing how much unresolved grief the new addition is actually carrying.",
    cast: ["Yuki Ono", "Chiaki Kobayashi"], seasons: 1, episodes: 11, year: 2019,
    platforms: ["Crunchyroll"], genre: ["romance", "drama", "slice-of-life"], mood: ["feel-good", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "your-lie-in-april", name: "Your Lie in April", type: "anime",
    plot: "A piano prodigy who stopped being able to hear his own music after his mother's death is pulled back toward performing by a free-spirited violinist who plays nothing like the way he was trained.",
    cast: ["Natsuki Hanae", "Risa Taneda"], seasons: 1, episodes: 22, year: 2014,
    platforms: ["Crunchyroll"], genre: ["romance", "drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "anohana", name: "Anohana: The Flower We Saw That Day", type: "anime",
    plot: "A group of estranged childhood friends is drawn back together when the ghost of the girl who died years ago appears with an unfinished wish only they can help her grant.",
    cast: ["Haruka Tomatsu", "Miyu Irino"], seasons: 1, episodes: 11, year: 2011,
    platforms: ["Crunchyroll"], genre: ["drama", "fantasy"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "suzume", name: "Suzume", type: "anime",
    plot: "A teenage girl teams up with a mysterious young man to close a series of magical doors scattered across Japan that are unleashing disasters, on a road trip that forces her to finally confront her own past.",
    cast: ["Nanoka Hara", "Hokuto Matsumura"], runtime: 122, year: 2022,
    platforms: ["Crunchyroll"], genre: ["fantasy", "drama"], mood: ["cerebral-ideas", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "belle-anime", name: "Belle", type: "anime",
    plot: "A shy high schooler grieving her mother becomes a global pop sensation inside a massive virtual world, and has to decide how much of her real self she's willing to show behind the avatar everyone loves instead.",
    cast: ["Kaho Nakamura", "Takeru Satoh"], runtime: 122, year: 2021,
    platforms: ["Crunchyroll"], genre: ["fantasy", "drama", "romance"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["sci-fi-future"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
];
