import type { RawTitle } from "../shape";

/** Batch 008 — Netflix focus (already the biggest platform, but still needs raw volume like everything else). */
export const RAW: RawTitle[] = [
  {
    id: "squid-game", name: "Squid Game", type: "show",
    plot: "Hundreds of people drowning in debt accept a mysterious invitation to compete in a series of deadly children's games for a massive cash prize, unaware just how literally deadly the games are.",
    cast: ["Lee Jung-jae", "Park Hae-soo", "Jung Ho-yeon"], seasons: 2, episodes: 16, year: 2021,
    platforms: ["Netflix"], genre: ["thriller", "drama"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "emily-in-paris", name: "Emily in Paris", type: "show",
    plot: "An ambitious American marketing exec is transplanted to a Parisian luxury firm with zero French language skills, and has to charm her way past a whole office that finds her instantly insufferable.",
    cast: ["Lily Collins", "Philippine Leroy-Beaulieu", "Ashley Park"], seasons: 4, episodes: 40, year: 2020,
    platforms: ["Netflix"], genre: ["comedy", "romance"], mood: ["light", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "you", name: "You", type: "show",
    plot: "A charming bookstore manager becomes fixated on the woman who walks in one day, narrating his stalking and manipulation in a chillingly reasonable inner monologue that always makes himself the victim.",
    cast: ["Penn Badgley", "Victoria Pedretti", "Ambyr Childers"], seasons: 5, episodes: 50, year: 2018,
    platforms: ["Netflix"], genre: ["thriller", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["long-runner"], love: ["plot-twists", "characters"],
  },
  {
    id: "outer-banks", name: "Outer Banks", type: "show",
    plot: "A tight-knit group of working-class teens goes treasure hunting for a legendary lost gold shipment tied to one of their missing fathers, running afoul of the wealthy families who want it for themselves.",
    cast: ["Chase Stokes", "Madelyn Cline", "Madison Bailey"], seasons: 4, episodes: 40, year: 2020,
    platforms: ["Netflix"], genre: ["action", "mystery", "romance"], mood: ["light", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["long-runner"], love: ["plot-twists", "characters"],
  },
  {
    id: "cobra-kai", name: "Cobra Kai", type: "show",
    plot: "Decades after the All Valley Karate Tournament, Johnny Lawrence reopens the Cobra Kai dojo to rebuild his life, reigniting his old rivalry with Daniel LaRusso and dragging a new generation of kids into it.",
    cast: ["Ralph Macchio", "William Zabka", "Xolo Maridueña"], seasons: 6, episodes: 65, year: 2018,
    platforms: ["Netflix"], genre: ["action", "comedy", "drama"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["long-runner"], love: ["characters", "humor"],
  },
  {
    id: "the-witcher", name: "The Witcher", type: "show",
    plot: "A monster hunter for hire, a powerful sorceress, and a princess with a dangerous destiny all cross paths on a war-torn continent, their intertwining fates driving toward a war none of them can avoid.",
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"], seasons: 3, episodes: 24, year: 2019,
    platforms: ["Netflix"], genre: ["fantasy", "action"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["world-building", "plot-twists"],
  },
  {
    id: "lupin", name: "Lupin", type: "show",
    plot: "Inspired by the adventures of gentleman thief Arsène Lupin, a master of disguise sets out to avenge his father's frame-up decades earlier by taking down the wealthy family responsible, one elaborate heist at a time.",
    cast: ["Omar Sy", "Ludivine Sagnier", "Clotilde Hesme"], seasons: 3, episodes: 19, year: 2021,
    platforms: ["Netflix"], genre: ["thriller", "mystery"], mood: ["cerebral-mystery", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "elite", name: "Elite", type: "show",
    plot: "Three working-class scholarship students enroll at Spain's most exclusive private school, and their arrival sets off a chain of affairs, blackmail, and a murder that the whole first season builds toward.",
    cast: ["Itzan Escamilla", "Miguel Bernardeau", "Danna Paola"], seasons: 8, episodes: 64, year: 2018,
    platforms: ["Netflix"], genre: ["drama", "mystery", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["plot-twists", "characters"],
  },
  {
    id: "narcos", name: "Narcos", type: "show",
    plot: "A dramatized account of the rise and fall of Pablo Escobar's Medellín cartel, and the DEA agents dedicated to bringing him down at any cost.",
    cast: ["Wagner Moura", "Boyd Holbrook", "Pedro Pascal"], seasons: 3, episodes: 30, year: 2015,
    platforms: ["Netflix"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["plot-twists", "world-building"],
  },
  {
    id: "mindhunter", name: "Mindhunter", type: "show",
    plot: "Two FBI agents in the late 1970s pioneer criminal psychology by interviewing imprisoned serial killers, developing the profiling techniques that would define modern criminal investigation.",
    cast: ["Jonathan Groff", "Holt McCallany", "Anna Torv"], seasons: 2, episodes: 19, year: 2017,
    platforms: ["Netflix"], genre: ["drama", "thriller", "mystery"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "russian-doll", name: "Russian Doll", type: "show",
    plot: "A cynical New Yorker keeps dying on the night of her 36th birthday party and waking up right back at the start of it, forced to figure out why she's stuck before the loop consumes her completely.",
    cast: ["Natasha Lyonne", "Charlie Barnett", "Greta Lee"], seasons: 2, episodes: 15, year: 2019,
    platforms: ["Netflix"], genre: ["comedy", "sci-fi", "mystery"], mood: ["dark", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "unorthodox", name: "Unorthodox", type: "show",
    plot: "A young woman flees her ultra-Orthodox Hasidic community in Brooklyn and an arranged marriage to start a new life in Berlin, with her husband and his cousin in close pursuit to bring her back.",
    cast: ["Shira Haas", "Amit Rahav", "Jeff Wilbusch"], seasons: 1, episodes: 4, year: 2020,
    platforms: ["Netflix"], genre: ["drama"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-umbrella-academy", name: "The Umbrella Academy", type: "show",
    plot: "Seven adopted siblings with wildly different superpowers, estranged for years, reunite after their father's death and have to work together to stop an apocalypse none of them can agree on how to prevent.",
    cast: ["Elliot Page", "Tom Hopper", "Emmy Raver-Lampman"], seasons: 4, episodes: 40, year: 2019,
    platforms: ["Netflix"], genre: ["sci-fi", "action", "comedy"], mood: ["cerebral-ideas", "dark"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["characters", "plot-twists"],
  },
  {
    id: "beef", name: "Beef", type: "show",
    plot: "A near-miss road rage incident between two strangers spirals into an all-consuming, increasingly destructive personal vendetta that ends up unraveling both of their entire lives.",
    cast: ["Steven Yeun", "Ali Wong", "Joseph Lee"], seasons: 1, episodes: 10, year: 2023,
    platforms: ["Netflix"], genre: ["drama", "comedy", "thriller"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "baby-reindeer", name: "Baby Reindeer", type: "show",
    plot: "A struggling comedian's small act of kindness toward a lonely woman at his bar spirals into an obsessive, terrifying stalking campaign, forcing him to confront trauma of his own he's never told anyone about.",
    cast: ["Richard Gadd", "Jessica Gunning", "Nava Mau"], seasons: 1, episodes: 7, year: 2024,
    platforms: ["Netflix"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "3-body-problem", name: "3 Body Problem", type: "show",
    plot: "A secret military project in 1960s China makes contact with an alien civilization, setting off a decades-spanning crisis for a group of scientists as humanity braces for a first contact that isn't friendly.",
    cast: ["Jovan Adepo", "Eiza González", "John Bradley"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Netflix"], genre: ["sci-fi", "drama", "mystery"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "never-have-i-ever", name: "Never Have I Ever", type: "show",
    plot: "An Indian-American high schooler navigates grief over her father's death, first crushes, and her own explosive temper, narrated with deadpan commentary by an unlikely tennis legend.",
    cast: ["Maitreyi Ramakrishnan", "Poorna Jagannathan", "Darren Barnet"], seasons: 4, episodes: 40, year: 2020,
    platforms: ["Netflix"], genre: ["comedy", "romance", "drama"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "emotional-weight"],
  },
  {
    id: "sweet-tooth", name: "Sweet Tooth", type: "show",
    plot: "In a world reshaped by a mysterious virus and the sudden appearance of human-animal hybrid children, a deer-boy raised in isolation ventures out to find his mother, guided by a gruff drifter he doesn't fully trust yet.",
    cast: ["Christian Convery", "Nonso Anozie", "Adeel Akhtar"], seasons: 3, episodes: 25, year: 2021,
    platforms: ["Netflix"], genre: ["fantasy", "drama", "action"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "shadow-and-bone", name: "Shadow and Bone", type: "show",
    plot: "An orphan mapmaker discovers she has a rare power that could unite a fractured empire and destroy the monstrous darkness splitting it in two, but every faction wants to use her power for their own ends.",
    cast: ["Jessie Mei Li", "Ben Barnes", "Freddy Carter"], seasons: 2, episodes: 16, year: 2021,
    platforms: ["Netflix"], genre: ["fantasy", "action"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "glass-onion", name: "Glass Onion: A Knives Out Mystery", type: "movie",
    plot: "Detective Benoit Blanc is invited to a tech billionaire's private Greek island for a murder-mystery weekend among his old, backstabbing friend group — until one of the fake murders turns disturbingly real.",
    cast: ["Daniel Craig", "Edward Norton", "Janelle Monáe"], runtime: 140, year: 2022,
    platforms: ["Netflix"], genre: ["mystery", "comedy"], mood: ["cerebral-mystery", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "humor"],
  },
  {
    id: "the-irishman", name: "The Irishman", type: "movie",
    plot: "An aging hitman looks back on his decades running with the Bufalino crime family and his close friendship with Teamsters leader Jimmy Hoffa, and the job that ended it.",
    cast: ["Robert De Niro", "Al Pacino", "Joe Pesci"], runtime: 209, year: 2019,
    platforms: ["Netflix"], genre: ["drama", "thriller"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "marriage-story", name: "Marriage Story", type: "movie",
    plot: "A theater director and an actress navigate a painfully amicable divorce that turns adversarial the moment lawyers get involved, watching a genuine love slowly get weaponized by the process meant to end it.",
    cast: ["Adam Driver", "Scarlett Johansson", "Laura Dern"], runtime: 137, year: 2019,
    platforms: ["Netflix"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "roma", name: "Roma", type: "movie",
    plot: "A quiet, black-and-white portrait of a year in the life of a live-in housekeeper for a middle-class family in 1970s Mexico City, as her own life and the family's slowly come apart in parallel.",
    cast: ["Yalitza Aparicio", "Marina de Tavira"], runtime: 135, year: 2018,
    platforms: ["Netflix"], genre: ["drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "the-power-of-the-dog", name: "The Power of the Dog", type: "movie",
    plot: "A domineering Montana rancher torments his brother's new wife and her sensitive teenage son, until the son's quiet observation turns out to be a far more dangerous trait than anyone expected.",
    cast: ["Benedict Cumberbatch", "Kirsten Dunst", "Kodi Smit-McPhee"], runtime: 128, year: 2021,
    platforms: ["Netflix"], genre: ["drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "dont-look-up", name: "Don't Look Up", type: "movie",
    plot: "Two low-level astronomers discover a planet-killing comet on a direct collision course with Earth, and find that getting anyone in power to actually care is a much harder problem than the math.",
    cast: ["Leonardo DiCaprio", "Jennifer Lawrence", "Meryl Streep"], runtime: 138, year: 2021,
    platforms: ["Netflix"], genre: ["comedy", "sci-fi", "drama"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "bird-box", name: "Bird Box", type: "movie",
    plot: "A mother blindfolds herself and her two children for a desperate river journey to safety, fleeing an unseen force that drives anyone who looks at it to violent suicide.",
    cast: ["Sandra Bullock", "Trevante Rhodes", "John Malkovich"], runtime: 124, year: 2018,
    platforms: ["Netflix"], genre: ["horror", "thriller", "sci-fi"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "the-adam-project", name: "The Adam Project", type: "movie",
    plot: "A time-traveling fighter pilot crash-lands in his own backyard and teams up with his twelve-year-old self to save the future and finally make peace with the father they both lost too young.",
    cast: ["Ryan Reynolds", "Walker Scobell", "Mark Ruffalo"], runtime: 106, year: 2022,
    platforms: ["Netflix"], genre: ["sci-fi", "comedy", "action"], mood: ["light", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "red-notice", name: "Red Notice", type: "movie",
    plot: "An FBI profiler chasing the world's most wanted art thief ends up handcuffed to him instead, forced into an uneasy partnership to catch an even more elusive rival thief before either of them gets played.",
    cast: ["Dwayne Johnson", "Ryan Reynolds", "Gal Gadot"], runtime: 118, year: 2021,
    platforms: ["Netflix"], genre: ["action", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "plot-twists"],
  },
  {
    id: "extraction", name: "Extraction", type: "movie",
    plot: "A black-market mercenary is hired to rescue the kidnapped son of an imprisoned crime lord from a rival gang in Dhaka, and the extraction goes so wrong it turns into an all-out war across the city.",
    cast: ["Chris Hemsworth", "Rudhraksh Jaiswal", "Randeep Hooda"], runtime: 117, year: 2020,
    platforms: ["Netflix"], genre: ["action"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-gray-man", name: "The Gray Man", type: "movie",
    plot: "A CIA black-ops mercenary uncovers dark secrets about the agency mid-mission, and immediately becomes the target of an international manhunt led by a sociopathic freelance operative hired to eliminate him.",
    cast: ["Ryan Gosling", "Chris Evans", "Ana de Armas"], runtime: 129, year: 2022,
    platforms: ["Netflix"], genre: ["action", "thriller"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "enola-holmes", name: "Enola Holmes", type: "movie",
    plot: "Sherlock Holmes's much younger, far more overlooked sister sets off to find her suddenly missing mother, matching wits with her famous brothers along the way and proving she's every bit the detective they are.",
    cast: ["Millie Bobby Brown", "Henry Cavill", "Sam Claflin"], runtime: 123, year: 2020,
    platforms: ["Netflix"], genre: ["mystery", "action", "comedy"], mood: ["light", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["historical"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "to-all-the-boys-ive-loved-before", name: "To All the Boys I've Loved Before", type: "movie",
    plot: "A teenager's private stash of five secret love letters, written to every boy she's ever had a crush on, gets mysteriously mailed out to all of them at once, blowing up her carefully guarded love life overnight.",
    cast: ["Lana Condor", "Noah Centineo", "Janel Parrish"], runtime: 100, year: 2018,
    platforms: ["Netflix"], genre: ["romance", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "klaus", name: "Klaus", type: "movie",
    plot: "A spoiled postal academy washout is banished to a miserable frozen town with zero mail, and stumbles into an unlikely friendship with a reclusive toymaker that accidentally invents the entire Santa Claus legend.",
    cast: ["Jason Schwartzman", "J.K. Simmons", "Rashida Jones"], runtime: 97, year: 2019,
    platforms: ["Netflix"], genre: ["comedy", "fantasy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "the-mitchells-vs-the-machines", name: "The Mitchells vs. the Machines", type: "movie",
    plot: "A quirky, chaotic family's cross-country road trip to drop their daughter off at film school turns out to be humanity's last hope when a robot uprising suddenly kicks off around them.",
    cast: ["Abbi Jacobson", "Danny McBride", "Maya Rudolph"], runtime: 113, year: 2021,
    platforms: ["Netflix"], genre: ["comedy", "sci-fi", "action"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "nimona", name: "Nimona", type: "movie",
    plot: "A disgraced knight framed for a murder he didn't commit teams up with a shapeshifting teenage outcast to clear his name, even though everyone in the kingdom is convinced she's a monster.",
    cast: ["Chloë Grace Moretz", "Riz Ahmed", "Eugene Lee Yang"], runtime: 101, year: 2023,
    platforms: ["Netflix"], genre: ["fantasy", "action", "comedy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
];
