import type { RawTitle } from "../shape";

/** Batch 009 — more Crunchyroll anime (still the smallest type category), plus the Ghibli/GKIDS
 * catalog correctly tagged to HBO Max, its actual US streaming home (not Crunchyroll). */
export const RAW: RawTitle[] = [
  {
    id: "bungo-stray-dogs", name: "Bungo Stray Dogs", type: "anime",
    plot: "A boy expelled from his orphanage for having a mysterious ability is rescued by a detective agency of literary-named superpowered operatives, and joins their fight against an equally strange mafia.",
    cast: ["Yuto Uemura", "Mamoru Miyano"], seasons: 5, episodes: 62, year: 2016,
    platforms: ["Crunchyroll"], genre: ["action", "mystery", "fantasy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["characters", "plot-twists"],
  },
  {
    id: "noragami", name: "Noragami", type: "anime",
    plot: "A minor, penniless god with no shrine to his name takes odd jobs for five yen apiece, dreaming of the day he'll finally be famous enough to have worshippers of his own.",
    cast: ["Yūki Kaji", "Maaya Uchida"], seasons: 2, episodes: 25, year: 2014,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "the-seven-deadly-sins", name: "The Seven Deadly Sins", type: "anime",
    plot: "A princess sets out to find a disbanded order of legendary knights, each named for a deadly sin, to help her reclaim her kingdom from the corrupt Holy Knights who overthrew it.",
    cast: ["Yūki Kaji", "Sora Amamiya"], seasons: 4, episodes: 100, year: 2014,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "comedy"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "dr-stone", name: "Dr. Stone", type: "anime",
    plot: "Every human on Earth is suddenly turned to stone, and thousands of years later a science-obsessed teenager wakes up first and sets out to rebuild civilization from absolute scratch, one invention at a time.",
    cast: ["Gen Sato", "Aoi Yūki"], seasons: 4, episodes: 61, year: 2019,
    platforms: ["Crunchyroll"], genre: ["sci-fi", "comedy", "action"], mood: ["cerebral-ideas", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "characters"],
  },
  {
    id: "the-devil-is-a-part-timer", name: "The Devil Is a Part-Timer!", type: "anime",
    plot: "A demon lord defeated and stranded in modern Tokyo has to take a job at a fast-food joint to survive, and slowly finds he's a lot better at making minimum wage than conquering worlds.",
    cast: ["Ryōta Ōsaka", "Yōko Hikasa"], seasons: 2, episodes: 23, year: 2013,
    platforms: ["Crunchyroll"], genre: ["comedy", "fantasy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "food-wars", name: "Food Wars! Shokugeki no Soma", type: "anime",
    plot: "A talented young cook enrolls at an elite culinary academy with a brutal expulsion rate, and has to win outrageous, high-stakes cook-off duels just to stay enrolled.",
    cast: ["Yoshitsugu Matsuoka", "Risa Taneda"], seasons: 5, episodes: 96, year: 2015,
    platforms: ["Crunchyroll"], genre: ["comedy", "drama"], mood: ["funny-silly", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["characters", "humor"],
  },
  {
    id: "dorohedoro", name: "Dorohedoro", type: "anime",
    plot: "In a grimy, lawless slum plagued by sorcerers who use ordinary people for magic experiments, a lizard-headed amnesiac man hunts for whichever magic user turned his head into a lizard's in the first place.",
    cast: ["Wataru Takagi", "Saori Hayami"], seasons: 1, episodes: 12, year: 2020,
    platforms: ["Crunchyroll"], genre: ["fantasy", "horror", "comedy"], mood: ["dark", "funny-silly"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "great-pretender", name: "Great Pretender", type: "anime",
    plot: "A small-time Japanese con man teams up with a mysterious, brilliant swindler for a globe-trotting string of increasingly elaborate cons targeting the world's worst criminals.",
    cast: ["Chiaki Kobayashi", "Yōko Hikasa"], seasons: 1, episodes: 23, year: 2020,
    platforms: ["Crunchyroll"], genre: ["comedy", "thriller"], mood: ["funny-witty", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "humor"],
  },
  {
    id: "beastars", name: "Beastars", type: "anime",
    plot: "At a high school where carnivores and herbivores coexist under uneasy truce, a quiet wolf's growing feelings for a small rabbit classmate collide with a murder investigation and his own predatory instincts.",
    cast: ["Chikahiro Kobayashi", "Sayaka Senbongi"], seasons: 2, episodes: 24, year: 2019,
    platforms: ["Crunchyroll"], genre: ["drama", "mystery", "romance"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "the-ancient-magus-bride", name: "The Ancient Magus' Bride", type: "anime",
    plot: "An orphaned girl with a rare magical gift is sold at auction to a nonhuman mage with a skull for a head, who names her both his apprentice and his future bride, and neither of them fully knows what that means yet.",
    cast: ["Atsumi Tanezaki", "Ryōta Takeuchi"], seasons: 2, episodes: 36, year: 2017,
    platforms: ["Crunchyroll"], genre: ["fantasy", "romance"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "log-horizon", name: "Log Horizon", type: "anime",
    plot: "Thirty thousand Japanese players are trapped inside their favorite MMO when it stops being a game, and a socially awkward strategist has to help build an actual functioning society for everyone stuck inside.",
    cast: ["Ryōhei Kimura", "Asami Seto"], seasons: 3, episodes: 50, year: 2013,
    platforms: ["Crunchyroll"], genre: ["fantasy", "sci-fi"], mood: ["cerebral-ideas", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["world-building", "characters"],
  },
  {
    id: "no-game-no-life", name: "No Game No Life", type: "anime",
    plot: "A pair of shut-in gamer siblings are summoned to a world where all conflict, even war, is settled through games, and set out to conquer all sixteen ruling species without ever losing a single match.",
    cast: ["Yoshitsugu Matsuoka", "Ai Kayano"], seasons: 1, episodes: 12, year: 2014,
    platforms: ["Crunchyroll"], genre: ["fantasy", "comedy"], mood: ["funny-silly", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "parasyte-the-maxim", name: "Parasyte -the maxim-", type: "anime",
    plot: "A parasitic alien fails to take over a teenager's brain and settles for his right hand instead, and the two of them have to learn to coexist while other, fully successful parasites start hunting humans nearby.",
    cast: ["Nobunaga Shimazaki", "Aya Hirano"], seasons: 1, episodes: 24, year: 2014,
    platforms: ["Crunchyroll"], genre: ["horror", "sci-fi", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "terror-in-resonance", name: "Terror in Resonance", type: "anime",
    plot: "Two teenage terrorists carry out a string of meticulously planned attacks on Tokyo, leaving cryptic riddles behind for the police and a traumatized detective to decipher before the next one hits.",
    cast: ["Soma Saito", "Kensho Ono"], seasons: 1, episodes: 11, year: 2014,
    platforms: ["Crunchyroll"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "golden-kamuy", name: "Golden Kamuy", type: "anime",
    plot: "A battle-hardened veteran and a young Ainu girl team up to hunt for a fortune in stolen gold hidden across the wilds of Hokkaido, chased the whole way by escaped convicts and a rogue army platoon.",
    cast: ["Yuichi Nakamura", "Ikumi Hasegawa"], seasons: 4, episodes: 37, year: 2018,
    platforms: ["Crunchyroll"], genre: ["action", "comedy", "drama"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "characters"],
  },
  {
    id: "banana-fish", name: "Banana Fish", type: "anime",
    plot: "A New York gang leader hunting down the truth behind his brother's mysterious breakdown, the phrase 'Banana Fish,' crosses paths with a visiting Japanese photographer whose life gets pulled into the danger with him.",
    cast: ["Yuma Uchida", "Kenshō Ono"], seasons: 1, episodes: 24, year: 2018,
    platforms: ["Crunchyroll"], genre: ["thriller", "drama", "action"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "plot-twists"],
  },
  {
    id: "yuri-on-ice", name: "Yuri!!! on Ice", type: "anime",
    plot: "A once-promising figure skater on the verge of quitting after a crushing defeat gets an unexpected shot at a comeback when his childhood idol shows up to coach him back to the world stage.",
    cast: ["Toshiyuki Toyonaga", "Kōki Uchiyama"], seasons: 1, episodes: 12, year: 2016,
    platforms: ["Crunchyroll"], genre: ["drama", "romance"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "kurokos-basketball", name: "Kuroko's Basketball", type: "anime",
    plot: "A nearly invisible former member of an unbeatable middle-school basketball dynasty joins a struggling high school team, using his uncanny lack of presence to set up plays no opponent sees coming.",
    cast: ["Kenshō Ono", "Yūki Kaji"], seasons: 3, episodes: 75, year: 2012,
    platforms: ["Crunchyroll"], genre: ["drama", "comedy"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["characters", "humor"],
  },
  {
    id: "the-disastrous-life-of-saiki-k", name: "The Disastrous Life of Saiki K.", type: "anime",
    plot: "An all-powerful psychic high schooler just wants a normal, quiet life, but his telepathy, telekinesis, and every other power under the sun keep dragging him into his classmates' absurd daily chaos.",
    cast: ["Yōhei Azakami", "Sōma Saitō"], seasons: 4, episodes: 120, year: 2016,
    platforms: ["Crunchyroll"], genre: ["comedy", "sci-fi"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "gintama", name: "Gintama", type: "anime",
    plot: "In an alien-occupied Edo-era Japan where swords are banned, a broke, lazy ex-samurai runs an odd-jobs shop with his oddball friends, bouncing between absurdist comedy and surprisingly heavy samurai-era drama.",
    cast: ["Tomokazu Sugita", "Daisuke Sakaguchi"], seasons: 8, episodes: 367, year: 2006,
    platforms: ["Crunchyroll"], genre: ["comedy", "action", "sci-fi"], mood: ["funny-silly", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "my-neighbor-totoro", name: "My Neighbor Totoro", type: "anime",
    plot: "Two young sisters move to the countryside with their father while their mother recovers in the hospital, and discover a gentle, giant forest spirit living in the woods behind their new house.",
    cast: ["Noriko Hidaka", "Chika Sakamoto"], runtime: 86, year: 1988,
    platforms: ["HBO Max"], genre: ["fantasy"], mood: ["feel-good", "comfort-escapist"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "kikis-delivery-service", name: "Kiki's Delivery Service", type: "anime",
    plot: "A thirteen-year-old witch leaves home for a year of independence in a new seaside town, setting up a broomstick delivery service and slowly finding her footing — and her confidence — on her own.",
    cast: ["Minami Takayama", "Rei Sakuma"], runtime: 103, year: 1989,
    platforms: ["HBO Max"], genre: ["fantasy"], mood: ["feel-good", "comfort-escapist"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "castle-in-the-sky", name: "Castle in the Sky", type: "anime",
    plot: "A boy and a girl with a mysterious glowing pendant race sky pirates and government agents to find Laputa, a legendary floating castle said to hold untold ancient power.",
    cast: ["Mayumi Tanaka", "Keiko Yokozawa"], runtime: 124, year: 1986,
    platforms: ["HBO Max"], genre: ["fantasy", "action"], mood: ["feel-good", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "nausicaa-of-the-valley-of-the-wind", name: "Nausicaä of the Valley of the Wind", type: "anime",
    plot: "A thousand years after civilization's collapse, a princess who can communicate with giant mutated insects tries to stop two warring kingdoms from finishing the job of destroying what's left of the world.",
    cast: ["Sumi Shimamoto", "Mahito Tsujimura"], runtime: 117, year: 1984,
    platforms: ["HBO Max"], genre: ["fantasy", "sci-fi"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "grave-of-the-fireflies", name: "Grave of the Fireflies", type: "anime",
    plot: "A teenage boy and his little sister struggle to survive on their own in the final months of WWII Japan after their mother is killed in a firebombing raid and their extended family turns them away.",
    cast: ["Tsutomu Tatsumi", "Ayano Shiraishi"], runtime: 89, year: 1988,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-wind-rises", name: "The Wind Rises", type: "anime",
    plot: "A fictionalized account of Jiro Horikoshi, the engineer who designed WWII Japanese fighter planes, torn between the pure joy of flight and the devastating purpose his beautiful designs were ultimately built for.",
    cast: ["Hideaki Anno", "Miori Takimoto"], runtime: 126, year: 2013,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "when-marnie-was-there", name: "When Marnie Was There", type: "anime",
    plot: "A withdrawn foster girl sent to the countryside for her health befriends a mysterious blonde girl living in an old mansion across the marsh, whose true identity turns out to be tangled up in her own family's past.",
    cast: ["Sara Takatsuki", "Kasumi Arimura"], runtime: 103, year: 2014,
    platforms: ["HBO Max"], genre: ["drama", "mystery"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["family"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "plot-twists"],
  },
  {
    id: "only-yesterday", name: "Only Yesterday", type: "anime",
    plot: "A 27-year-old office worker takes a countryside vacation and finds herself constantly drifting back into vivid memories of her tricky, awkward fifth-grade self, reconsidering the whole shape of her life so far.",
    cast: ["Miki Imai", "Toshirō Yanagiba"], runtime: 118, year: 1991,
    platforms: ["HBO Max"], genre: ["drama", "romance"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "ponyo", name: "Ponyo", type: "anime",
    plot: "A magical goldfish princess who wants to become human befriends a five-year-old boy on the coast, and her desire to stay with him starts unbalancing the delicate magic keeping the ocean in harmony with land.",
    cast: ["Yuria Nara", "Hiroki Doi"], runtime: 101, year: 2008,
    platforms: ["HBO Max"], genre: ["fantasy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "whisper-of-the-heart", name: "Whisper of the Heart", type: "anime",
    plot: "A bookish middle schooler follows the trail of a mysterious boy whose name keeps showing up in every library book she checks out, and discovers he's chasing his own creative dream just as hard as she wants to find hers.",
    cast: ["Yoko Honna", "Issei Takahashi"], runtime: 111, year: 1995,
    platforms: ["HBO Max"], genre: ["romance", "drama"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
];
