import type { RawTitle } from "../shape";

/** Batch 010 — documentaries and family/kids animation, both underrepresented so far. */
export const RAW: RawTitle[] = [
  {
    id: "my-octopus-teacher", name: "My Octopus Teacher", type: "movie",
    plot: "A burned-out filmmaker starts free-diving daily into a South African kelp forest and forms an unlikely, year-long bond with a wild octopus, who teaches him something about attention and mortality along the way.",
    cast: ["Craig Foster"], runtime: 85, year: 2020,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "the-social-dilemma", name: "The Social Dilemma", type: "movie",
    plot: "Former tech executives who helped build Facebook, Google, and Twitter's core features explain, on camera, exactly how those same features are engineered to hijack attention and manipulate behavior.",
    cast: ["Tristan Harris", "Jaron Lanier"], runtime: 94, year: 2020,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["cerebral-ideas", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "13th", name: "13th", type: "movie",
    plot: "A sweeping examination of how the 13th Amendment's loophole exempting prisoners from its ban on slavery helped build America's system of mass incarceration.",
    cast: ["Angela Davis", "Van Jones"], runtime: 100, year: 2016,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "icarus", name: "Icarus", type: "movie",
    plot: "An amateur cyclist's personal experiment with performance-enhancing drugs accidentally uncovers Russia's state-sponsored Olympic doping program, and the film turns into a real-time whistleblower thriller.",
    cast: ["Bryan Fogel", "Grigory Rodchenkov"], runtime: 121, year: 2017,
    platforms: ["Netflix"], genre: ["documentary", "thriller"], mood: ["cerebral-mystery", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "american-factory", name: "American Factory", type: "movie",
    plot: "A Chinese billionaire reopens a shuttered Ohio auto-glass plant, and the culture clash between Chinese management and American workers exposes deep tensions about labor, automation, and what a job is even for.",
    cast: ["Multiple interviewees"], runtime: 110, year: 2019,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "wild-wild-country", name: "Wild Wild Country", type: "show",
    plot: "A controversial Indian guru's followers build a utopian commune in rural Oregon in the 1980s, and the escalating conflict with suspicious locals spirals into bioterrorism, immigration fraud, and attempted murder.",
    cast: ["Ma Anand Sheela"], seasons: 1, episodes: 6, year: 2018,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["cerebral-mystery", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "chefs-table", name: "Chef's Table", type: "show",
    plot: "Each episode profiles a single world-class chef, following their philosophy, personal history, and craft in gorgeously shot detail — as much a character study as a food show.",
    cast: ["Various chefs"], seasons: 6, episodes: 30, year: 2015,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "formula-1-drive-to-survive", name: "Formula 1: Drive to Survive", type: "show",
    plot: "Unprecedented behind-the-scenes access to every Formula 1 team follows the drivers, principals, and engineers through a season of high-stakes rivalry, turning the sport's politics into must-watch drama.",
    cast: ["Lewis Hamilton", "Max Verstappen", "Daniel Ricciardo"], seasons: 6, episodes: 60, year: 2019,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["long-runner"], love: ["characters", "plot-twists"],
  },
  {
    id: "cheer", name: "Cheer", type: "show",
    plot: "A junior college cheerleading team with a legendary, brutal coach trains toward the national championship, following each athlete's personal story of injury, ambition, and what the sport costs them.",
    cast: ["Monica Aldama", "Jerry Harris"], seasons: 2, episodes: 15, year: 2020,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "emotional-weight"],
  },
  {
    id: "the-beatles-get-back", name: "The Beatles: Get Back", type: "show",
    plot: "Restored footage from the Beatles' final rehearsals and rooftop concert shows the band writing an entire album together in real time, capturing both their creative chemistry and the tension pulling them apart.",
    cast: ["John Lennon", "Paul McCartney", "George Harrison"], seasons: 1, episodes: 3, year: 2021,
    platforms: ["Disney+ Hotstar"], genre: ["documentary"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "free-solo", name: "Free Solo", type: "movie",
    plot: "Elite climber Alex Honnold prepares to free-solo climb Yosemite's 3,000-foot El Capitan wall with no ropes and zero margin for error, while the crew filming him has to reckon with what they're actually documenting.",
    cast: ["Alex Honnold"], runtime: 100, year: 2018,
    platforms: ["Disney+ Hotstar"], genre: ["documentary"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "wont-you-be-my-neighbor", name: "Won't You Be My Neighbor?", type: "movie",
    plot: "A look back at Fred Rogers, the soft-spoken Presbyterian minister who spent decades quietly, radically insisting that children's television could take kids' feelings seriously.",
    cast: ["Fred Rogers"], runtime: 94, year: 2018,
    platforms: ["HBO Max"], genre: ["documentary"], mood: ["feel-good", "comfort-background"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-last-dance", name: "The Last Dance", type: "show",
    plot: "Built around never-before-seen footage from the Chicago Bulls' final championship season, this traces Michael Jordan's entire career and the dynasty around him, one legendary rivalry at a time.",
    cast: ["Michael Jordan", "Scottie Pippen", "Phil Jackson"], seasons: 1, episodes: 10, year: 2020,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "the-sea-beast", name: "The Sea Beast", type: "movie",
    plot: "A legendary monster hunter takes on a young stowaway determined to prove herself, and the two of them start to question everything they were taught about the sea beasts they've spent their lives killing.",
    cast: ["Karl Urban", "Zaris-Angel Hator", "Jared Harris"], runtime: 115, year: 2022,
    platforms: ["Netflix"], genre: ["fantasy", "action"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "wish-dragon", name: "Wish Dragon", type: "movie",
    plot: "A working-class college student stumbles onto a magic teapot containing a wisecracking dragon who grants him three wishes, and uses it to try to reconnect with the wealthy childhood best friend he lost touch with.",
    cast: ["Jimmy Wong", "John Cho", "Constance Wu"], runtime: 98, year: 2021,
    platforms: ["Netflix"], genre: ["fantasy", "comedy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "home-2015", name: "Home", type: "movie",
    plot: "A clumsy alien on the run from his own kind hides out with a resourceful teenage girl searching for her mother, and the two mismatched fugitives end up saving the whole planet together.",
    cast: ["Jim Parsons", "Rihanna", "Steve Martin"], runtime: 94, year: 2015,
    platforms: ["Netflix"], genre: ["comedy", "sci-fi"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "my-little-pony-friendship-is-magic", name: "My Little Pony: Friendship Is Magic", type: "show",
    plot: "A studious young unicorn sent to make friends in a small pony town discovers that friendship itself is a kind of magic powerful enough to save the world from ancient evils.",
    cast: ["Tara Strong", "Ashleigh Ball", "Andrea Libman"], seasons: 9, episodes: 221, year: 2010,
    platforms: ["Netflix"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "trollhunters", name: "Trollhunters", type: "show",
    plot: "An ordinary teenager finds a magic amulet that makes him the chosen Trollhunter, sworn to protect his suburban town from monstrous trolls hiding in plain sight below its streets.",
    cast: ["Anton Yelchin", "Kelsey Grammer", "Charlie Saxton"], seasons: 3, episodes: 52, year: 2016,
    platforms: ["Netflix"], genre: ["fantasy", "action"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["world-building", "characters"],
  },
  {
    id: "carmen-sandiego", name: "Carmen Sandiego", type: "show",
    plot: "A master thief who steals only from villains uses her globe-trotting skills and encyclopedic knowledge of world geography and culture to stay one step ahead of the shadowy organization that trained her.",
    cast: ["Gina Rodriguez", "Finn Wolfhard"], seasons: 4, episodes: 40, year: 2019,
    platforms: ["Netflix"], genre: ["mystery", "action"], mood: ["light", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "the-dragon-prince", name: "The Dragon Prince", type: "show",
    plot: "A human prince and an elf assassin sent to kill him instead team up to return a stolen dragon egg to its mother, in a desperate bid to end a centuries-old war between their two peoples.",
    cast: ["Jack DeSena", "Paula Burrows", "Sasha Rojen"], seasons: 7, episodes: 63, year: 2018,
    platforms: ["Netflix"], genre: ["fantasy", "action"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["world-building", "characters"],
  },
  {
    id: "hilda", name: "Hilda", type: "show",
    plot: "A fearless blue-haired girl moves from the wilderness into a big city full of hidden magical creatures, making friends with trolls, elves, and giants that most people walk right past without noticing.",
    cast: ["Bella Ramsey"], seasons: 3, episodes: 39, year: 2018,
    platforms: ["Netflix"], genre: ["fantasy", "comedy"], mood: ["feel-good", "comfort-escapist"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "gravity-falls", name: "Gravity Falls", type: "show",
    plot: "Twin siblings sent to stay with their great-uncle in a small Oregon town full of gnomes, ghosts, and government conspiracies spend the summer investigating every strange mystery he warns them to leave alone.",
    cast: ["Jason Ritter", "Kristen Schaal", "Alex Hirsch"], seasons: 2, episodes: 40, year: 2012,
    platforms: ["Disney+ Hotstar"], genre: ["mystery", "comedy", "fantasy"], mood: ["funny-witty", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["plot-twists", "humor"],
  },
  {
    id: "phineas-and-ferb", name: "Phineas and Ferb", type: "show",
    plot: "Two stepbrothers turn every single day of summer vacation into an enormous, elaborate invention — a roller coaster, a time machine — while their pet platypus secretly moonlights as a spy fighting an inept villain.",
    cast: ["Vincent Martella", "Thomas Sangster", "Ashley Tisdale"], seasons: 4, episodes: 222, year: 2007,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "sci-fi"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "ducktales-2017", name: "DuckTales", type: "show",
    plot: "Scrooge McDuck's three mischievous grand-nephews move into his mansion and drag the once-adventurous tycoon back out into the world for globe-trotting treasure hunts he'd sworn off for good.",
    cast: ["David Tennant", "Danny Pudi", "Ben Schwartz"], seasons: 3, episodes: 69, year: 2017,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "action"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "big-city-greens", name: "Big City Greens", type: "show",
    plot: "A country kid who just moved to the big city with his loud, close-knit farm family refuses to let go of his rural habits, turning every ordinary city block into an opportunity for chaos.",
    cast: ["Chris Houghton", "Bob Joles", "Marieve Herington"], seasons: 5, episodes: 100, year: 2018,
    platforms: ["Disney+ Hotstar"], genre: ["comedy"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "the-owl-house", name: "The Owl House", type: "show",
    plot: "A misfit teenager accidentally stumbles through a portal into the Demon Realm and apprentices herself to a rebellious witch, choosing a world of magic and monsters over the human life waiting back home.",
    cast: ["Sarah-Nicole Robles", "Wendie Malick", "Alex Hirsch"], seasons: 3, episodes: 44, year: 2020,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "characters"],
  },
  {
    id: "amphibia", name: "Amphibia", type: "show",
    plot: "A phone-obsessed teenager gets magically transported to a world of talking frogs, and slowly grows out of her sheltered old habits while helping her adopted frog family survive threats to their pond town.",
    cast: ["Brenda Song", "Justin Felbinger", "Bill Farmer"], seasons: 3, episodes: 61, year: 2019,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy", "action"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "emotional-weight"],
  },
];
