import type { RawTitle } from "../shape";

/** Batch 011 — more Prime Video, Apple TV, and HBO Max volume across mixed genres. */
export const RAW: RawTitle[] = [
  {
    id: "the-idea-of-you", name: "The Idea of You", type: "movie",
    plot: "A 40-year-old single mom accompanying her daughter to a music festival has an unexpected connection with the 24-year-old lead singer of the world's biggest boy band, and has to decide if she's willing to risk the tabloid fallout.",
    cast: ["Anne Hathaway", "Nicholas Galitzine"], runtime: 115, year: 2024,
    platforms: ["Prime Video"], genre: ["romance", "drama"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "red-white-and-royal-blue", name: "Red, White & Royal Blue", type: "movie",
    plot: "The son of the US President and a British prince have a very public rivalry that turns into a very secret romance, one that could blow up both of their families' political careers if it ever gets out.",
    cast: ["Taylor Zakhar Perez", "Nicholas Galitzine", "Uma Thurman"], runtime: 118, year: 2023,
    platforms: ["Prime Video"], genre: ["romance", "comedy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "the-wilds", name: "The Wilds", type: "show",
    plot: "A group of teenage girls survives a plane crash and washes up on a deserted island, unaware the whole ordeal is secretly being engineered and observed as part of a hidden social experiment.",
    cast: ["Sarah Pidgeon", "Shannon Berry", "Sophia Ali"], seasons: 2, episodes: 18, year: 2020,
    platforms: ["Prime Video"], genre: ["drama", "mystery", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "panic", name: "Panic", type: "show",
    plot: "Every summer, graduating seniors in a small Texas town compete in a secret, dangerous game of escalating dares for a life-changing cash prize, and this year's contest starts pulling old grudges to the surface.",
    cast: ["Olivia Welch", "Mike Faist", "Jessica Sula"], seasons: 1, episodes: 10, year: 2021,
    platforms: ["Prime Video"], genre: ["drama", "thriller"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "harlem", name: "Harlem", type: "show",
    plot: "Four best friends navigate careers, dating, and their own ambitions in modern Harlem, leaning on each other through everything from professional setbacks to the return of a long-lost ex.",
    cast: ["Meagan Good", "Grace Byers", "Jerrie Johnson"], seasons: 2, episodes: 18, year: 2021,
    platforms: ["Prime Video"], genre: ["comedy", "romance", "drama"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "cross", name: "Cross", type: "show",
    plot: "A brilliant DC homicide detective and forensic psychologist hunts a serial killer while investigating his own wife's unsolved murder, refusing to let either case go cold.",
    cast: ["Aldis Hodge", "Isaiah Mustafa", "Ryan Eggold"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Prime Video"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-boys-presents-diabolical", name: "The Boys Presents: Diabolical", type: "show",
    plot: "An animated anthology set in the same universe as The Boys, each short bringing a different director and animation style to its own twisted, ultra-violent superhero satire.",
    cast: ["Awkwafina", "Andrew Rannells"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Prime Video"], genre: ["comedy", "horror", "action"], mood: ["dark", "funny-silly"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "world-building"],
  },
  {
    id: "acapulco", name: "Acapulco", type: "show",
    plot: "An older man narrates his own past to his skeptical nephew, recalling how a summer as a young towel boy at Acapulco's most glamorous resort in the 1980s changed the entire course of his life.",
    cast: ["Eugenio Derbez", "Enrique Arrizon", "Fernando Carsa"], seasons: 3, episodes: 30, year: 2021,
    platforms: ["Apple TV"], genre: ["comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "emotional-weight"],
  },
  {
    id: "the-big-door-prize", name: "The Big Door Prize", type: "show",
    plot: "A mysterious machine shows up in a small-town general store, promising to reveal anyone's true life potential for a couple of quarters — and the whole town starts obsessively rethinking their choices because of it.",
    cast: ["Chris O'Dowd", "Gabrielle Dennis", "Ally Maki"], seasons: 2, episodes: 20, year: 2023,
    platforms: ["Apple TV"], genre: ["comedy", "drama", "mystery"], mood: ["cerebral-ideas", "funny-witty"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "trying", name: "Trying", type: "show",
    plot: "A couple who can't conceive on their own decides to adopt, and the show follows every awkward, funny, heartbreaking step of the process as they try to prove to a skeptical system they'll be good parents.",
    cast: ["Rafe Spall", "Esther Smith"], seasons: 4, episodes: 24, year: 2020,
    platforms: ["Apple TV"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "humor"],
  },
  {
    id: "central-park", name: "Central Park", type: "show",
    plot: "A family of Central Park caretakers breaks into song to fend off a hotel heiress determined to bulldoze the park into private condos, narrated by a busker who's somehow always exactly where the story needs him.",
    cast: ["Josh Gad", "Kristen Bell", "Leslie Odom Jr."], seasons: 3, episodes: 39, year: 2020,
    platforms: ["Apple TV"], genre: ["comedy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "servant", name: "Servant", type: "show",
    plot: "A Philadelphia couple hires a mysterious young nanny to care for a lifelike doll they've been using as reborn-doll therapy after a tragedy — and then the doll seems to actually turn into a real baby.",
    cast: ["Lauren Ambrose", "Toby Kebbell", "Nell Tiger Free"], seasons: 4, episodes: 40, year: 2019,
    platforms: ["Apple TV"], genre: ["horror", "mystery", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "home-before-dark", name: "Home Before Dark", type: "show",
    plot: "A nine-year-old aspiring investigative journalist moves to her father's hometown and starts digging into an old cold case everyone there would rather forget, following the story wherever the adults won't.",
    cast: ["Brooklynn Prince", "Jim Sturgess", "Abby Miller"], seasons: 2, episodes: 20, year: 2020,
    platforms: ["Apple TV"], genre: ["mystery", "drama"], mood: ["cerebral-mystery", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-flight-attendant", name: "The Flight Attendant", type: "show",
    plot: "A hard-partying flight attendant wakes up in a stranger's hotel room next to his dead body with no memory of what happened, and has to solve her own possible crime before the police get to her first.",
    cast: ["Kaley Cuoco", "Zosia Mamet", "Michiel Huisman"], seasons: 2, episodes: 16, year: 2020,
    platforms: ["HBO Max"], genre: ["thriller", "comedy", "mystery"], mood: ["cerebral-mystery", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "humor"],
  },
  {
    id: "station-eleven", name: "Station Eleven", type: "show",
    plot: "Twenty years after a flu pandemic collapses civilization, a traveling troupe of actors and musicians performs Shakespeare for scattered survivor settlements, and their paths keep crossing with a man from the world before.",
    cast: ["Mackenzie Davis", "Himesh Patel", "Matilda Lawler"], seasons: 1, episodes: 10, year: 2021,
    platforms: ["HBO Max"], genre: ["drama", "sci-fi"], mood: ["cerebral-ideas", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "raised-by-wolves", name: "Raised by Wolves", type: "show",
    plot: "Two androids are sent to a distant planet to raise human children in peace after Earth destroys itself in a religious war, but their carefully engineered atheist colony starts fraying the moment believers arrive.",
    cast: ["Amanda Collin", "Abubakar Salim", "Winta McGrath"], seasons: 2, episodes: 18, year: 2020,
    platforms: ["HBO Max"], genre: ["sci-fi", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "the-righteous-gemstones", name: "The Righteous Gemstones", type: "show",
    plot: "A wildly dysfunctional family of televangelists runs a sprawling megachurch empire, all of them far more interested in money, power, and petty sibling rivalries than anything resembling actual faith.",
    cast: ["Danny McBride", "John Goodman", "Edi Patterson"], seasons: 4, episodes: 39, year: 2019,
    platforms: ["HBO Max"], genre: ["comedy", "drama"], mood: ["funny-witty", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "los-espookys", name: "Los Espookys", type: "show",
    plot: "A group of Spanish-speaking friends turns their shared love of horror movies into a business, staging elaborate fake supernatural scares for paying clients across an unnamed Latin American country.",
    cast: ["Bernardo Velasco", "Cassandra Ciangherotti", "Julio Torres"], seasons: 2, episodes: 12, year: 2019,
    platforms: ["HBO Max"], language: ["Spanish"], industry: ["Latin American Cinema"],
    genre: ["comedy", "horror"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "our-flag-means-death", name: "Our Flag Means Death", type: "show",
    plot: "A wealthy aristocrat abandons his comfortable life to become a pirate captain, and his hopelessly incompetent crew stands zero chance until he crosses paths with the infamous, weary Blackbeard.",
    cast: ["Rhys Darby", "Taika Waititi", "Rory Kinnear"], seasons: 2, episodes: 18, year: 2022,
    platforms: ["HBO Max"], genre: ["comedy", "romance", "action"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "perry-mason-2020", name: "Perry Mason", type: "show",
    plot: "Years before he became LA's sharpest defense attorney, a down-on-his-luck private investigator in Depression-era Los Angeles takes on a gruesome kidnapping case that reshapes the rest of his career.",
    cast: ["Matthew Rhys", "Juliet Rylance", "Chris Chalk"], seasons: 2, episodes: 16, year: 2020,
    platforms: ["HBO Max"], genre: ["mystery", "drama", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "julia-hbo", name: "Julia", type: "show",
    plot: "Julia Child fights her way onto public television in the 1960s with a cooking show nobody thought anyone would watch, quietly revolutionizing how an entire country thought about food and TV along the way.",
    cast: ["Sarah Lancashire", "David Hyde Pierce", "Bebe Neuwirth"], seasons: 2, episodes: 16, year: 2022,
    platforms: ["HBO Max"], genre: ["comedy", "drama"], mood: ["feel-good", "funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "emotional-weight"],
  },
];
