import type { RawTitle } from "../shape";

/** Batch 012 — movie-heavy catch-up across all platforms (shows have been outpacing movies). */
export const RAW: RawTitle[] = [
  {
    id: "tetris", name: "Tetris", type: "movie",
    plot: "A Dutch video game salesman risks everything trying to license Tetris out of the Soviet Union in 1988, racing shady rival bidders and Soviet bureaucracy alike before the deal falls apart.",
    cast: ["Taron Egerton", "Nikita Efremov", "Toby Jones"], runtime: 118, year: 2023,
    platforms: ["Apple TV"], genre: ["drama", "thriller"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-beanie-bubble", name: "The Beanie Bubble", type: "movie",
    plot: "Told from the perspective of the women behind the scenes, this traces the absurd 1990s rise of Beanie Babies from a garage operation into a full-blown speculative mania.",
    cast: ["Zach Galifianakis", "Elizabeth Banks", "Sarah Snook"], runtime: 111, year: 2023,
    platforms: ["Apple TV"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "flora-and-son", name: "Flora and Son", type: "movie",
    plot: "A struggling single mother in Dublin fishes a guitar out of a dumpster for her troubled teenage son, and ends up taking online lessons herself from an easygoing LA musician who slowly becomes something more.",
    cast: ["Eve Hewson", "Joseph Gordon-Levitt", "Orén Kinlan"], runtime: 97, year: 2023,
    platforms: ["Apple TV"], genre: ["romance", "comedy", "drama"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "emancipation", name: "Emancipation", type: "movie",
    plot: "An enslaved man escapes a brutal Louisiana plantation and treks through hostile swampland pursued by slave catchers, on a desperate bid to reach Union lines and freedom.",
    cast: ["Will Smith", "Ben Foster"], runtime: 132, year: 2022,
    platforms: ["Apple TV"], genre: ["drama", "action"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-family-plan", name: "The Family Plan", type: "movie",
    plot: "A mild-mannered suburban dad's secret past as a government assassin catches up with him, forcing him to load his oblivious family into the minivan for a cross-country road trip that's actually an escape from hitmen.",
    cast: ["Mark Wahlberg", "Michelle Monaghan", "Zoe Colletti"], runtime: 116, year: 2023,
    platforms: ["Apple TV"], genre: ["action", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "fingernails", name: "Fingernails", type: "movie",
    plot: "In a world where a scientific test can supposedly confirm whether two people are truly in love, a woman questioning her own relationship takes a job at the institute that administers it.",
    cast: ["Jessie Buckley", "Riz Ahmed", "Jeremy Allen White"], runtime: 114, year: 2023,
    platforms: ["Apple TV"], genre: ["romance", "sci-fi", "drama"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "american-fiction", name: "American Fiction", type: "movie",
    plot: "A frustrated novelist tired of the publishing industry's appetite for stereotypical Black stories writes a satirical parody of exactly that under a fake identity, and watches in horror as it becomes his biggest hit ever.",
    cast: ["Jeffrey Wright", "Tracee Ellis Ross", "Sterling K. Brown"], runtime: 117, year: 2023,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["funny-witty", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "challengers", name: "Challengers", type: "movie",
    plot: "A tennis prodigy turned coach engineers a match between her husband and her ex-boyfriend-turned-rival, and their whole tangled history plays out point by point across one tense low-level tournament.",
    cast: ["Zendaya", "Josh O'Connor", "Mike Faist"], runtime: 131, year: 2024,
    platforms: ["Prime Video"], genre: ["drama", "romance"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "i-want-you-back", name: "I Want You Back", type: "movie",
    plot: "Two strangers who were both just dumped in the same week team up on an increasingly ridiculous scheme to sabotage their exes' new relationships and win them back.",
    cast: ["Charlie Day", "Jenny Slate"], runtime: 114, year: 2022,
    platforms: ["Prime Video"], genre: ["romance", "comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "hocus-pocus-2", name: "Hocus Pocus 2", type: "movie",
    plot: "Three teenage girls accidentally resurrect the Sanderson sisters on Halloween night in modern-day Salem, and have to stop the witches' new revenge plot before the whole town pays for it.",
    cast: ["Bette Midler", "Sarah Jessica Parker", "Kathy Najimy"], runtime: 103, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["funny-silly", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "the-marvels", name: "The Marvels", type: "movie",
    plot: "Captain Marvel's powers get tangled up with a Jersey City teen superfan and her estranged niece, and whenever any of the three uses her powers, they all instantly swap places with each other.",
    cast: ["Brie Larson", "Teyonah Parris", "Iman Vellani"], runtime: 105, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "ant-man-and-the-wasp-quantumania", name: "Ant-Man and the Wasp: Quantumania", type: "movie",
    plot: "Scott Lang and his family are accidentally pulled into the Quantum Realm, where they run straight into the powerful multiversal conqueror Kang for the first time.",
    cast: ["Paul Rudd", "Evangeline Lilly", "Jonathan Majors"], runtime: 125, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi", "comedy"], mood: ["light", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "humor"],
  },
  {
    id: "indiana-jones-and-the-dial-of-destiny", name: "Indiana Jones and the Dial of Destiny", type: "movie",
    plot: "An aging Indiana Jones is pulled into one last chase for a legendary time-bending artifact, racing a former Nazi scientist who wants to use it to rewrite the outcome of WWII.",
    cast: ["Harrison Ford", "Phoebe Waller-Bridge", "Mads Mikkelsen"], runtime: 154, year: 2023,
    platforms: ["Disney+ Hotstar"], genre: ["action", "mystery"], mood: ["intense", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "national-treasure", name: "National Treasure", type: "movie",
    plot: "A historian and treasure hunter has to steal the Declaration of Independence before rival treasure hunters do, convinced it holds a map to a legendary fortune hidden by America's Founding Fathers.",
    cast: ["Nicolas Cage", "Diane Kruger", "Justin Bartha"], runtime: 131, year: 2004,
    platforms: ["Disney+ Hotstar"], genre: ["action", "mystery"], mood: ["light", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "pirates-of-the-caribbean-curse-of-the-black-pearl", name: "Pirates of the Caribbean: The Curse of the Black Pearl", type: "movie",
    plot: "A blacksmith teams up with an eccentric pirate captain to rescue the kidnapped governor's daughter from a crew of cursed undead pirates sailing under the command of his own mutinous first mate.",
    cast: ["Johnny Depp", "Orlando Bloom", "Keira Knightley"], runtime: 143, year: 2003,
    platforms: ["Disney+ Hotstar"], genre: ["action", "fantasy", "comedy"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "the-princess-diaries", name: "The Princess Diaries", type: "movie",
    plot: "An awkward San Francisco teenager learns she's actually the heir to a small European kingdom, and her estranged royal grandmother has exactly one summer to turn her into a princess.",
    cast: ["Anne Hathaway", "Julie Andrews", "Héctor Elizondo"], runtime: 115, year: 2001,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "romance"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "high-school-musical", name: "High School Musical", type: "movie",
    plot: "A basketball star and a shy academic decathlete both audition for their high school's winter musical on a dare, throwing their entire cliquish social order into chaos.",
    cast: ["Zac Efron", "Vanessa Hudgens", "Ashley Tisdale"], runtime: 98, year: 2006,
    platforms: ["Disney+ Hotstar"], genre: ["romance", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "remember-the-titans", name: "Remember the Titans", type: "movie",
    plot: "A newly integrated Virginia high school's football team, and the Black head coach hired over the white incumbent, have to find a way to become a real team just as their town is coming apart over the change.",
    cast: ["Denzel Washington", "Will Patton", "Ryan Hurst"], runtime: 113, year: 2000,
    platforms: ["Disney+ Hotstar"], genre: ["drama"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "aquaman", name: "Aquaman", type: "movie",
    plot: "The half-human, half-Atlantean son of a lighthouse keeper has to embrace his royal birthright and stop his power-hungry half-brother from uniting the seven seas into a war against the surface world.",
    cast: ["Jason Momoa", "Amber Heard", "Willem Dafoe"], runtime: 143, year: 2018,
    platforms: ["HBO Max"], genre: ["action", "fantasy"], mood: ["light", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "joker", name: "Joker", type: "movie",
    plot: "A failed, mentally ill stand-up comedian in a decaying Gotham City is pushed past every breaking point by a city that has nothing but contempt for him, and slowly transforms into the Joker.",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"], runtime: 122, year: 2019,
    platforms: ["HBO Max"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "it-2017", name: "It", type: "movie",
    plot: "A group of outcast kids in small-town Maine band together to fight a shape-shifting entity that's been preying on the town's children for centuries, most often disguised as a sinister clown.",
    cast: ["Bill Skarsgård", "Jaeden Martell", "Sophia Lillis"], runtime: 135, year: 2017,
    platforms: ["HBO Max"], genre: ["horror"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "harry-potter-and-the-sorcerers-stone", name: "Harry Potter and the Sorcerer's Stone", type: "movie",
    plot: "An eleven-year-old orphan discovers on his birthday that he's actually a wizard, and is whisked off to a magical boarding school where he starts uncovering the truth about his parents' deaths.",
    cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"], runtime: 152, year: 2001,
    platforms: ["HBO Max"], genre: ["fantasy", "action"], mood: ["feel-good", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "the-matrix", name: "The Matrix", type: "movie",
    plot: "A restless computer programmer is recruited by a band of rebels who reveal that the world he knows is a simulated reality, and that he might be humanity's last hope against the machines running it.",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"], runtime: 136, year: 1999,
    platforms: ["HBO Max"], genre: ["sci-fi", "action"], mood: ["cerebral-ideas", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "oceans-eleven", name: "Ocean's Eleven", type: "movie",
    plot: "A recently paroled con artist assembles a crack team of ten specialists to pull off the biggest casino heist in Vegas history, robbing three casinos simultaneously on fight night.",
    cast: ["George Clooney", "Brad Pitt", "Julia Roberts"], runtime: 116, year: 2001,
    platforms: ["HBO Max"], genre: ["thriller", "comedy"], mood: ["funny-witty", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "casablanca", name: "Casablanca", type: "movie",
    plot: "A cynical American expat running a nightclub in Vichy-controlled Casablanca has to choose between his own safety and helping his lost love and her resistance-leader husband escape the Nazis.",
    cast: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid"], runtime: 102, year: 1942,
    platforms: ["HBO Max"], genre: ["drama", "romance"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["family"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-half-of-it", name: "The Half of It", type: "movie",
    plot: "A shy, closeted high schooler is paid to ghostwrite love letters for a well-meaning jock trying to woo the girl she's secretly in love with herself.",
    cast: ["Leah Lewis", "Daniel Diemer", "Alexxis Lemire"], runtime: 104, year: 2020,
    platforms: ["Netflix"], genre: ["romance", "comedy", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "always-be-my-maybe", name: "Always Be My Maybe", type: "movie",
    plot: "Childhood best friends who haven't spoken in fifteen years reconnect when one of them, now a celebrity chef, moves back to San Francisco — and old feelings resurface right alongside old grudges.",
    cast: ["Ali Wong", "Randall Park", "Keanu Reeves"], runtime: 102, year: 2019,
    platforms: ["Netflix"], genre: ["romance", "comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "set-it-up", name: "Set It Up", type: "movie",
    plot: "Two overworked assistants scheme to set their impossible bosses up on a relationship, hoping it'll finally free up some evenings for themselves — and end up falling for each other in the process.",
    cast: ["Zoey Deutch", "Glen Powell", "Lucy Liu"], runtime: 105, year: 2018,
    platforms: ["Netflix"], genre: ["romance", "comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "purple-hearts", name: "Purple Hearts", type: "movie",
    plot: "A broke aspiring singer and a Marine about to deploy enter a marriage of convenience for his military benefits, and the arrangement gets a lot more complicated once real feelings show up.",
    cast: ["Sofia Carson", "Nicholas Galitzine"], runtime: 122, year: 2022,
    platforms: ["Netflix"], genre: ["romance", "drama"], mood: ["feel-good", "intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-platform", name: "The Platform", type: "movie",
    plot: "Prisoners in a vertical tower are fed by a platform of food that descends one floor at a time, and the ones on top gorge themselves while the ones below starve — a system one new inmate refuses to accept.",
    cast: ["Iván Massagué", "Zorion Eguileor", "Antonia San Juan"], runtime: 94, year: 2019,
    platforms: ["Netflix"], language: ["Spanish"], industry: ["European Cinema"],
    genre: ["horror", "sci-fi", "thriller"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
];
