import type { RawTitle } from "../shape";

/** Batch 013 — international hits: Korean/Japanese titles on Netflix, and Indian originals on
 * Prime Video / Disney+ Hotstar (a real gap given Hotstar's presence in the platform list). */
export const RAW: RawTitle[] = [
  {
    id: "kingdom", name: "Kingdom", type: "show",
    plot: "In medieval Korea, a crown prince investigates a mysterious plague turning the dead into flesh-eating monsters, uncovering a conspiracy inside the royal court that's covering up the outbreak's true cause.",
    cast: ["Ju Ji-hoon", "Bae Doona", "Ryu Seung-ryong"], seasons: 2, episodes: 12, year: 2019,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["horror", "action", "mystery"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "all-of-us-are-dead", name: "All of Us Are Dead", type: "show",
    plot: "A zombie outbreak traps a group of high schoolers inside their own school, and their only hope of survival means crossing the very people and cliques who used to make school hell for them anyway.",
    cast: ["Park Ji-hu", "Yoon Chan-young", "Cho Yi-hyun"], seasons: 1, episodes: 12, year: 2022,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["horror", "action", "drama"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "alice-in-borderland", name: "Alice in Borderland", type: "show",
    plot: "Three friends are mysteriously transported to an empty, alternate Tokyo where survival depends on clearing lethal games against the clock, each one testing them in a different, more brutal way.",
    cast: ["Kento Yamazaki", "Tao Tsuchiya", "Nijirô Murakami"], seasons: 3, episodes: 20, year: 2020,
    platforms: ["Netflix"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["thriller", "sci-fi", "action"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "the-glory", name: "The Glory", type: "show",
    plot: "A woman devastated by brutal high school bullying spends years meticulously planning her revenge, engineering her way back into her tormentors' lives to make them lose everything, one calculated move at a time.",
    cast: ["Song Hye-kyo", "Lee Do-hyun", "Lim Ji-yeon"], seasons: 1, episodes: 16, year: 2022,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "extraordinary-attorney-woo", name: "Extraordinary Attorney Woo", type: "show",
    plot: "A brilliant autistic lawyer navigates her first job at a top law firm, using her extraordinary memory and unconventional way of seeing cases to win the ones everyone else has already written off.",
    cast: ["Park Eun-bin", "Kang Tae-oh", "Kang Ki-young"], seasons: 1, episodes: 16, year: 2022,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["drama", "comedy"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "emotional-weight"],
  },
  {
    id: "crash-landing-on-you", name: "Crash Landing on You", type: "show",
    plot: "A South Korean heiress accidentally paraglides across the border into North Korea during a freak storm, and a principled North Korean army officer risks everything hiding her and getting her home safely.",
    cast: ["Hyun Bin", "Son Ye-jin", "Seo Ji-hye"], seasons: 1, episodes: 16, year: 2019,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["romance", "drama", "comedy"], mood: ["feel-good", "intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "goblin", name: "Goblin", type: "show",
    plot: "An immortal, centuries-old goblin cursed to walk the earth until he finds his human bride, discovers she might be a lonely teenage girl who's also, unknowingly, the reaper's next assignment.",
    cast: ["Gong Yoo", "Kim Go-eun", "Lee Dong-wook"], seasons: 1, episodes: 16, year: 2016,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["fantasy", "romance", "drama"], mood: ["feel-good", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["fantasy-world"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "its-okay-to-not-be-okay", name: "It's Okay to Not Be Okay", type: "show",
    plot: "A psychiatric ward caretaker devoted entirely to his autistic older brother is drawn to a famous, emotionally guarded children's book author, and the two of them slowly help each other confront childhood trauma neither has dealt with.",
    cast: ["Kim Soo-hyun", "Seo Ye-ji", "Oh Jung-se"], seasons: 1, episodes: 16, year: 2020,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["romance", "drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "train-to-busan", name: "Train to Busan", type: "movie",
    plot: "A workaholic father and his young daughter fight to survive a zombie outbreak that erupts aboard their high-speed train to Busan, with no way off and no safe car left to hide in.",
    cast: ["Gong Yoo", "Jung Yu-mi", "Ma Dong-seok"], runtime: 118, year: 2016,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["horror", "thriller", "action"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "plot-twists"],
  },
  {
    id: "rrr", name: "RRR", type: "movie",
    plot: "A fictional reimagining of two real Indian revolutionaries, brought together as friends years before history pit them against the British Raj on opposite sides of a mission, building toward an explosive shared uprising.",
    cast: ["N. T. Rama Rao Jr.", "Ram Charan", "Ajay Devgn"], runtime: 187, year: 2022,
    platforms: ["Netflix"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["action", "drama"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "delhi-crime", name: "Delhi Crime", type: "show",
    plot: "Based on a real case, a Delhi police team races against public outrage and the clock to track down the perpetrators of a horrific crime that shocked the entire country.",
    cast: ["Shefali Shah", "Rasika Dugal", "Adil Hussain"], seasons: 2, episodes: 13, year: 2019,
    platforms: ["Netflix"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["drama", "thriller", "mystery"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "sacred-games", name: "Sacred Games", type: "show",
    plot: "A weary Mumbai police officer gets an anonymous tip from a legendary crime boss that the city has 25 days left to live, and has to untangle decades of the gangster's history to find out why.",
    cast: ["Saif Ali Khan", "Nawazuddin Siddiqui", "Radhika Apte"], seasons: 2, episodes: 16, year: 2018,
    platforms: ["Netflix"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller", "drama", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "kota-factory", name: "Kota Factory", type: "show",
    plot: "A small-town teenager moves to India's coaching-institute capital to cram for engineering entrance exams, and the show follows his batch of friends through the brutal, pressure-cooker world of Indian test prep.",
    cast: ["Mayur More", "Jitendra Kumar", "Ranjan Raj"], seasons: 3, episodes: 28, year: 2019,
    platforms: ["Netflix"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "the-family-man", name: "The Family Man", type: "show",
    plot: "An underpaid, overworked intelligence officer has to juggle high-stakes counter-terrorism missions with the much harder job of keeping his own oblivious family and marriage together.",
    cast: ["Manoj Bajpayee", "Samantha Ruth Prabhu", "Priyamani"], seasons: 2, episodes: 19, year: 2019,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["action", "thriller", "comedy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "mirzapur", name: "Mirzapur", type: "show",
    plot: "A ruthless crime lord's control over the lawless city of Mirzapur is challenged from within his own family, sparking a brutal, multi-generational power struggle for control of the region's gun-running empire.",
    cast: ["Pankaj Tripathi", "Ali Fazal", "Divyendu Sharma"], seasons: 3, episodes: 29, year: 2018,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller", "drama", "action"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "paatal-lok", name: "Paatal Lok", type: "show",
    plot: "A jaded, low-ranking Delhi cop is unexpectedly assigned a high-profile case, and chasing down the four accused men drags him through every stratified layer of Indian society, from the top down to the very bottom.",
    cast: ["Jaideep Ahlawat", "Neeraj Kabi", "Gul Panag"], seasons: 2, episodes: 17, year: 2020,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "panchayat", name: "Panchayat", type: "show",
    plot: "An engineering graduate who couldn't land a better job reluctantly takes a post as village council secretary in rural India, and slowly grows to care about the quirky, close-knit community he was dreading.",
    cast: ["Jitendra Kumar", "Raghubir Yadav", "Neena Gupta"], seasons: 3, episodes: 24, year: 2020,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["comedy", "drama", "slice-of-life"], mood: ["feel-good", "funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "scam-1992", name: "Scam 1992: The Harshad Mehta Story", type: "show",
    plot: "A small-time Mumbai stockbroker exploits loopholes in the Indian banking system to manipulate the stock market on an unprecedented scale, riding the rush all the way to the top before it all collapses.",
    cast: ["Pratik Gandhi", "Shreya Dhanwanthary", "Hemant Kher"], seasons: 1, episodes: 10, year: 2020,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["drama", "thriller"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "four-more-shots-please", name: "Four More Shots Please!", type: "show",
    plot: "Four very different Mumbai women bond over cocktails at their favorite bar, leaning on each other through career setbacks, messy relationships, and the pressure of living life on their own terms.",
    cast: ["Sayani Gupta", "Kirti Kulhari", "Maanvi Gagroo"], seasons: 3, episodes: 30, year: 2019,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "made-in-heaven", name: "Made in Heaven", type: "show",
    plot: "Two Delhi wedding planners stage lavish, picture-perfect weddings for the city's elite, and every event peels back another layer of the class, caste, and gender hypocrisies hiding underneath the celebration.",
    cast: ["Sobhita Dhulipala", "Arjun Mathur", "Kalki Koechlin"], seasons: 2, episodes: 16, year: 2019,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["drama"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "emotional-weight"],
  },
  {
    id: "special-ops", name: "Special Ops", type: "show",
    plot: "A veteran RAW intelligence officer facing an internal inquiry defends his 19-year hunt for the mastermind behind a string of terror attacks, told through five of his most dangerous field agents' missions.",
    cast: ["Kay Kay Menon", "Vinay Pathak", "Karan Tacker"], seasons: 2, episodes: 16, year: 2020,
    platforms: ["Disney+ Hotstar"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["action", "thriller"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "aarya", name: "Aarya", type: "show",
    plot: "A sheltered pharmaceutical-company wife is forced to take over her husband's drug-trafficking business after his murder, transforming from housewife to ruthless operator to protect her three children.",
    cast: ["Sushmita Sen", "Chandrachur Singh", "Sikandar Kher"], seasons: 3, episodes: 27, year: 2020,
    platforms: ["Disney+ Hotstar"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "criminal-justice", name: "Criminal Justice", type: "show",
    plot: "An ordinary young man wakes up next to a murdered woman with no memory of the night before, and has to navigate India's broken criminal justice system with a rookie lawyer as his only hope of proving his innocence.",
    cast: ["Vikrant Massey", "Pankaj Tripathi", "Kirti Kulhari"], seasons: 4, episodes: 40, year: 2019,
    platforms: ["Disney+ Hotstar"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller", "drama", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "the-empire", name: "The Empire", type: "show",
    plot: "The rise of the Mughal dynasty is traced from Babur's first bloody conquest of Hindustan through generations of betrayal, ambition, and warfare that built one of history's greatest empires.",
    cast: ["Kunal Kapoor", "Shabana Azmi", "Dino Morea"], seasons: 2, episodes: 16, year: 2021,
    platforms: ["Disney+ Hotstar"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["drama", "action"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "rudra-the-edge-of-darkness", name: "Rudra: The Edge of Darkness", type: "show",
    plot: "A brilliant but unorthodox Mumbai police officer, still grieving his wife's death, tracks a string of murders that seem to be modeled on a killer he thought he'd already caught years ago.",
    cast: ["Ajay Devgn", "Esha Deol", "Raashii Khanna"], seasons: 1, episodes: 6, year: 2022,
    platforms: ["Disney+ Hotstar"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
];
