import type { RawTitle } from "../shape";

/** Batch 014 — more Hulu and Crunchyroll, still the two thinnest platforms by volume. */
export const RAW: RawTitle[] = [
  {
    id: "grownish", name: "Grown-ish", type: "show",
    plot: "The eldest Johnson kid from black-ish heads off to college and has to figure out who she is away from her big, opinionated family, one bad decision and new friendship at a time.",
    cast: ["Yara Shahidi", "Trevor Jackson", "Emily Arlook"], seasons: 6, episodes: 87, year: 2018,
    platforms: ["Hulu"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "utopia-2020", name: "Utopia", type: "show",
    plot: "A group of comic-book fans obsessed with an underground graphic novel discover it predicted a series of real pandemics, and go on the run when they realize they're now targets themselves.",
    cast: ["John Cusack", "Rainn Wilson", "Sasha Lane"], seasons: 1, episodes: 8, year: 2020,
    platforms: ["Prime Video"], genre: ["thriller", "sci-fi", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "castle-rock", name: "Castle Rock", type: "show",
    plot: "A mysterious prisoner with no memory turns up in the depths of a Maine prison, drawing a defense attorney back to a town where nearly every Stephen King story you've ever read seems to be quietly connected.",
    cast: ["André Holland", "Bill Skarsgård", "Sissy Spacek"], seasons: 2, episodes: 20, year: 2018,
    platforms: ["Hulu"], genre: ["horror", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "wu-tang-an-american-saga", name: "Wu-Tang: An American Saga", type: "show",
    plot: "A dramatized origin story of the Wu-Tang Clan, following a young RZA and his crew navigating the crack epidemic and street violence of 1990s Staten Island on their way to forming one of hip-hop's greatest groups.",
    cast: ["Ashton Sanders", "Shameik Moore", "Siddiq Saunderson"], seasons: 3, episodes: 30, year: 2019,
    platforms: ["Hulu"], genre: ["drama"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "mrs-america", name: "Mrs. America", type: "show",
    plot: "The 1970s fight over the Equal Rights Amendment is told from both sides — the feminist leaders pushing for it and the conservative activist Phyllis Schlafly leading the movement to stop it.",
    cast: ["Cate Blanchett", "Rose Byrne", "Uzo Aduba"], seasons: 1, episodes: 9, year: 2020,
    platforms: ["Hulu"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "the-act", name: "The Act", type: "show",
    plot: "Based on a true crime story, a mother keeps her daughter convinced she's chronically ill for years to maintain control over her — until the daughter starts to realize the truth and plans a horrifying way out.",
    cast: ["Patricia Arquette", "Joey King", "AnnaSophia Robb"], seasons: 1, episodes: 8, year: 2019,
    platforms: ["Hulu"], genre: ["drama", "thriller", "mystery"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "a-teacher", name: "A Teacher", type: "show",
    plot: "A high school English teacher begins an affair with one of her students, and the show follows the slow-motion damage it does to both of them, long after the relationship itself is over.",
    cast: ["Kate Mara", "Nick Robinson"], seasons: 1, episodes: 10, year: 2020,
    platforms: ["Hulu"], genre: ["drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "fresh", name: "Fresh", type: "movie",
    plot: "A woman burned out on dating apps meets a charming stranger at the grocery store and finally feels a real spark — right up until his true, horrifying intentions for her come to light.",
    cast: ["Daisy Edgar-Jones", "Sebastian Stan"], runtime: 114, year: 2022,
    platforms: ["Hulu"], genre: ["horror", "thriller", "comedy"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "happiest-season", name: "Happiest Season", type: "movie",
    plot: "A woman plans to propose to her girlfriend at her family's Christmas gathering, only to find out on the drive there that her girlfriend still hasn't come out to her conservative family at all.",
    cast: ["Kristen Stewart", "Mackenzie Davis", "Aubrey Plaza"], runtime: 102, year: 2020,
    platforms: ["Hulu"], genre: ["romance", "comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "plan-b", name: "Plan B", type: "movie",
    plot: "After a party hookup goes wrong, two best friends race against the clock across South Dakota on one wild night to track down the morning-after pill before it's too late.",
    cast: ["Kuhoo Verma", "Victoria Moroles"], runtime: 108, year: 2021,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "not-okay", name: "Not Okay", type: "movie",
    plot: "A desperate-for-attention aspiring writer fakes a trip to Paris for social media clout, and the lie spirals wildly out of control after she accidentally becomes a viral tragedy influencer.",
    cast: ["Zoey Deutch", "Mia Isaac", "Dylan O'Brien"], runtime: 100, year: 2022,
    platforms: ["Hulu"], genre: ["comedy", "drama"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "boston-strangler-2023", name: "Boston Strangler", type: "movie",
    plot: "Two tenacious female reporters break the story connecting a series of unsolved Boston murders in the 1960s, defying a dismissive police force and newsroom to expose a serial killer no one else was taking seriously.",
    cast: ["Keira Knightley", "Carrie Coon", "Chris Cooper"], runtime: 112, year: 2023,
    platforms: ["Hulu"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "chevalier", name: "Chevalier", type: "movie",
    plot: "The son of an enslaved African woman and a French plantation owner rises to become one of the most celebrated composers and violinists in 18th-century Paris, only to be erased from history by Napoleon.",
    cast: ["Kelvin Harrison Jr.", "Samara Weaving", "Lucy Boynton"], runtime: 108, year: 2022,
    platforms: ["Hulu"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "my-dress-up-darling", name: "My Dress-Up Darling", type: "anime",
    plot: "A shy classmate obsessed with traditional doll-making is recruited by the popular girl who sits next to him to sew cosplay costumes for her, and the two bond over crafting far more than either expected.",
    cast: ["Shoya Ishige", "Hina Suguta"], seasons: 2, episodes: 24, year: 2022,
    platforms: ["Crunchyroll"], genre: ["romance", "comedy", "slice-of-life"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "call-of-the-night", name: "Call of the Night", type: "anime",
    plot: "An insomniac teenager wandering the streets at night meets a charming vampire and asks her to turn him, since he figures a life free of daytime and sleep might finally suit him better.",
    cast: ["Kazuya Nakai", "Fairouz Ai"], seasons: 1, episodes: 13, year: 2022,
    platforms: ["Crunchyroll"], genre: ["romance", "fantasy", "slice-of-life"], mood: ["comfort-escapist", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "the-eminence-in-shadow", name: "The Eminence in Shadow", type: "anime",
    plot: "A teenager obsessed with becoming a secret mastermind character gets reincarnated into a fantasy world and role-plays his way into leading an actual shadowy organization, without realizing the threats he invents are somehow all real.",
    cast: ["Ryota Suzuki", "Sora Amamiya"], seasons: 2, episodes: 20, year: 2022,
    platforms: ["Crunchyroll"], genre: ["fantasy", "comedy", "action"], mood: ["funny-witty", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "plot-twists"],
  },
  {
    id: "classroom-of-the-elite", name: "Classroom of the Elite", type: "anime",
    plot: "At an elite school that ranks students purely by merit and quietly pits them against each other, a seemingly indifferent student turns out to be hiding a calculating strategic mind behind his apathy.",
    cast: ["Shōya Chiba", "Sayumi Suzushiro"], seasons: 3, episodes: 38, year: 2017,
    platforms: ["Crunchyroll"], genre: ["drama", "mystery"], mood: ["cerebral-mystery", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "86-eighty-six", name: "86 EIGHTY-SIX", type: "anime",
    plot: "A nation fighting a drone war insists it has zero casualties, because the actual pilots — a persecuted ethnic minority stripped of legal personhood — are officially not considered human.",
    cast: ["Shuichiro Umeda", "Ayane Sakura"], seasons: 1, episodes: 23, year: 2021,
    platforms: ["Crunchyroll"], genre: ["sci-fi", "action", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "fire-force", name: "Fire Force", type: "anime",
    plot: "In a world where people can spontaneously combust into fire-wielding infernals, a special fire brigade of pyrokinetic soldiers investigates the true cause of the epidemic while battling the infernals it creates.",
    cast: ["Gakuto Kajiwara", "Kengo Kawanishi"], seasons: 2, episodes: 48, year: 2019,
    platforms: ["Crunchyroll"], genre: ["action", "fantasy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "characters"],
  },
  {
    id: "the-apothecary-diaries", name: "The Apothecary Diaries", type: "anime",
    plot: "A sharp-witted young apothecary sold into servitude at the imperial palace can't help solving the mysterious ailments and poisonings that keep cropping up among the emperor's concubines.",
    cast: ["Aoi Yūki", "Genki Muro"], seasons: 2, episodes: 48, year: 2023,
    platforms: ["Crunchyroll"], genre: ["mystery", "drama"], mood: ["cerebral-mystery", "funny-witty"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["historical"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "delicious-in-dungeon", name: "Delicious in Dungeon", type: "anime",
    plot: "Broke after losing all their supplies to a dragon, a party of adventurers decides the only way to keep exploring the dungeon is to start cooking and eating the monsters they find along the way.",
    cast: ["Kentaro Kumagai", "Saori Hayami"], seasons: 1, episodes: 24, year: 2024,
    platforms: ["Crunchyroll"], genre: ["fantasy", "comedy", "action"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["humor", "world-building"],
  },
  {
    id: "mashle", name: "Mashle: Magic and Muscles", type: "anime",
    plot: "In a world where magic determines your entire worth, a boy born with zero magical power trains his body to superhuman strength instead, and punches his way through a magic academy that would otherwise reject him.",
    cast: ["Yuma Uchida", "Ayaka Suwa"], seasons: 2, episodes: 25, year: 2023,
    platforms: ["Crunchyroll"], genre: ["comedy", "action", "fantasy"], mood: ["funny-silly", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "undead-unluck", name: "Undead Unluck", type: "anime",
    plot: "A girl whose touch causes catastrophic bad luck for anyone around her falls for an immortal man who can't die no matter what happens to him, and the only two people who could possibly survive loving each other team up.",
    cast: ["Asami Seto", "Yuichiro Umehara"], seasons: 1, episodes: 25, year: 2023,
    platforms: ["Crunchyroll"], genre: ["action", "comedy", "fantasy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "kaiju-no-8", name: "Kaiju No. 8", type: "anime",
    plot: "A man stuck cleaning up kaiju corpses for a living gets accidentally infused with monster powers of his own, and has to hide his new kaiju form while trying to join the very defense force sworn to kill things like him.",
    cast: ["Kaito Ishikawa", "Kikunosuke Toya"], seasons: 1, episodes: 12, year: 2024,
    platforms: ["Crunchyroll"], genre: ["action", "sci-fi"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
];
