import type { RawTitle } from "../shape";

/** Batch 015 — Indian cinema (Prime Video/Netflix) and a few more Korean Netflix titles. */
export const RAW: RawTitle[] = [
  {
    id: "gully-boy", name: "Gully Boy", type: "movie",
    plot: "A young man from a Mumbai slum discovers an outlet for his frustration and ambition in underground rap, and has to fight his own family's expectations as hard as he fights for a shot at a music career.",
    cast: ["Ranveer Singh", "Alia Bhatt", "Siddhant Chaturvedi"], runtime: 154, year: 2019,
    platforms: ["Prime Video"], genre: ["drama"], mood: ["intense", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "andhadhun", name: "AndhaDhun", type: "movie",
    plot: "A pianist pretending to be blind for artistic reasons accidentally witnesses a murder, and has to keep up the act to survive while the people around him spiral into an escalating string of lies and cover-ups.",
    cast: ["Ayushmann Khurrana", "Tabu", "Radhika Apte"], runtime: 139, year: 2018,
    platforms: ["Prime Video"], genre: ["thriller", "comedy", "mystery"], mood: ["cerebral-mystery", "dark"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "piku", name: "Piku", type: "movie",
    plot: "A stressed-out Delhi woman drives her stubborn, hypochondriac elderly father cross-country to Kolkata, and the road trip forces both of them to confront the affection buried under all their bickering.",
    cast: ["Deepika Padukone", "Amitabh Bachchan", "Irrfan Khan"], runtime: 125, year: 2015,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "zindagi-na-milegi-dobara", name: "Zindagi Na Milegi Dobara", type: "movie",
    plot: "Three childhood friends take a bachelor road trip through Spain before one of them gets married, and the trip's extreme-sports itinerary starts forcing each of them to confront fears they've buried for years.",
    cast: ["Hrithik Roshan", "Farhan Akhtar", "Abhay Deol"], runtime: 155, year: 2011,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "3-idiots", name: "3 Idiots", type: "movie",
    plot: "Two friends go searching for their long-lost, most brilliant college roommate years after graduation, and the search unravels into flashbacks about the friendship that got all three of them through a brutal engineering school.",
    cast: ["Aamir Khan", "R. Madhavan", "Sharman Joshi"], runtime: 170, year: 2009,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["funny-witty", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "barfi", name: "Barfi!", type: "movie",
    plot: "A deaf-mute man's irrepressible charm and optimism draws two very different women into his orbit in 1970s Darjeeling, one of whom is autistic, in a story told mostly without dialogue.",
    cast: ["Ranbir Kapoor", "Priyanka Chopra", "Ileana D'Cruz"], runtime: 151, year: 2012,
    platforms: ["Prime Video"], genre: ["romance", "comedy", "drama"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "tumbbad", name: "Tumbbad", type: "movie",
    plot: "Across three generations of a cursed family in rural Maharashtra, greed keeps pulling a bloodline back to an ancient, monstrous god who guards a fortune of gold in the depths of a forbidden temple.",
    cast: ["Sohum Shah", "Jyoti Malshe"], runtime: 104, year: 2018,
    platforms: ["Prime Video"], genre: ["horror", "fantasy", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "queen-2014", name: "Queen", type: "movie",
    plot: "Dumped days before her wedding, a sheltered Delhi woman decides to go on her already-booked honeymoon to Europe alone, and the solo trip turns into the first real adventure — and self-discovery — of her life.",
    cast: ["Kangana Ranaut", "Rajkummar Rao", "Lisa Haydon"], runtime: 146, year: 2013,
    platforms: ["Netflix"], genre: ["comedy", "drama"], mood: ["feel-good", "funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "dangal", name: "Dangal", type: "movie",
    plot: "A former amateur wrestler trains his two daughters to become India's first world-class female wrestlers, fighting both national indifference and his own daughters' resistance to the brutal training regimen.",
    cast: ["Aamir Khan", "Fatima Sana Shaikh", "Sanya Malhotra"], runtime: 161, year: 2016,
    platforms: ["Netflix"], genre: ["drama"], mood: ["intense", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "lagaan", name: "Lagaan", type: "movie",
    plot: "Villagers in colonial India facing a crushing tax challenge their British rulers to a cricket match instead, with three years of tax exemption on the line if they can somehow win a sport none of them have ever played.",
    cast: ["Aamir Khan", "Gracy Singh", "Rachel Shelley"], runtime: 224, year: 2001,
    platforms: ["Netflix"], genre: ["drama"], mood: ["feel-good", "intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "my-name", name: "My Name", type: "show",
    plot: "A woman infiltrates the police force undercover on orders from a crime boss to find out who murdered her father, and has to decide where her loyalty actually lies as the case gets more complicated.",
    cast: ["Han So-hee", "Park Hee-soon", "Ahn Bo-hyun"], seasons: 1, episodes: 8, year: 2021,
    platforms: ["Netflix"], genre: ["thriller", "action", "drama"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "d-p", name: "D.P.", type: "show",
    plot: "A soldier assigned to a military police unit that hunts down deserters starts to realize the desertions are almost always a symptom of the brutal abuse happening inside the barracks, not the cause.",
    cast: ["Jung Hae-in", "Koo Kyo-hwan", "Kim Sung-kyun"], seasons: 2, episodes: 12, year: 2021,
    platforms: ["Netflix"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "hellbound", name: "Hellbound", type: "show",
    plot: "Supernatural creatures start appearing to publicly, brutally execute random people who've been given an otherworldly 'decree,' and a new religious movement rises up around the terrifying phenomenon.",
    cast: ["Yoo Ah-in", "Park Jeong-min", "Kim Hyun-joo"], seasons: 1, episodes: 6, year: 2021,
    platforms: ["Netflix"], genre: ["horror", "thriller", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "move-to-heaven", name: "Move to Heaven", type: "show",
    plot: "An autistic young man inherits his late father's trauma-cleaning business, clearing out the belongings of the deceased, and teams up with his estranged ex-convict uncle to learn what the job is really about.",
    cast: ["Lee Je-hoon", "Tang Jun-sang", "Hong Seung-hee"], seasons: 1, episodes: 10, year: 2021,
    platforms: ["Netflix"], genre: ["drama"], mood: ["feel-good", "dark"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
];
