import type { RawTitle } from "../shape";

/** Batch 016 — more movies: Netflix action/thriller originals + HBO Max blockbusters. */
export const RAW: RawTitle[] = [
  {
    id: "extraction-2", name: "Extraction 2", type: "movie",
    plot: "Having barely survived his last job, mercenary Tyler Rake takes on a near-impossible mission to break a family out of a brutal Georgian prison, with an entire criminal empire in pursuit.",
    cast: ["Chris Hemsworth", "Golshifteh Farahani", "Adam Bessa"], runtime: 122, year: 2023,
    platforms: ["Netflix"], genre: ["action"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-killer-2023", name: "The Killer", type: "movie",
    plot: "A meticulous, detached assassin's carefully controlled routine unravels after a job goes wrong, sending him on a methodical, increasingly personal path of retribution across the globe.",
    cast: ["Michael Fassbender", "Tilda Swinton", "Charles Parnell"], runtime: 118, year: 2023,
    platforms: ["Netflix"], genre: ["thriller", "action"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "spenser-confidential", name: "Spenser Confidential", type: "movie",
    plot: "A newly released ex-cop and ex-con stumbles onto a police corruption conspiracy tied to the murder of two officers, and teams up with an aspiring MMA fighter to dig into it against every warning to stay out.",
    cast: ["Mark Wahlberg", "Winston Duke", "Alan Arkin"], runtime: 111, year: 2020,
    platforms: ["Netflix"], genre: ["action", "comedy", "mystery"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "plot-twists"],
  },
  {
    id: "triple-frontier", name: "Triple Frontier", type: "movie",
    plot: "Five former Special Forces operators reunite for one last job, robbing a South American drug lord's fortune, only to find that stealing the money is far easier than getting it — and themselves — out alive.",
    cast: ["Ben Affleck", "Oscar Isaac", "Charlie Hunnam"], runtime: 125, year: 2019,
    platforms: ["Netflix"], genre: ["action", "thriller"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "the-old-guard", name: "The Old Guard", type: "movie",
    plot: "A team of nearly-immortal mercenary warriors who've fought in secret for centuries is exposed by a pharmaceutical company determined to exploit their regenerative power, forcing them out of the shadows for good.",
    cast: ["Charlize Theron", "KiKi Layne", "Matthias Schoenaerts"], runtime: 125, year: 2020,
    platforms: ["Netflix"], genre: ["action", "fantasy"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "army-of-the-dead", name: "Army of the Dead", type: "movie",
    plot: "A crew of mercenaries is offered a fortune to pull off a heist inside a zombie-quarantined Las Vegas, right before the government nukes the whole city off the map.",
    cast: ["Dave Bautista", "Ella Purnell", "Omari Hardwick"], runtime: 148, year: 2021,
    platforms: ["Netflix"], genre: ["horror", "action"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "bright", name: "Bright", type: "movie",
    plot: "In a modern LA where orcs, elves, and humans live in uneasy coexistence, a human cop and his orc partner stumble onto a magic wand that every faction in the city is suddenly willing to kill for.",
    cast: ["Will Smith", "Joel Edgerton", "Noomi Rapace"], runtime: 117, year: 2017,
    platforms: ["Netflix"], genre: ["action", "fantasy"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "furiosa-a-mad-max-saga", name: "Furiosa: A Mad Max Saga", type: "movie",
    plot: "Snatched from the Green Place as a child, young Furiosa survives years in the clutches of a warlord biker horde, forging the ruthlessness and skill that will one day make her a legend of the Wasteland.",
    cast: ["Anya Taylor-Joy", "Chris Hemsworth", "Tom Burke"], runtime: 148, year: 2024,
    platforms: ["HBO Max"], genre: ["action", "sci-fi"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "beetlejuice-beetlejuice", name: "Beetlejuice Beetlejuice", type: "movie",
    plot: "Decades after the events of the first film, a family crisis brings the Deetz women back to Winter River, and someone says the name three times too many, bringing the mischievous ghost with the striped suit roaring back.",
    cast: ["Michael Keaton", "Winona Ryder", "Jenna Ortega"], runtime: 105, year: 2024,
    platforms: ["HBO Max"], genre: ["comedy", "fantasy", "horror"], mood: ["funny-silly", "dark"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["franchise"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "wonka", name: "Wonka", type: "movie",
    plot: "Before he had a chocolate factory, a young, penniless Willy Wonka arrives in the city with nothing but a hatful of dreams, determined to share his magical chocolate with the world despite a cartel of rival chocolatiers.",
    cast: ["Timothée Chalamet", "Calah Lane", "Hugh Grant"], runtime: 116, year: 2023,
    platforms: ["HBO Max"], genre: ["comedy", "fantasy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "the-meg", name: "The Meg", type: "movie",
    plot: "A deep-sea rescue diver is pulled back into action when a research submersible is attacked at the bottom of the Mariana Trench by a 75-foot prehistoric shark thought to have gone extinct millions of years ago.",
    cast: ["Jason Statham", "Li Bingbing", "Rainn Wilson"], runtime: 113, year: 2018,
    platforms: ["HBO Max"], genre: ["action", "horror", "sci-fi"], mood: ["intense", "light"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "rampage-2018", name: "Rampage", type: "movie",
    plot: "A primatologist's genetically altered gorilla is caught up in a rogue experiment that turns it and two other animals into rapidly growing, rampaging monsters heading straight for downtown Chicago.",
    cast: ["Dwayne Johnson", "Naomie Harris", "Malin Åkerman"], runtime: 107, year: 2018,
    platforms: ["HBO Max"], genre: ["action", "sci-fi"], mood: ["intense", "light"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "san-andreas", name: "San Andreas", type: "movie",
    plot: "A rescue-helicopter pilot flies across a California devastated by a record-breaking earthquake to reach his estranged daughter, as the whole San Andreas fault continues to tear the state apart.",
    cast: ["Dwayne Johnson", "Carla Gugino", "Alexandra Daddario"], runtime: 114, year: 2015,
    platforms: ["HBO Max"], genre: ["action"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "crazy-stupid-love", name: "Crazy, Stupid, Love.", type: "movie",
    plot: "A newly divorced middle-aged man gets a crash course in dating from a slick young bachelor at a bar, while his teenage son and the family babysitter are tangled up in their own hopeless crush.",
    cast: ["Steve Carell", "Ryan Gosling", "Julianne Moore"], runtime: 118, year: 2011,
    platforms: ["HBO Max"], genre: ["romance", "comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "sherlock-holmes-2009", name: "Sherlock Holmes", type: "movie",
    plot: "Sherlock Holmes and Dr. Watson investigate a string of murders tied to a secret cult and a supposedly executed sorcerer who appears to have come back from the dead to menace London.",
    cast: ["Robert Downey Jr.", "Jude Law", "Rachel McAdams"], runtime: 128, year: 2009,
    platforms: ["HBO Max"], genre: ["mystery", "action"], mood: ["cerebral-mystery", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "raymond-and-ray", name: "Raymond & Ray", type: "movie",
    plot: "Two long-estranged half-brothers reunite to bury the abusive father they both hated, and the funeral trip forces them to finally confront how differently his cruelty shaped each of their lives.",
    cast: ["Ewan McGregor", "Ethan Hawke", "Maribel Verdú"], runtime: 106, year: 2022,
    platforms: ["Apple TV"], genre: ["drama", "comedy"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "hala", name: "Hala", type: "movie",
    plot: "A Pakistani-American teenager balances her conservative household's expectations against a new boyfriend and her own creative ambitions, right as she stumbles onto a secret that upends her parents' marriage.",
    cast: ["Geraldine Viswanathan", "Purbi Joshi", "Azad Khan"], runtime: 94, year: 2019,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
];
