import type { RawTitle } from "../shape";

/** Batch 017 — more Crunchyroll anime; anime remains the smallest type category overall. */
export const RAW: RawTitle[] = [
  {
    id: "black-butler", name: "Black Butler", type: "anime",
    plot: "A young English earl who sold his soul for revenge is served by a demon butler of impossible skill and elegance, bound to protect him until the day their contract is finally fulfilled.",
    cast: ["Daisuke Ono", "Brina Palencia"], seasons: 3, episodes: 39, year: 2008,
    platforms: ["Crunchyroll"], genre: ["fantasy", "mystery", "comedy"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "soul-eater", name: "Soul Eater", type: "anime",
    plot: "Students at a school for weapon-meisters pair human students who can transform into weapons with the meisters who wield them, training together to collect enough evil souls to forge a death scythe.",
    cast: ["Chiaki Omigawa", "Kōki Uchiyama"], seasons: 1, episodes: 51, year: 2008,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "comedy"], mood: ["funny-witty", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "boruto-naruto-next-generations", name: "Boruto: Naruto Next Generations", type: "anime",
    plot: "Set a generation after the original Naruto, the Hidden Leaf's new class of young ninja — led by the Hokage's own son, who resents his father's absence — face new threats to the peace Naruto fought so hard to win.",
    cast: ["Yuko Sanpei", "Kokoro Kikuchi"], seasons: 2, episodes: 293, year: 2017,
    platforms: ["Crunchyroll"], genre: ["action", "fantasy"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "inuyasha", name: "Inuyasha", type: "anime",
    plot: "A modern Japanese schoolgirl is pulled through a well into the feudal era, where she teams up with a half-demon bound by an ancient curse to recover the shattered shards of a wish-granting jewel before demons do.",
    cast: ["Kappei Yamaguchi", "Satsuki Yukino"], seasons: 7, episodes: 167, year: 2000,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "romance"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "ranma-1-2", name: "Ranma ½", type: "anime",
    plot: "A young martial artist cursed to turn into a girl whenever splashed with cold water has to navigate an arranged engagement, rival suitors, and constant chaos, all while trying to find a cure.",
    cast: ["Kappei Yamaguchi", "Megumi Hayashibara"], seasons: 7, episodes: 161, year: 1989,
    platforms: ["Crunchyroll"], genre: ["comedy", "romance", "action"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["humor", "characters"],
  },
  {
    id: "yu-yu-hakusho", name: "Yu Yu Hakusho", type: "anime",
    plot: "A delinquent teenager killed saving a child's life is given a second chance as a spirit detective, policing the boundary between the human and demon worlds against threats far above his old street-fighting weight class.",
    cast: ["Nozomu Sasaki", "Noriko Hidaka"], seasons: 4, episodes: 112, year: 1992,
    platforms: ["Crunchyroll"], genre: ["action", "fantasy", "comedy"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "trigun", name: "Trigun", type: "anime",
    plot: "A pacifist gunslinger with a $$60 billion bounty on his head and a reputation for city-leveling destruction is actually trying his hardest to save everyone he meets without firing a single fatal shot.",
    cast: ["Masaya Onosaka", "Kazuhiko Inoue"], seasons: 1, episodes: 26, year: 1998,
    platforms: ["Crunchyroll"], genre: ["sci-fi", "action", "comedy"], mood: ["funny-witty", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "samurai-champloo", name: "Samurai Champloo", type: "anime",
    plot: "A waitress in Edo-era Japan hires two wildly mismatched swordsmen — one wild and impulsive, one disciplined and quiet — to help her find the mysterious 'samurai who smells of sunflowers' from her past.",
    cast: ["Ginpei Sato", "Kazuya Nakai"], seasons: 1, episodes: 26, year: 2004,
    platforms: ["Crunchyroll"], genre: ["action", "comedy", "drama"], mood: ["funny-witty", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "ghost-in-the-shell-stand-alone-complex", name: "Ghost in the Shell: Stand Alone Complex", type: "anime",
    plot: "A cybernetically enhanced counter-terrorism unit investigates cybercrime in a near-future Japan where minds can be hacked as easily as computers, and identity itself has become a slippery concept.",
    cast: ["Atsuko Tanaka", "Akio Ōtsuka"], seasons: 2, episodes: 52, year: 2002,
    platforms: ["Crunchyroll"], genre: ["sci-fi", "action", "mystery"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["world-building", "plot-twists"],
  },
  {
    id: "ouran-high-school-host-club", name: "Ouran High School Host Club", type: "anime",
    plot: "A scholarship student at an elite academy accidentally breaks an expensive vase and is forced to work off the debt disguised as a boy in the school's absurdly popular all-male host club.",
    cast: ["Maaya Sakamoto", "Mamoru Miyano"], seasons: 1, episodes: 26, year: 2006,
    platforms: ["Crunchyroll"], genre: ["comedy", "romance"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "nana", name: "NANA", type: "anime",
    plot: "Two very different young women, both named Nana, meet by chance on a train to Tokyo and end up sharing an apartment, their friendship tested as one chases punk-rock stardom and the other chases love.",
    cast: ["Romi Park", "Atsuko Enomoto"], seasons: 1, episodes: 47, year: 2006,
    platforms: ["Crunchyroll"], genre: ["drama", "romance"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "paranoia-agent", name: "Paranoia Agent", type: "anime",
    plot: "A wave of seemingly random attacks by a roller-skating boy with a golden bat sweeps through Tokyo, and detectives investigating the case start uncovering how deeply the city's collective anxieties are actually connected.",
    cast: ["Toshihiko Seki", "Shion Nakamaru"], seasons: 1, episodes: 13, year: 2004,
    platforms: ["Crunchyroll"], genre: ["mystery", "horror", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "baccano", name: "Baccano!", type: "anime",
    plot: "Alchemists, mobsters, and thieves on a 1930s cross-country train all collide over a stolen immortality elixir, with the story told wildly out of chronological order until every thread finally clicks into place.",
    cast: ["Yuka Nanri", "Rie Kugimiya"], seasons: 1, episodes: 16, year: 2007,
    platforms: ["Crunchyroll"], genre: ["fantasy", "mystery", "action"], mood: ["cerebral-mystery", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "durarara", name: "Durarara!!", type: "anime",
    plot: "A headless, superhuman motorcycle-riding dullahan roams the streets of Tokyo's Ikebukuro district, and her presence turns out to connect an enormous, tangled web of gangs, urban legends, and ordinary teenagers.",
    cast: ["Mamoru Miyano", "Kana Hanazawa"], seasons: 1, episodes: 26, year: 2010,
    platforms: ["Crunchyroll"], genre: ["mystery", "fantasy", "action"], mood: ["cerebral-mystery", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "monster", name: "Monster", type: "anime",
    plot: "A brilliant surgeon who once saved a young boy's life over his own hospital director's orders spends years hunting the man down after discovering the boy grew into a serial killer.",
    cast: ["Hidenobu Kiuchi", "Toshiyuki Morikawa"], seasons: 1, episodes: 74, year: 2004,
    platforms: ["Crunchyroll"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["plot-twists", "characters"],
  },
  {
    id: "hajime-no-ippo", name: "Hajime no Ippo", type: "anime",
    plot: "A shy, constantly bullied high schooler discovers a hidden talent for boxing after a chance encounter with a pro fighter, and slowly transforms into one of the most promising featherweights in Japan.",
    cast: ["Kohsuke Toriumi", "Wataru Takagi"], seasons: 3, episodes: 114, year: 2000,
    platforms: ["Crunchyroll"], genre: ["drama", "comedy"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "emotional-weight"],
  },
];
