import type { RawTitle } from "../shape";

/** Batch 018 — more anime (still proportionally thinnest type) plus a few more Apple TV/Hulu
 * titles (still behind Netflix/HBO Max in platform volume). */
export const RAW: RawTitle[] = [
  {
    id: "great-teacher-onizuka", name: "Great Teacher Onizuka", type: "anime",
    plot: "A former biker gang member with zero teaching credentials becomes a high school homeroom teacher, and his completely unconventional, often illegal methods somehow keep actually reaching the students everyone else gave up on.",
    cast: ["Wataru Takagi", "Akiko Yajima"], seasons: 1, episodes: 43, year: 1999,
    platforms: ["Crunchyroll"], genre: ["comedy", "drama"], mood: ["funny-silly", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "beelzebub", name: "Beelzebub", type: "anime",
    plot: "The most feared delinquent in his high school is chosen to raise the infant son of the demon king, and has to juggle terrifying baby tantrums with his usual daily gang warfare.",
    cast: ["Tomokazu Sugita", "Kana Hanazawa"], seasons: 1, episodes: 60, year: 2011,
    platforms: ["Crunchyroll"], genre: ["comedy", "action", "fantasy"], mood: ["funny-silly", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "devilman-crybaby", name: "Devilman Crybaby", type: "anime",
    plot: "A gentle, easily-moved teenager merges with a demon to gain its power without losing his human heart, and has to hold onto his compassion as the world around him spirals into paranoia and violence.",
    cast: ["Kōki Uchiyama", "Ayaka Ohashi"], seasons: 1, episodes: 10, year: 2018,
    platforms: ["Crunchyroll"], genre: ["horror", "drama", "action"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "land-of-the-lustrous", name: "Land of the Lustrous", type: "anime",
    plot: "Crystalline immortal beings fight off meteorite-hunters trying to harvest them for jewelry, and the least skilled, most fragile of them all is determined to finally find a purpose worth fighting for.",
    cast: ["Tomoyo Kurosawa"], seasons: 1, episodes: 12, year: 2017,
    platforms: ["Crunchyroll"], genre: ["fantasy", "sci-fi", "action"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "march-comes-in-like-a-lion", name: "March Comes in Like a Lion", type: "anime",
    plot: "A withdrawn teenage professional shogi player living alone struggles with grief and isolation, slowly opening up thanks to a warm neighboring family who keep pulling him into their orbit.",
    cast: ["Kengo Kawanishi", "Asami Seto"], seasons: 2, episodes: 44, year: 2016,
    platforms: ["Crunchyroll"], genre: ["drama", "slice-of-life"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "a-place-further-than-the-universe", name: "A Place Further Than the Universe", type: "anime",
    plot: "Four teenage girls with nothing else in common team up to join a real scientific expedition to Antarctica, chasing dreams, grief, and friendship all the way to the bottom of the world.",
    cast: ["Inori Minase", "Nanaka Suwa"], seasons: 1, episodes: 13, year: 2018,
    platforms: ["Crunchyroll"], genre: ["drama", "comedy"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "non-non-biyori", name: "Non Non Biyori", type: "anime",
    plot: "A Tokyo transplant adjusts to life at a tiny rural school with only five students total, and the show settles into the slow, gentle rhythms of countryside childhood with almost no plot to speak of.",
    cast: ["Kotori Koiwai", "Ai Kayano"], seasons: 3, episodes: 37, year: 2013,
    platforms: ["Crunchyroll"], genre: ["comedy", "slice-of-life"], mood: ["comfort-background", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "humor"],
  },
  {
    id: "barakamon", name: "Barakamon", type: "anime",
    plot: "A prickly, perfectionist calligrapher exiles himself to a remote island after punching out a critic, and the island's chaotic, unbothered locals — especially one relentless little girl — slowly loosen him up.",
    cast: ["Makoto Furukawa", "Kotori Koiwai"], seasons: 1, episodes: 12, year: 2014,
    platforms: ["Crunchyroll"], genre: ["comedy", "slice-of-life"], mood: ["feel-good", "comfort-background"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "the-tatami-galaxy", name: "The Tatami Galaxy", type: "anime",
    plot: "A disillusioned college student replays his last two years over and over across different club choices, each timeline ending in the same regret until he finally figures out what he's actually been missing.",
    cast: ["Shintaro Sonooka", "Saori Hayami"], seasons: 1, episodes: 11, year: 2010,
    platforms: ["Crunchyroll"], genre: ["comedy", "drama"], mood: ["cerebral-ideas", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "welcome-to-the-nhk", name: "Welcome to the NHK", type: "anime",
    plot: "A paranoid, reclusive young man convinced a shadowy conspiracy is responsible for his own social withdrawal is pulled out of his apartment by a mysterious girl determined to help him rejoin the world.",
    cast: ["Hiro Shimono", "Ryōko Shiraishi"], seasons: 1, episodes: 24, year: 2006,
    platforms: ["Crunchyroll"], genre: ["comedy", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "serial-experiments-lain", name: "Serial Experiments Lain", type: "anime",
    plot: "A withdrawn, awkward teenager starts receiving emails from a classmate who committed suicide, pulling her deeper into a networked virtual world that starts blurring the line with reality itself.",
    cast: ["Kaori Shimizu"], seasons: 1, episodes: 13, year: 1998,
    platforms: ["Crunchyroll"], genre: ["sci-fi", "horror", "mystery"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "extrapolations", name: "Extrapolations", type: "show",
    plot: "An anthology spanning decades into a near-future shaped by escalating climate change, following different characters each episode as they navigate a world reorganizing itself around ecological collapse.",
    cast: ["Meryl Streep", "Kit Harington", "Sienna Miller"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Apple TV"], genre: ["sci-fi", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "sunny-apple", name: "Sunny", type: "show",
    plot: "After her husband and son vanish in a plane crash, a grieving American woman in Japan is given a domestic robot she never wanted — and starts to suspect the robot knows more about the disappearance than it's letting on.",
    cast: ["Rashida Jones", "Hidetoshi Nishijima", "Judy Ongg"], seasons: 1, episodes: 10, year: 2024,
    platforms: ["Apple TV"], genre: ["mystery", "sci-fi", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "prehistoric-planet", name: "Prehistoric Planet", type: "show",
    plot: "Cutting-edge visual effects and paleontological research bring dinosaurs back to life in immersive, nature-documentary detail, following them through coasts, deserts, freshwater, and ice like any modern wildlife series.",
    cast: ["David Attenborough"], seasons: 2, episodes: 10, year: 2022,
    platforms: ["Apple TV"], genre: ["documentary"], mood: ["cerebral-ideas", "intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["world-building", "characters"],
  },
  {
    id: "the-new-look", name: "The New Look", type: "show",
    plot: "In Nazi-occupied and newly liberated Paris, Christian Dior and Coco Chanel take very different paths through the war, and the fashion revolution Dior launches afterward is inseparable from what he survived to get there.",
    cast: ["Ben Mendelsohn", "Juliette Binoche", "John Malkovich"], seasons: 1, episodes: 10, year: 2024,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "reboot-hulu", name: "Reboot", type: "show",
    plot: "A streaming executive revives a cheesy early-2000s sitcom with a gritty modern reboot, and the original cast has to relearn how to work together while a clueless network tries to make everyone happy at once.",
    cast: ["Keegan-Michael Key", "Judy Greer", "Johnny Knoxville"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-witty", "funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "killing-it", name: "Killing It", type: "show",
    plot: "A broke Florida man enters a bizarre statewide python-hunting contest with a massive cash prize, and the increasingly absurd competition becomes his last real shot at a normal life.",
    cast: ["Craig Robinson", "Claudia O'Doherty", "Rell Battle"], seasons: 2, episodes: 16, year: 2022,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "how-i-met-your-father", name: "How I Met Your Father", type: "show",
    plot: "In 2050, a mother tells her son the long, winding story of how she met his father, unfolding through her chaotic circle of friends navigating dating and adulthood in 2020s New York.",
    cast: ["Hilary Duff", "Christopher Lowell", "Francia Raisa"], seasons: 2, episodes: 20, year: 2022,
    platforms: ["Hulu"], genre: ["comedy", "romance"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "emotional-weight"],
  },
];
