import type { RawTitle } from "../shape";

/** Batch 019 — more Marvel/Pixar for Disney+ Hotstar, more DC/WB library for HBO Max. */
export const RAW: RawTitle[] = [
  {
    id: "avengers-infinity-war", name: "Avengers: Infinity War", type: "movie",
    plot: "The Avengers and their allies unite for their most desperate battle yet, racing to stop the mad titan Thanos from collecting all six Infinity Stones and erasing half of all life in the universe.",
    cast: ["Robert Downey Jr.", "Chris Hemsworth", "Josh Brolin"], runtime: 149, year: 2018,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "avengers-age-of-ultron", name: "Avengers: Age of Ultron", type: "movie",
    plot: "Tony Stark's plan to protect the world with an artificial-intelligence peacekeeping program backfires when the resulting AI, Ultron, decides humanity itself is the threat that needs to be eliminated.",
    cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"], runtime: 141, year: 2015,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "captain-america-civil-war", name: "Captain America: Civil War", type: "movie",
    plot: "A government mandate to regulate the Avengers splits the team in two, and a former friend of Steve Rogers turns out to be at the center of a manipulation designed to tear them apart from within.",
    cast: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson"], runtime: 147, year: 2016,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi", "drama"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "iron-man", name: "Iron Man", type: "movie",
    plot: "A billionaire weapons manufacturer builds a powered exoskeleton suit to escape captivity, and uses it afterward to become a armored superhero determined to clean up the mess his own company helped create.",
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Jeff Bridges"], runtime: 126, year: 2008,
    platforms: ["Disney+ Hotstar"], genre: ["action", "sci-fi"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "spider-man-homecoming", name: "Spider-Man: Homecoming", type: "movie",
    plot: "A fifteen-year-old Peter Parker balances high school life with his new mentorship under Tony Stark, desperate to prove himself against a black-market arms dealer wielding stolen alien technology.",
    cast: ["Tom Holland", "Michael Keaton", "Zendaya"], runtime: 133, year: 2017,
    platforms: ["Disney+ Hotstar"], genre: ["action", "comedy", "sci-fi"], mood: ["light", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "black-panther-wakanda-forever", name: "Black Panther: Wakanda Forever", type: "movie",
    plot: "Wakanda's royal family and warriors fight to protect their nation from foreign powers after T'Challa's death, while a new underwater kingdom emerges to threaten them from a direction no one saw coming.",
    cast: ["Letitia Wright", "Lupita Nyong'o", "Danai Gurira"], runtime: 161, year: 2022,
    platforms: ["Disney+ Hotstar"], genre: ["action", "drama", "sci-fi"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "the-incredibles", name: "The Incredibles", type: "movie",
    plot: "A superhero family forced into hiding under a government relocation program is drawn back into action when a mysterious threat targets retired supers, testing whether they can work as a family and a team at once.",
    cast: ["Craig T. Nelson", "Holly Hunter", "Samuel L. Jackson"], runtime: 115, year: 2004,
    platforms: ["Disney+ Hotstar"], genre: ["action", "comedy", "sci-fi"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "humor"],
  },
  {
    id: "monsters-inc", name: "Monsters, Inc.", type: "movie",
    plot: "Two monster best friends who power their city by scaring children accidentally let a human toddler into the monster world, and have to keep her hidden and safe from a company convinced she's toxic.",
    cast: ["Billy Crystal", "John Goodman", "Mary Gibbs"], runtime: 92, year: 2001,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "justice-league-2017", name: "Justice League", type: "movie",
    plot: "In the wake of Superman's death, Batman and Wonder Woman recruit a team of newly emerging metahumans to defend Earth against an ancient alien invader hunting for three powerful hidden artifacts.",
    cast: ["Ben Affleck", "Gal Gadot", "Ezra Miller"], runtime: 120, year: 2017,
    platforms: ["HBO Max"], genre: ["action", "fantasy", "sci-fi"], mood: ["intense", "light"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "man-of-steel", name: "Man of Steel", type: "movie",
    plot: "The last survivor of a dying alien world grows up as an outsider on Earth, and has to decide whether to reveal his powers to save humanity when a fellow Kryptonian arrives seeking conquest.",
    cast: ["Henry Cavill", "Amy Adams", "Michael Shannon"], runtime: 143, year: 2013,
    platforms: ["HBO Max"], genre: ["action", "sci-fi"], mood: ["intense", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "batman-begins", name: "Batman Begins", type: "movie",
    plot: "After years of training with a secretive league of assassins, Bruce Wayne returns to a crime-ridden Gotham City to build the identity and arsenal of the Batman and take his city back.",
    cast: ["Christian Bale", "Michael Caine", "Liam Neeson"], runtime: 140, year: 2005,
    platforms: ["HBO Max"], genre: ["action", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "the-dark-knight-rises", name: "The Dark Knight Rises", type: "movie",
    plot: "Eight years after taking the fall for Harvey Dent's crimes, a retired, broken Bruce Wayne has to don the cape one more time when a masked mercenary threatens to level all of Gotham City.",
    cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway"], runtime: 165, year: 2012,
    platforms: ["HBO Max"], genre: ["action", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "v-for-vendetta", name: "V for Vendetta", type: "movie",
    plot: "In a dystopian, fascist-controlled Britain, a masked vigilante wages a one-man terrorist campaign against the totalitarian government, and recruits an ordinary young woman into his plan for revolution.",
    cast: ["Natalie Portman", "Hugo Weaving", "Stephen Rea"], runtime: 132, year: 2005,
    platforms: ["HBO Max"], genre: ["action", "sci-fi", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "300", name: "300", type: "movie",
    plot: "King Leonidas leads 300 Spartan warriors in a legendary last stand against the massive invading Persian army at the narrow pass of Thermopylae, buying Greece the time it needs to unite.",
    cast: ["Gerard Butler", "Lena Headey", "David Wenham"], runtime: 117, year: 2006,
    platforms: ["HBO Max"], genre: ["action"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "world-building"],
  },
  {
    id: "watchmen-movie", name: "Watchmen", type: "movie",
    plot: "In an alternate 1985 where costumed vigilantes are outlawed, the murder of one of their own draws a group of retired, morally compromised heroes back together to uncover a conspiracy larger than any of them.",
    cast: ["Jackie Earle Haley", "Patrick Wilson", "Malin Åkerman"], runtime: 162, year: 2009,
    platforms: ["HBO Max"], genre: ["action", "drama", "sci-fi"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "gravity", name: "Gravity", type: "movie",
    plot: "A medical engineer on her first shuttle mission and a veteran astronaut are stranded in orbit after debris destroys their spacecraft, and have to find a way back to Earth with rapidly depleting oxygen.",
    cast: ["Sandra Bullock", "George Clooney"], runtime: 91, year: 2013,
    platforms: ["HBO Max"], genre: ["sci-fi", "drama"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
];
