import type { RawTitle } from "../shape";

/** Batch 020 — thriller/mystery variety across Netflix, Prime Video, HBO Max. */
export const RAW: RawTitle[] = [
  {
    id: "the-night-agent", name: "The Night Agent", type: "show",
    plot: "A low-level FBI agent who mans a phone that never rings finally gets a call in the middle of the night, dragging him into a conspiracy that reaches into the White House itself.",
    cast: ["Gabriel Basso", "Luciane Buchanan", "Fola Evans-Akingbola"], seasons: 2, episodes: 20, year: 2023,
    platforms: ["Netflix"], genre: ["thriller", "action", "mystery"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "bodyguard", name: "Bodyguard", type: "show",
    plot: "A war veteran with PTSD is assigned to protect a home secretary whose politics he privately despises, and the tension between duty and conviction gets far more dangerous once an assassination plot emerges.",
    cast: ["Richard Madden", "Keeley Hawes", "Sophie Rundle"], seasons: 1, episodes: 6, year: 2018,
    platforms: ["Netflix"], genre: ["thriller", "action"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-serpent", name: "The Serpent", type: "show",
    plot: "Based on a true story, a Dutch diplomat and his partner spend years quietly gathering evidence to bring down a con man and serial killer who preyed on backpackers across Southeast Asia's hippie trail in the 1970s.",
    cast: ["Tahar Rahim", "Jenna Coleman", "Billy Howle"], seasons: 1, episodes: 8, year: 2021,
    platforms: ["Netflix"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "behind-her-eyes", name: "Behind Her Eyes", type: "show",
    plot: "A single mother starts an affair with her new psychiatrist boss while secretly befriending his fragile wife, and the tangled love triangle turns out to be hiding a secret far stranger than infidelity.",
    cast: ["Simona Brown", "Eve Hewson", "Tom Bateman"], seasons: 1, episodes: 6, year: 2021,
    platforms: ["Netflix"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "clickbait", name: "Clickbait", type: "show",
    plot: "A devoted husband and father vanishes, and a video surfaces showing him bound and beaten holding signs accusing him of terrible crimes — with a countdown to his death that racks up views the more it's shared.",
    cast: ["Adrian Grenier", "Zoe Kazan", "Betty Gabriel"], seasons: 1, episodes: 8, year: 2021,
    platforms: ["Netflix"], genre: ["thriller", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "safe-2018", name: "Safe", type: "show",
    plot: "A widowed surgeon's teenage daughter goes missing the same night a body turns up buried in his gated community's woods, and every neighbor he trusts turns out to be hiding something.",
    cast: ["Michael C. Hall", "Amanda Abbington", "Marc Warren"], seasons: 1, episodes: 8, year: 2018,
    platforms: ["Netflix"], genre: ["thriller", "mystery", "drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-stranger-2020", name: "The Stranger", type: "show",
    plot: "A stranger tells a happily married man a devastating secret about his wife, and the revelation sets off a chain of blackmail and buried secrets rippling through an entire English suburb.",
    cast: ["Richard Armitage", "Siobhan Finneran", "Jennifer Saunders"], seasons: 1, episodes: 8, year: 2020,
    platforms: ["Netflix"], genre: ["thriller", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "fool-me-once", name: "Fool Me Once", type: "show",
    plot: "A widow sets up a nanny cam after her husband's murder and is stunned to see him alive on the footage days later, unraveling a web of lies that reaches back into both of their pasts.",
    cast: ["Michelle Keegan", "Adeel Akhtar", "Richard Armitage"], seasons: 1, episodes: 8, year: 2024,
    platforms: ["Netflix"], genre: ["thriller", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-perfect-couple", name: "The Perfect Couple", type: "show",
    plot: "A glamorous Nantucket wedding weekend is thrown into chaos when a body washes up on the beach the morning of the ceremony, and every guest turns out to have a motive.",
    cast: ["Nicole Kidman", "Liev Schreiber", "Eve Hewson"], seasons: 1, episodes: 6, year: 2024,
    platforms: ["Netflix"], genre: ["mystery", "drama", "comedy"], mood: ["cerebral-mystery", "dark"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-peripheral", name: "The Peripheral", type: "show",
    plot: "A woman in near-future rural America discovers she can remotely inhabit a synthetic body decades in the future, and gets pulled into a deadly conflict spanning two different timelines.",
    cast: ["Chloë Grace Moretz", "Jack Reynor", "Gary Carr"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Prime Video"], genre: ["sci-fi", "thriller", "mystery"], mood: ["cerebral-ideas", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "homecoming-amazon", name: "Homecoming", type: "show",
    plot: "A caseworker at a facility helping soldiers transition back to civilian life is visited years later by a government auditor investigating why she abruptly left the job, and she can't remember why herself.",
    cast: ["Julia Roberts", "Stephan James", "Bobby Cannavale"], seasons: 2, episodes: 20, year: 2018,
    platforms: ["Prime Video"], genre: ["thriller", "mystery", "drama"], mood: ["cerebral-mystery", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "world-building"],
  },
  {
    id: "sneaky-pete", name: "Sneaky Pete", type: "show",
    plot: "A con artist fresh out of prison and on the run from a dangerous gangster assumes the identity of his old cellmate, hiding out with the man's estranged family, who have no idea he's not who he says he is.",
    cast: ["Giovanni Ribisi", "Marin Ireland", "Shane McRae"], seasons: 3, episodes: 30, year: 2015,
    platforms: ["Prime Video"], genre: ["thriller", "drama", "comedy"], mood: ["cerebral-mystery", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists", "characters"],
  },
  {
    id: "goliath", name: "Goliath", type: "show",
    plot: "A washed-up, alcoholic lawyer who used to be a top litigator takes on a wrongful-death case against the powerful law firm he co-founded and was pushed out of, risking everything for one last shot at redemption.",
    cast: ["Billy Bob Thornton", "William Hurt", "Nina Arianda"], seasons: 4, episodes: 32, year: 2016,
    platforms: ["Prime Video"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "plot-twists"],
  },
  {
    id: "the-outsider-hbo", name: "The Outsider", type: "show",
    plot: "A detective investigating the brutal murder of a child finds airtight evidence placing the same suspect in two places at once, forcing a skeptical private investigator to consider an explanation beyond reason.",
    cast: ["Ben Mendelsohn", "Cynthia Erivo", "Jason Bateman"], seasons: 1, episodes: 10, year: 2020,
    platforms: ["HBO Max"], genre: ["horror", "mystery", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "sharp-objects", name: "Sharp Objects", type: "show",
    plot: "A troubled reporter returns to her small Missouri hometown to cover the murders of two young girls, and the investigation drags her back into a childhood defined by her own mother's coldness and cruelty.",
    cast: ["Amy Adams", "Patricia Clarkson", "Eliza Scanlen"], seasons: 1, episodes: 8, year: 2018,
    platforms: ["HBO Max"], genre: ["mystery", "drama", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "mare-of-easttown", name: "Mare of Easttown", type: "show",
    plot: "A small-town Pennsylvania detective juggling her own family fallout investigates a local girl's murder, and the case slowly exposes just how many secrets an entire close-knit community has been keeping.",
    cast: ["Kate Winslet", "Jean Smart", "Evan Peters"], seasons: 1, episodes: 7, year: 2021,
    platforms: ["HBO Max"], genre: ["mystery", "drama", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-night-of", name: "The Night Of", type: "show",
    plot: "A young man's one impulsive night out ends with him waking up next to a murdered woman with no memory of what happened, and the show follows the slow, grinding machinery of the justice system that swallows him.",
    cast: ["Riz Ahmed", "John Turturro", "Bill Camp"], seasons: 1, episodes: 8, year: 2016,
    platforms: ["HBO Max"], genre: ["mystery", "drama", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-undoing", name: "The Undoing", type: "show",
    plot: "A successful Manhattan therapist's perfect life unravels when her husband becomes the prime suspect in a brutal murder, forcing her to question how well she actually knew the man she married.",
    cast: ["Nicole Kidman", "Hugh Grant", "Donald Sutherland"], seasons: 1, episodes: 6, year: 2020,
    platforms: ["HBO Max"], genre: ["mystery", "drama", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
];
