import type { RawTitle } from "../shape";

/** Batch 021 — more Hulu and Apple TV, the two platforms lagging most after 20 batches. */
export const RAW: RawTitle[] = [
  {
    id: "under-the-banner-of-heaven", name: "Under the Banner of Heaven", type: "show",
    plot: "A devout Mormon detective investigates the brutal murder of a young mother and her infant daughter, and the case forces him to confront violent extremism hiding inside his own faith community.",
    cast: ["Andrew Garfield", "Daisy Edgar-Jones", "Sam Worthington"], seasons: 1, episodes: 7, year: 2022,
    platforms: ["Hulu"], genre: ["drama", "mystery", "thriller"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "welcome-to-chippendales", name: "Welcome to Chippendales", type: "show",
    plot: "An Indian immigrant builds an empire out of the world's first male-stripper revue in 1980s LA, and his increasingly desperate need for control over the brand curdles into paranoia and violence.",
    cast: ["Kumail Nanjiani", "Murray Bartlett", "Annaleigh Ashford"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Hulu"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "candy-hulu", name: "Candy", type: "show",
    plot: "Based on a true case, a seemingly ordinary Texas housewife bludgeons her friend and fellow church member to death with an axe, and the investigation slowly reveals the tension simmering underneath their friendship.",
    cast: ["Jessica Biel", "Melanie Lynskey", "Pablo Schreiber"], seasons: 1, episodes: 5, year: 2022,
    platforms: ["Hulu"], genre: ["thriller", "drama", "mystery"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "pam-and-tommy", name: "Pam & Tommy", type: "show",
    plot: "A disgruntled contractor steals a private tape from Pamela Anderson and Tommy Lee's home, and its release becomes one of the first viral internet scandals, upending both of their lives and careers.",
    cast: ["Lily James", "Sebastian Stan", "Seth Rogen"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Hulu"], genre: ["drama", "comedy"], mood: ["dark", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "shrill", name: "Shrill", type: "show",
    plot: "A fat woman tired of being told her body is a problem stops apologizing for it, and starts pushing back against everyone in her life who's treated her weight as an excuse to disrespect her.",
    cast: ["Aidy Bryant", "Lolly Adefope", "Luka Jones"], seasons: 3, episodes: 22, year: 2019,
    platforms: ["Hulu"], genre: ["comedy", "drama"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "emotional-weight"],
  },
  {
    id: "dopesick", name: "Dopesick", type: "show",
    plot: "The opioid epidemic is traced from a small Virginia mining town to the boardrooms of Purdue Pharma, following the doctors, DEA agents, and patients caught in the machinery of a manufactured public health crisis.",
    cast: ["Michael Keaton", "Kaitlyn Dever", "Peter Sarsgaard"], seasons: 1, episodes: 8, year: 2021,
    platforms: ["Hulu"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "this-fool", name: "This Fool", type: "show",
    plot: "A South Central LA guy still living with his mom works at a gang-intervention nonprofit that just so happens to have taken on his own violent cousin as a client, testing every boundary he's supposed to keep professional.",
    cast: ["Chris Estrada", "Michael Imperioli", "Frankie Quiñones"], seasons: 2, episodes: 18, year: 2022,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "history-of-the-world-part-ii", name: "History of the World, Part II", type: "show",
    plot: "A sketch-comedy sequel decades in the making, jumping across history's biggest and weirdest moments — the Russian Revolution, the Wild West, Kublai Khan's court — for whatever joke fits.",
    cast: ["Mel Brooks", "Wanda Sykes", "Nick Kroll"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Hulu"], genre: ["comedy"], mood: ["funny-silly", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor", "world-building"],
  },
  {
    id: "no-exit-hulu", name: "No Exit", type: "movie",
    plot: "Stranded at a highway rest stop during a blizzard, a recovering addict discovers a kidnapped child locked in one of the other stranded travelers' vans, and has to figure out which stranger is guilty without giving herself away.",
    cast: ["Havana Rose Liu", "Danny Ramirez", "Dennis Haysbert"], runtime: 96, year: 2022,
    platforms: ["Hulu"], genre: ["thriller"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "physical-apple", name: "Physical", type: "show",
    plot: "A quietly miserable 1980s housewife discovers aerobics as an unlikely outlet for her rage, and builds a fitness-video empire while narrating her own brutal, unfiltered self-loathing the whole way.",
    cast: ["Rose Byrne", "Rory Scovel", "Della Saba"], seasons: 3, episodes: 30, year: 2021,
    platforms: ["Apple TV"], genre: ["comedy", "drama"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "emotional-weight"],
  },
  {
    id: "loot-apple", name: "Loot", type: "show",
    plot: "A woman discovers her billionaire husband's affair on the day of their divorce and walks away with a $87 billion settlement, and has to figure out what to actually do with her life — and the money — afterward.",
    cast: ["Maya Rudolph", "Michael Park", "Joel Kim Booster"], seasons: 2, episodes: 20, year: 2022,
    platforms: ["Apple TV"], genre: ["comedy"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["humor", "characters"],
  },
  {
    id: "dear-edward", name: "Dear Edward", type: "show",
    plot: "A twelve-year-old boy is the sole survivor of a plane crash that killed 191 other people, including his own family, and the show follows him and the crash's other grieving relatives trying to rebuild something out of the wreckage.",
    cast: ["Colin O'Brien", "Taylor Schilling", "Connie Britton"], seasons: 1, episodes: 10, year: 2023,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "hijack", name: "Hijack", type: "show",
    plot: "A skilled corporate negotiator uses every trick he knows to keep passengers calm and buy time when his London-bound flight is hijacked mid-air, racing to figure out what the hijackers actually want before it's too late.",
    cast: ["Idris Elba", "Archie Panjabi", "Neil Maskell"], seasons: 1, episodes: 7, year: 2023,
    platforms: ["Apple TV"], genre: ["thriller", "action"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "time-bandits-apple", name: "Time Bandits", type: "show",
    plot: "An eleven-year-old is swept up by a band of scheming time-traveling thieves using a stolen map of history's holes to loot different eras, and reluctantly becomes part of their chaotic crew.",
    cast: ["Lisa Kudrow", "Kal-El Tuck", "Tadhg Murphy"], seasons: 1, episodes: 10, year: 2024,
    platforms: ["Apple TV"], genre: ["fantasy", "comedy", "action"], mood: ["funny-witty", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building", "humor"],
  },
];
