import type { RawTitle } from "../shape";

/** Batch 022 — more movies across platforms, mixed genres. */
export const RAW: RawTitle[] = [
  {
    id: "the-holdovers", name: "The Holdovers", type: "movie",
    plot: "A cranky boarding-school teacher is stuck supervising the handful of students with nowhere to go over Christmas break, and slowly forms an unlikely bond with the one troubled kid he actually resents the most.",
    cast: ["Paul Giamatti", "Da'Vine Joy Randolph", "Dominic Sessa"], runtime: 133, year: 2023,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "the-farewell", name: "The Farewell", type: "movie",
    plot: "A Chinese-American woman returns to China to say goodbye to her dying grandmother, who doesn't know she's terminally ill — the family has decided not to tell her, and stages a fake wedding as an excuse for everyone to gather.",
    cast: ["Awkwafina", "Shuzhen Zhao", "X Mayo"], runtime: 100, year: 2019,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "minari", name: "Minari", type: "movie",
    plot: "A Korean-American family relocates to a small Arkansas farm chasing the father's dream of growing Korean produce, and the move puts real strain on a marriage already stretched thin.",
    cast: ["Steven Yeun", "Yeri Han", "Alan S. Kim"], runtime: 115, year: 2020,
    platforms: ["Prime Video"], genre: ["drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-lost-daughter", name: "The Lost Daughter", type: "movie",
    plot: "A solo vacation on a Greek island brings up unresolved feelings from a college professor's past as a young mother, unsettled by watching another young family on the beach struggle with the same pressures she once did.",
    cast: ["Olivia Colman", "Dakota Johnson", "Jessie Buckley"], runtime: 122, year: 2021,
    platforms: ["Netflix"], genre: ["drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "malcolm-and-marie", name: "Malcolm & Marie", type: "movie",
    plot: "A filmmaker and his girlfriend return home from his triumphant movie premiere, and a single, unresolved slight spirals into an all-night reckoning with everything unspoken in their relationship.",
    cast: ["Zendaya", "John David Washington"], runtime: 106, year: 2021,
    platforms: ["Netflix"], genre: ["drama", "romance"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "moxie", name: "Moxie", type: "movie",
    plot: "A shy high schooler inspired by her mother's Riot Grrrl past anonymously publishes a feminist zine calling out her school's sexist double standards, and it snowballs into a movement she never expected to lead.",
    cast: ["Hadley Robinson", "Patrick Schwarzenegger", "Amy Poehler"], runtime: 111, year: 2021,
    platforms: ["Netflix"], genre: ["comedy", "drama"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "spiderhead", name: "Spiderhead", type: "movie",
    plot: "Inmates at an experimental prison facility volunteer for cutting-edge mood-altering drug trials in exchange for reduced sentences, run by a charismatic administrator whose motives turn out to be far darker.",
    cast: ["Chris Hemsworth", "Miles Teller", "Jurnee Smollett"], runtime: 106, year: 2022,
    platforms: ["Netflix"], genre: ["sci-fi", "thriller"], mood: ["dark", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
];
