import type { RawTitle } from "../shape";

/** Batch 023 — more Disney+ Hotstar (Pixar/Disney classics) and Prime Video (Amazon originals). */
export const RAW: RawTitle[] = [
  {
    id: "toy-story-3", name: "Toy Story 3", type: "movie",
    plot: "Donated to a daycare after their kid grows up and leaves for college, Woody and the gang have to escape a toy-tyrant's regime and figure out where they actually belong now.",
    cast: ["Tom Hanks", "Tim Allen", "Joan Cusack"], runtime: 103, year: 2010,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "toy-story-4", name: "Toy Story 4", type: "movie",
    plot: "Woody sets off on a road trip to rescue a new, reluctant handmade toy who keeps trying to throw himself away, and along the way runs into an old flame who's built a whole new life without a kid of her own.",
    cast: ["Tom Hanks", "Tim Allen", "Annie Potts"], runtime: 100, year: 2019,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["feel-good", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "cars", name: "Cars", type: "movie",
    plot: "A hotshot rookie race car gets stranded in a forgotten Route 66 town on his way to a championship race, and the quirky locals end up teaching him what actually matters more than winning.",
    cast: ["Owen Wilson", "Paul Newman", "Bonnie Hunt"], runtime: 117, year: 2006,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "action"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "brave", name: "Brave", type: "movie",
    plot: "A headstrong Scottish princess who'd rather shoot arrows than marry defies an ancient custom and makes a reckless wish that turns her own mother into a bear, forcing them to repair their relationship to break the spell.",
    cast: ["Kelly Macdonald", "Emma Thompson", "Billy Connolly"], runtime: 93, year: 2012,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "action"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "onward", name: "Onward", type: "movie",
    plot: "Two teenage elf brothers in a suburban fantasy world use a rare bit of leftover magic to try to bring their late father back for one day, but the spell only manages to resurrect his legs.",
    cast: ["Tom Holland", "Chris Pratt", "Julia Louis-Dreyfus"], runtime: 102, year: 2020,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy", "action"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "frozen", name: "Frozen", type: "movie",
    plot: "When her cursed ice powers accidentally trap her kingdom in eternal winter, a princess flees into the mountains, and her sister sets off with a mountain man and a snowman to bring her home and undo the curse.",
    cast: ["Kristen Bell", "Idina Menzel", "Jonathan Groff"], runtime: 102, year: 2013,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "tangled", name: "Tangled", type: "movie",
    plot: "A princess locked in a tower her whole life for the magic in her enormously long hair strikes a deal with a wanted thief to finally see the outside world on her eighteenth birthday.",
    cast: ["Mandy Moore", "Zachary Levi", "Donna Murphy"], runtime: 100, year: 2010,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy", "romance"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "aladdin-2019", name: "Aladdin", type: "movie",
    plot: "A live-action retelling of the street urchin who finds a magic lamp and its genie, and uses his wishes to pose as a prince and win the heart of the sultan's daughter.",
    cast: ["Mena Massoud", "Naomi Scott", "Will Smith"], runtime: 128, year: 2019,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "romance", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "beauty-and-the-beast-2017", name: "Beauty and the Beast", type: "movie",
    plot: "A live-action retelling of a bookish young woman who trades her freedom for her father's, and slowly falls for the cursed prince holding her prisoner in his enchanted castle.",
    cast: ["Emma Watson", "Dan Stevens", "Luke Evans"], runtime: 129, year: 2017,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "romance"], mood: ["feel-good", "light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "mulan-2020", name: "Mulan", type: "movie",
    plot: "A live-action retelling of a young woman who disguises herself as a man to take her ailing father's place in the emperor's army, hiding her identity while proving herself one of its best soldiers.",
    cast: ["Yifei Liu", "Donnie Yen", "Jason Scott Lee"], runtime: 115, year: 2020,
    platforms: ["Disney+ Hotstar"], genre: ["action", "drama"], mood: ["intense", "feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "cinderella-2021", name: "Cinderella", type: "movie",
    plot: "A musical retelling where an aspiring dress designer with a dream of starting her own business is held back by her cruel stepfamily, until a fairy godmother gives her a shot at the royal ball.",
    cast: ["Camila Cabello", "Nicholas Galitzine", "Billy Porter"], runtime: 113, year: 2021,
    platforms: ["Prime Video"], genre: ["fantasy", "comedy", "romance"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "humor"],
  },
  {
    id: "chemical-hearts", name: "Chemical Hearts", type: "movie",
    plot: "A high school senior falls for a mysterious new classmate who walks with a cane and carries a grief she won't explain, and their relationship becomes his first real education in heartbreak.",
    cast: ["Austin Abrams", "Lili Reinhart"], runtime: 93, year: 2020,
    platforms: ["Prime Video"], genre: ["romance", "drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "sylvies-love", name: "Sylvie's Love", type: "movie",
    plot: "A record-store owner's daughter and a saxophonist fall in love over one 1957 summer in Harlem, and reunite years later after their separate paths and ambitions pulled them apart.",
    cast: ["Tessa Thompson", "Nnamdi Asomugha", "Aja Naomi King"], runtime: 114, year: 2020,
    platforms: ["Prime Video"], genre: ["romance", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "uncle-frank", name: "Uncle Frank", type: "movie",
    plot: "A young woman road-tripping to her grandfather's funeral with her closeted gay uncle gets pulled into his complicated history with the family that never accepted him.",
    cast: ["Paul Bettany", "Sophia Lillis", "Peter Macdissi"], runtime: 95, year: 2020,
    platforms: ["Prime Video"], genre: ["comedy", "drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "im-your-woman", name: "I'm Your Woman", type: "movie",
    plot: "A housewife with no idea what her criminal husband actually does for a living is forced into hiding with her infant son after he suddenly disappears, and has to learn to survive entirely on her own.",
    cast: ["Rachel Brosnahan", "Arinzé Kene"], runtime: 120, year: 2020,
    platforms: ["Prime Video"], genre: ["thriller", "drama"], mood: ["intense", "dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "plot-twists"],
  },
];
