import type { RawTitle } from "../shape";

/** Batch 024 — prestige limited series / true-crime dramas across platforms. */
export const RAW: RawTitle[] = [
  {
    id: "olive-kitteridge", name: "Olive Kitteridge", type: "show",
    plot: "A blunt, difficult small-town Maine schoolteacher's prickly exterior slowly reveals decades of buried grief and love, told across a series of interconnected episodes in the lives of her neighbors.",
    cast: ["Frances McDormand", "Richard Jenkins", "Bill Murray"], seasons: 1, episodes: 4, year: 2014,
    platforms: ["HBO Max"], genre: ["drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "maid", name: "Maid", type: "show",
    plot: "A young single mother flees an emotionally abusive relationship with nothing but $18 and her toddler, and has to navigate a maze of broken social services while cleaning houses to survive.",
    cast: ["Margaret Qualley", "Nick Robinson", "Andie MacDowell"], seasons: 1, episodes: 10, year: 2021,
    platforms: ["Netflix"], genre: ["drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "inventing-anna", name: "Inventing Anna", type: "show",
    plot: "A journalist investigates the true story of a fake German heiress who conned New York's elite social and financial scene out of hundreds of thousands of dollars before finally getting caught.",
    cast: ["Julia Garner", "Anna Chlumsky", "Arian Moayed"], seasons: 1, episodes: 9, year: 2022,
    platforms: ["Netflix"], genre: ["drama", "thriller"], mood: ["cerebral-mystery", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "the-dropout", name: "The Dropout", type: "show",
    plot: "A Stanford dropout convinces Silicon Valley she's invented a revolutionary blood-testing device, building a $9 billion company on a technology that never actually worked as promised.",
    cast: ["Amanda Seyfried", "Naveen Andrews", "William H. Macy"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Hulu"], genre: ["drama"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "wecrashed", name: "WeCrashed", type: "show",
    plot: "A charismatic, wildly overconfident founder and his wife turn a co-working startup into a $47 billion unicorn built almost entirely on his own personal mythology, right up until it collapses overnight.",
    cast: ["Jared Leto", "Anne Hathaway", "Kyle Marvin"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Apple TV"], genre: ["drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "black-bird", name: "Black Bird", type: "show",
    plot: "A charming small-time drug dealer facing a decade in prison is offered a shot at freedom if he can get a suspected serial killer in a maximum-security psychiatric unit to confess.",
    cast: ["Taron Egerton", "Paul Walter Hauser", "Ray Liotta"], seasons: 1, episodes: 6, year: 2022,
    platforms: ["Apple TV"], genre: ["thriller", "drama", "mystery"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "american-crime-story-the-people-v-oj-simpson", name: "American Crime Story: The People v. O.J. Simpson", type: "show",
    plot: "The murder trial of O.J. Simpson is retold from inside both the prosecution and defense camps, tracing how race, celebrity, and media spectacle turned it into the trial of the century.",
    cast: ["Sarah Paulson", "Sterling K. Brown", "Cuba Gooding Jr."], seasons: 1, episodes: 10, year: 2016,
    platforms: ["Hulu"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "american-crime-story-impeachment", name: "American Crime Story: Impeachment", type: "show",
    plot: "The Clinton impeachment scandal is retold centering Monica Lewinsky, Linda Tripp, and Paula Jones, reframing a story the media originally told almost entirely from the men's point of view.",
    cast: ["Beanie Feldstein", "Sarah Paulson", "Clive Owen"], seasons: 1, episodes: 10, year: 2021,
    platforms: ["Hulu"], genre: ["drama"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "when-they-see-us", name: "When They See Us", type: "show",
    plot: "Five Black and Latino teenagers are wrongfully convicted of a brutal Central Park assault, tracing how a rushed, racially charged investigation stole years of their lives before they were finally exonerated.",
    cast: ["Jharrel Jerome", "Niecy Nash", "Michael K. Williams"], seasons: 1, episodes: 4, year: 2019,
    platforms: ["Netflix"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "unbelievable", name: "Unbelievable", type: "show",
    plot: "A teenage rape survivor is charged with lying about her assault by disbelieving police, while two female detectives in another state, working the same case years later, prove she was telling the truth all along.",
    cast: ["Kaitlyn Dever", "Merritt Wever", "Toni Collette"], seasons: 1, episodes: 8, year: 2019,
    platforms: ["Netflix"], genre: ["drama", "mystery"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "plot-twists"],
  },
];
