import type { RawTitle } from "../shape";

/** Batch 025 — more anime (Crunchyroll) and family/kids content (Disney+ Hotstar, Netflix). */
export const RAW: RawTitle[] = [
  {
    id: "cardcaptor-sakura", name: "Cardcaptor Sakura", type: "anime",
    plot: "A cheerful fourth-grader accidentally releases a set of magical cards scattered across her town, and has to capture them all back before their chaotic powers cause real damage.",
    cast: ["Sakura Tange", "Junko Iwao"], seasons: 3, episodes: 70, year: 1998,
    platforms: ["Crunchyroll"], genre: ["fantasy", "comedy"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "digimon-adventure", name: "Digimon Adventure", type: "anime",
    plot: "Seven kids at summer camp are pulled into a digital world and each partnered with a monster that can digivolve into stronger forms, fighting to save both worlds from digital chaos.",
    cast: ["Colleen O'Shaughnessey", "Joshua Seth"], seasons: 1, episodes: 54, year: 1999,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "comedy"], mood: ["feel-good", "intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["long-runner"], love: ["characters", "world-building"],
  },
  {
    id: "sword-art-online", name: "Sword Art Online", type: "anime",
    plot: "Ten thousand players are trapped inside a virtual-reality MMO with no way to log out, and dying in the game means dying for real, leaving one skilled swordsman racing to clear the game and free everyone.",
    cast: ["Yoshitsugu Matsuoka", "Haruka Tomatsu"], seasons: 4, episodes: 96, year: 2012,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "romance"], mood: ["intense", "cerebral-ideas"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["sci-fi-future"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["long-runner"], love: ["world-building", "plot-twists"],
  },
  {
    id: "chihayafuru", name: "Chihayafuru", type: "anime",
    plot: "A girl obsessed with a classical Japanese card game recruits her reluctant childhood friends to form a competitive karuta club, chasing a national championship none of them originally cared about.",
    cast: ["Asami Seto", "Ayane Sakura"], seasons: 3, episodes: 75, year: 2011,
    platforms: ["Crunchyroll"], genre: ["drama", "romance"], mood: ["intense", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["multi-season"], love: ["characters", "emotional-weight"],
  },
  {
    id: "blue-exorcist", name: "Blue Exorcist", type: "anime",
    plot: "A teenage boy discovers he's the biological son of Satan when a demon attack forces him to reveal his hidden powers, and enrolls at an academy to train as an exorcist so he can fight his own father.",
    cast: ["Nobuhiko Okamoto", "Jun Fukuyama"], seasons: 2, episodes: 37, year: 2011,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action"], mood: ["intense", "funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters", "world-building"],
  },
  {
    id: "fate-zero", name: "Fate/Zero", type: "anime",
    plot: "Seven mages summon legendary heroic spirits from history and myth to fight to the death in a hidden war for a wish-granting grail, each with their own conflicting reasons for wanting to win.",
    cast: ["Yuichi Nakamura", "Ryotaro Okiayu"], seasons: 2, episodes: 25, year: 2011,
    platforms: ["Crunchyroll"], genre: ["fantasy", "action", "drama"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "angel-beats", name: "Angel Beats!", type: "anime",
    plot: "A boy wakes up with no memory in a strange afterlife high school and joins a rebel group fighting against a mysterious girl who enforces the rules of the world between them, before finding out why any of them are really there.",
    cast: ["Hiroshi Kamiya", "Marina Inoue"], seasons: 1, episodes: 13, year: 2010,
    platforms: ["Crunchyroll"], genre: ["fantasy", "drama", "comedy"], mood: ["dark", "feel-good"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["fantasy-world"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "the-princess-and-the-frog", name: "The Princess and the Frog", type: "movie",
    plot: "A hardworking young waitress in 1920s New Orleans kisses a prince who's been turned into a frog, but instead of breaking the spell, it turns her into a frog too, and the two set off through the bayou looking for a cure.",
    cast: ["Anika Noni Rose", "Bruno Campos", "Keith David"], runtime: 97, year: 2009,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy", "romance"], mood: ["feel-good", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "pocahontas", name: "Pocahontas", type: "movie",
    plot: "The daughter of a Powhatan chief falls for an English settler as tensions rise between her tribe and the newly arrived colonists, and has to try to keep the peace before it turns to war.",
    cast: ["Irene Bedard", "Mel Gibson", "David Ogden Stiers"], runtime: 81, year: 1995,
    platforms: ["Disney+ Hotstar"], genre: ["romance", "drama"], mood: ["feel-good", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "hercules-1997", name: "Hercules", type: "movie",
    plot: "The god-born son of Zeus is stripped of his immortality as a baby and raised on Earth, and has to become a true hero to earn his place back on Mount Olympus.",
    cast: ["Tate Donovan", "Danny DeVito", "James Woods"], runtime: 93, year: 1997,
    platforms: ["Disney+ Hotstar"], genre: ["fantasy", "comedy", "action"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["humor", "emotional-weight"],
  },
  {
    id: "the-emperors-new-groove", name: "The Emperor's New Groove", type: "movie",
    plot: "A vain, self-centered emperor is turned into a llama by his own scheming advisor, and has to team up with the one peasant whose village he was about to bulldoze to get back to the palace and reverse the curse.",
    cast: ["David Spade", "John Goodman", "Eartha Kitt"], runtime: 78, year: 2000,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "fantasy"], mood: ["funny-silly", "light"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "lilo-and-stitch", name: "Lilo & Stitch", type: "movie",
    plot: "A lonely Hawaiian girl adopts what she thinks is a stray dog, but it's actually a genetically engineered alien fugitive on the run, and their unlikely bond teaches him what family really means.",
    cast: ["Daveigh Chase", "Chris Sanders", "Tia Carrere"], runtime: 85, year: 2002,
    platforms: ["Disney+ Hotstar"], genre: ["comedy", "sci-fi", "drama"], mood: ["feel-good", "funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
];
