import type { RawTitle } from "../shape";

/** Batch 026 — HBO Max/WB classic films, plus a few more Netflix originals. */
export const RAW: RawTitle[] = [
  {
    id: "goodfellas", name: "Goodfellas", type: "movie",
    plot: "A small-time Brooklyn kid rises through the ranks of the mob over three decades, chasing the glamour and easy money of the life right up until it all starts to collapse around him.",
    cast: ["Ray Liotta", "Robert De Niro", "Joe Pesci"], runtime: 145, year: 1990,
    platforms: ["HBO Max"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "full-metal-jacket", name: "Full Metal Jacket", type: "movie",
    plot: "A group of Marine recruits endure a brutal Parris Island boot camp before shipping out to the chaos of the Vietnam War, split into two halves that show the making and unmaking of a soldier.",
    cast: ["Matthew Modine", "R. Lee Ermey", "Vincent D'Onofrio"], runtime: 116, year: 1987,
    platforms: ["HBO Max"], genre: ["drama", "action"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "a-clockwork-orange", name: "A Clockwork Orange", type: "movie",
    plot: "In a dystopian near-future Britain, a violent young gang leader is captured and subjected to an experimental behavioral treatment meant to strip him of his capacity for violence — and everything else along with it.",
    cast: ["Malcolm McDowell", "Patrick Magee", "Michael Bates"], runtime: 136, year: 1971,
    platforms: ["HBO Max"], genre: ["drama", "sci-fi"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building", "characters"],
  },
  {
    id: "the-shining", name: "The Shining", type: "movie",
    plot: "A writer takes a winter caretaker job at a remote, isolated hotel with his wife and psychic young son, and the hotel's malevolent influence slowly pushes him toward madness and murder.",
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd"], runtime: 146, year: 1980,
    platforms: ["HBO Max"], genre: ["horror"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "world-building"],
  },
  {
    id: "se7en", name: "Se7en", type: "movie",
    plot: "Two homicide detectives, one about to retire and one brand new to the job, hunt a serial killer staging each murder around one of the seven deadly sins.",
    cast: ["Brad Pitt", "Morgan Freeman", "Kevin Spacey"], runtime: 127, year: 1995,
    platforms: ["HBO Max"], genre: ["thriller", "mystery", "horror"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "training-day", name: "Training Day", type: "movie",
    plot: "A rookie LAPD narcotics officer's first day shadowing a corrupt, charismatic veteran detective spirals into an increasingly dangerous test of exactly how far he's willing to bend the rules.",
    cast: ["Denzel Washington", "Ethan Hawke"], runtime: 122, year: 2001,
    platforms: ["HBO Max"], genre: ["thriller", "drama", "action"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters", "plot-twists"],
  },
  {
    id: "the-departed", name: "The Departed", type: "movie",
    plot: "A Boston cop goes undercover in the Irish mob while the mob simultaneously plants their own mole inside the police department, and both moles race to uncover each other before they're exposed themselves.",
    cast: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"], runtime: 151, year: 2006,
    platforms: ["HBO Max"], genre: ["thriller", "drama"], mood: ["dark", "intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "the-two-popes", name: "The Two Popes", type: "movie",
    plot: "A conservative Pope Benedict and a reform-minded Cardinal Bergoglio, doctrinal opposites, meet for a series of private conversations that reveal far more common ground than either expected.",
    cast: ["Anthony Hopkins", "Jonathan Pryce"], runtime: 125, year: 2019,
    platforms: ["Netflix"], genre: ["drama"], mood: ["cerebral-ideas", "feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "mudbound", name: "Mudbound", type: "movie",
    plot: "Two Mississippi families, one white and one Black, are bound together by the same unforgiving farmland after WWII, as their sons come home from the war forever changed by what they saw overseas.",
    cast: ["Carey Mulligan", "Jason Mitchell", "Garrett Hedlund"], runtime: 134, year: 2017,
    platforms: ["Netflix"], genre: ["drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight", "characters"],
  },
  {
    id: "el-camino-a-breaking-bad-movie", name: "El Camino: A Breaking Bad Movie", type: "movie",
    plot: "Picking up right where the Breaking Bad finale left off, Jesse Pinkman is finally free and has to outrun his past to find some version of a future for himself.",
    cast: ["Aaron Paul", "Jesse Plemons", "Charles Baker"], runtime: 122, year: 2019,
    platforms: ["Netflix"], genre: ["drama", "thriller"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters", "emotional-weight"],
  },
  {
    id: "athlete-a", name: "Athlete A", type: "movie",
    plot: "A team of investigative journalists breaks the story of USA Gymnastics doctor Larry Nassar's decades of abuse, working alongside the gymnasts who first came forward.",
    cast: ["Maggie Nichols", "Rachael Denhollander", "Jessica Howard"], runtime: 103, year: 2020,
    platforms: ["Netflix"], genre: ["documentary"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
];
