import type { RawTitle } from "../shape";

/** Batch 035 — moderate batch, Apple TV / Hulu / Prime Video / more Crunchyroll. */
export const RAW: RawTitle[] = [
  {
    id: "the-instigators", name: "The Instigators", type: "movie",
    plot: "A heist to rob a corrupt Boston mayor goes sideways almost immediately, and two mismatched criminals have to survive both the police and the crime boss they were supposed to be working for.",
    cast: ["Matt Damon", "Casey Affleck", "Hong Chau"], runtime: 101, year: 2024,
    platforms: ["Apple TV"], genre: ["action", "comedy", "thriller"], mood: ["funny-witty", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["humor", "plot-twists"],
  },
  {
    id: "suspicion", name: "Suspicion", type: "show",
    plot: "The teenage son of a British ambassador is kidnapped from a New York hotel in a scheme involving four seemingly unconnected British nationals, and every one of them insists they've been framed.",
    cast: ["Uma Thurman", "Kunal Nayyar", "Georgina Campbell"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Apple TV"], genre: ["thriller", "mystery"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "roar-apple", name: "Roar", type: "show",
    plot: "An anthology of loosely fable-like stories about women's lives, each one told with a surreal or fantastical twist — a woman literally eaten by a duck, a woman who keeps her husband on a shelf.",
    cast: ["Nicole Kidman", "Issa Rae", "Merritt Wever"], seasons: 1, episodes: 8, year: 2022,
    platforms: ["Apple TV"], genre: ["drama", "comedy", "fantasy"], mood: ["cerebral-ideas", "dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "emotional-weight"],
  },
  {
    id: "life-and-beth", name: "Life & Beth", type: "show",
    plot: "A wine importer whose life looks put-together from the outside has a public breakdown after her mother's sudden death, and starts questioning every choice that got her to where she is.",
    cast: ["Amy Schumer", "Michael Cera", "Susannah Flood"], seasons: 2, episodes: 16, year: 2022,
    platforms: ["Hulu"], genre: ["comedy", "drama"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight", "characters"],
  },
  {
    id: "deli-boys", name: "Deli Boys", type: "show",
    plot: "Two spoiled Pakistani-American brothers who never worked a day in their lives inherit their late father's business, only to discover the convenience-store empire was actually a front for a drug operation.",
    cast: ["Asif Ali", "Saagar Shaikh", "Poorna Jagannathan"], seasons: 1, episodes: 8, year: 2025,
    platforms: ["Hulu"], genre: ["comedy", "action"], mood: ["funny-silly", "intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["humor", "characters"],
  },
  {
    id: "the-rig", name: "The Rig", type: "show",
    plot: "The crew of a remote North Sea oil rig is cut off from the mainland by a mysterious fog, and strange happenings on board force them to confront what's really out there — and what they've been drilling into.",
    cast: ["Iain Glen", "Martin Compston", "Emily Hampshire"], seasons: 2, episodes: 12, year: 2023,
    platforms: ["Prime Video"], genre: ["thriller", "sci-fi", "mystery"], mood: ["dark", "cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["ongoing"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building", "plot-twists"],
  },
  {
    id: "wilderness-prime", name: "Wilderness", type: "show",
    plot: "A woman discovers her husband is having an affair and plots his murder on a dream American road trip, dragging both of them across national parks while she decides exactly how far she's willing to go.",
    cast: ["Jenna Coleman", "Oliver Jackson-Cohen", "Ashley Benson"], seasons: 1, episodes: 6, year: 2023,
    platforms: ["Prime Video"], genre: ["thriller", "drama"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "culprits", name: "Culprits", type: "show",
    plot: "Years after pulling off a massive, meticulously planned heist and going straight, the surviving members of the crew are being hunted down one by one by someone who seems to know exactly who they used to be.",
    cast: ["Nathan Stewart-Jarrett", "Eddie Izzard", "Gemma Arterton"], seasons: 1, episodes: 8, year: 2023,
    platforms: ["Prime Video"], genre: ["thriller", "mystery"], mood: ["intense", "cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
  {
    id: "vampire-knight", name: "Vampire Knight", type: "anime",
    plot: "A girl saved as a child by a pureblood vampire grows up to become a school guardian keeping the peace between the human and vampire classes at a school that hides its night-class students' true nature.",
    cast: ["Mamoru Miyano", "Norio Wakamoto"], seasons: 1, episodes: 26, year: 2008,
    platforms: ["Crunchyroll"], genre: ["fantasy", "romance"], mood: ["dark", "feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["short-binge"], love: ["emotional-weight", "world-building"],
  },
  {
    id: "elfen-lied", name: "Elfen Lied", type: "anime",
    plot: "A mutant girl with lethal invisible arms escapes a government research facility and loses her memory in the process, and the two college students who find her have no idea how dangerous she actually is.",
    cast: ["Sanae Kobayashi", "Mamiko Noto"], seasons: 1, episodes: 13, year: 2004,
    platforms: ["Crunchyroll"], genre: ["horror", "drama", "action"], mood: ["dark", "intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence", "heavy-themes"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight", "plot-twists"],
  },
  {
    id: "steins-gate-0", name: "Steins;Gate 0", type: "anime",
    plot: "In a timeline where the hero gave up on saving his friend, a broken, guilt-ridden scientist tries to move on from time travel entirely, until a new discovery threatens to drag him back into the same nightmare.",
    cast: ["Mamoru Miyano", "Kana Hanazawa"], seasons: 1, episodes: 23, year: 2018,
    platforms: ["Crunchyroll"], genre: ["sci-fi", "drama", "mystery"], mood: ["dark", "cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["sci-fi-future"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists", "emotional-weight"],
  },
  {
    id: "highschool-of-the-dead", name: "Highschool of the Dead", type: "anime",
    plot: "A small group of high schoolers bands together to survive a sudden zombie outbreak, fighting their way across a city in collapse while trying to track down their own families.",
    cast: ["Marina Inoue", "Yuki Kaida"], seasons: 1, episodes: 12, year: 2010,
    platforms: ["Crunchyroll"], genre: ["horror", "action"], mood: ["intense", "dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], sub_dub: ["sub-available", "dub-available"], completion: ["completed"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists", "characters"],
  },
];
