import type { RawTitle } from "../shape";

/** Batch 036 — multi-language expansion: real breadth across Kollywood/Tamil (previously zero
 * titles), Tollywood/Telugu, Bollywood/Hindi, Korean, Japanese live-action, and Spanish-language
 * (Spain + Latin America). Plot/cast/year/runtime sourced from TMDB (see
 * scripts/import-tmdb-titles.ts); platforms and every taxonomy tag assigned by hand — TMDB has
 * neither. */
export const RAW: RawTitle[] = [
  {
    id: "vikram-2022", name: "Vikram", type: "movie",
    plot: "Amar is assigned to investigate a case of serial killings. When Amar investigates the case, he realizes it is not what it seems to be and following down this path will lead to nothing but war between everyone involved.",
    cast: ["Kamal Haasan","Fahadh Faasil","Vijay Sethupathi","Suriya","Narain"], runtime: 174, year: 2022,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","thriller"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "soorarai-pottru", name: "Soorarai Pottru", type: "movie",
    plot: "Nedumaaran Rajangam \"Maara\" sets out to make the common man fly and in the process takes on the world's most capital intensive industry and several enemies who stand in his way.",
    cast: ["Suriya","Aparna Balamurali","Paresh Rawal","Mohan Babu","Urvashi"], runtime: 149, year: 2020,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama"], mood: ["intense","feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "asuran", name: "Asuran", type: "movie",
    plot: "A family from the underprivileged class is on the run after the teenaged son kills a rich man from the upper caste. Can the pacifist father be able to save his hot-blooded son?",
    cast: ["Dhanush","Manju Warrier","Ken Karunaas","Teejay","Pasupathy"], runtime: 141, year: 2019,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","thriller","action"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "kaithi", name: "Kaithi", type: "movie",
    plot: "Dilli, a convicted criminal, is out on parole to meet his daughter. However, a drug bust sets him off on a mission to save the life of police officers.",
    cast: ["Karthi","Narain","Arjun Das","Harish Uthaman","George Mariyan"], runtime: 147, year: 2019,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","thriller"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "96", name: "96", type: "movie",
    plot: "Ram is a photographer and nature lover who travels all around India capturing moments. On a chance visit to his hometown Tanjavur, he goes into his school and begins to walk down memory lane to 1994 when he was a student harboring feelings for his classmate Janu.",
    cast: ["Vijay Sethupathi","Trisha Krishnan","Aditya Baskar","Gouri G Kishan","Devadarshini"], runtime: 159, year: 2018,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["romance","drama"], mood: ["feel-good","dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "super-deluxe", name: "Super Deluxe", type: "movie",
    plot: "An unfaithful newly-wed wife, an estranged parent, a priest and an angry son suddenly find themselves in the most unexpected predicaments, each poised to experience their destiny, all on one fateful day.",
    cast: ["Vijay Sethupathi","Fahadh Faasil","Samantha Ruth Prabhu","Ramya Krishnan","Mysskin"], runtime: 176, year: 2019,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","comedy","mystery"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "jai-bhim", name: "Jai Bhim", type: "movie",
    plot: "A pregnant woman from a primitive tribal community, searches desperately for her husband, who is missing from police custody. So as to find her husband and seek justice for them, as their voice, a High Court advocate rises in support. Will their battle for justice succeed?",
    cast: ["Suriya","Lijomol Jose","Baby Joshika Maya","Manikandan","Rajisha Vijayan"], runtime: 164, year: 2021,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","thriller"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "vada-chennai", name: "Vada Chennai", type: "movie",
    plot: "Anbu, a young carrom player in North Chennai becomes inadvertently involved in an ongoing conflict between two local gangsters.",
    cast: ["Dhanush","Andrea Jeremiah","Ameer","Aishwarya Rajesh","Samuthirakani"], runtime: 166, year: 2018,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["thriller","drama","action"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","plot-twists"],
  },
  {
    id: "pushpa-the-rise", name: "Pushpa: The Rise", type: "movie",
    plot: "As Pushpa, a labourer, rises in the world of red sandalwood smuggling, he ends up making many enemies. However, violence ensues when the police try to topple his illegal business.",
    cast: ["Allu Arjun","Fahadh Faasil","Rashmika Mandanna","Jagadeesh Bandari","Sunil Varma"], runtime: 179, year: 2021,
    platforms: ["Prime Video"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["action","drama"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","plot-twists"],
  },
  {
    id: "baahubali-beginning", name: "Baahubali: The Beginning", type: "movie",
    plot: "The young Shivudu is left as a foundling in a small village by his mother. By the time he’s grown up, it has become apparent that he possesses exceptional gifts. He meets the beautiful warrior princess Avanthika and learns that her queen has been held captive for the last 25 years. Shividu sets off to rescue her, discovering his own origins in the process.",
    cast: ["Prabhas","Rana Daggubati","Tamannaah Bhatia","Anushka Shetty","Ramya Krishnan"], runtime: 159, year: 2015,
    platforms: ["Netflix"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["action","fantasy","drama"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "arjun-reddy", name: "Arjun Reddy", type: "movie",
    plot: "A brilliant but impulsive young surgeon spirals into self-destruction after a painful breakup, struggling to cope with love, loss, and the consequences of his own temper.",
    cast: ["Vijay Deverakonda","Shalini Pandey","Rahul Ramakrishna","Kamal Kamaraju","Kanchana"], runtime: 187, year: 2017,
    platforms: ["Prime Video"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["romance","drama"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "eega", name: "Eega", type: "movie",
    plot: "Nani is a flower decorator, madly in love with his neighbor Bindhu. He gets killed by the baddie, Sudeep, a powerful businessman. Nani comes back as a housefly to get his revenge.",
    cast: ["Sudeepa","Samantha Ruth Prabhu","Nani","Adithya Menon","Thagubothu Ramesh"], runtime: 145, year: 2012,
    platforms: ["Prime Video"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["fantasy","action","comedy"], mood: ["light","funny-silly"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["fantasy-world"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building","humor"],
  },
  {
    id: "rangasthalam", name: "Rangasthalam", type: "movie",
    plot: "Chitti Babu begins to suspect his elder brother's life is in danger after they team up to lock horns with their village president and overthrow his unlawful 30 year old regime.",
    cast: ["Ram Charan","Aadhi Pinisetty","Samantha Ruth Prabhu","Jagapati Babu","Prakash Raj"], runtime: 179, year: 2018,
    platforms: ["Prime Video"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["drama","action"], mood: ["intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "sita-ramam", name: "Sita Ramam", type: "movie",
    plot: "Afreen, a rebellious Pakistani student sets ablaze the car of an Indian in London. Angered Afreen returns to Pakistan to ask for money from her grandfather that she has to pay in a month's time as damages. However, she gets to know that he is no more and the only thing he has left for her is a letter-delivering task, written by Ram to Sita. As Afreen sets out to find Ram, there begins her journey of discovering the secret behind the 20-year-old letter.",
    cast: ["Dulquer Salmaan","Mrunal Thakur","Rashmika Mandanna","Sumanth","Gautham Vasudev Menon"], runtime: 158, year: 2022,
    platforms: ["Prime Video"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["romance","drama"], mood: ["feel-good","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","plot-twists"],
  },
  {
    id: "gangs-of-wasseypur", name: "Gangs of Wasseypur", type: "movie",
    plot: "In 1970s India, Sardar Khan vows to take revenge on the man who killed his father decades earlier.",
    cast: ["Manoj Bajpayee","Richa Chadha","Tigmanshu Dhulia","Nawazuddin Siddiqui","Reema Sen"], runtime: 160, year: 2012,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["drama","thriller","action"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["historical"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "pink-2016", name: "Pink", type: "movie",
    plot: "After being molested, Minal and her friends try to file an FIR against a politician's nephew. When the subsequent case gets rigged, a retired lawyer helps them to fight the case.",
    cast: ["Amitabh Bachchan","Taapsee Pannu","Kirti Kulhari","Andrea Tariang","Angad Bedi"], runtime: 136, year: 2016,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["drama","thriller"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "talvar", name: "Talvar", type: "movie",
    plot: "A hardened cop deals with three conflicting perspectives involving a brutal double murder. The case is complicated as the prime suspects are the parents who supposedly killed their teenage daughter.",
    cast: ["Irrfan Khan","Konkona Sen Sharma","Neeraj Kabi","Prakash Belawadi","Sohum Shah"], runtime: 132, year: 2015,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller","mystery","drama"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","world-building"],
  },
  {
    id: "masaan", name: "Masaan", type: "movie",
    plot: "Four lives intersect along the Ganges: a low caste boy in hopeless love, a daughter ridden with guilt of a sexual encounter ending in a tragedy, a hapless father with fading morality, and a spirited child yearning for a family, long to escape the moral constructs of a small-town.",
    cast: ["Richa Chadha","Sanjay Mishra","Vicky Kaushal","Shweta Tripathi Sharma","Pankaj Tripathi"], runtime: 109, year: 2015,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["drama","romance"], mood: ["dark","feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "newton-2017", name: "Newton", type: "movie",
    plot: "A government clerk on election duty in a conflict-ridden jungle of Central India tries his best to conduct free and fair voting despite the apathy of security forces and the looming fear of guerrilla attacks by communist rebels.",
    cast: ["Rajkummar Rao","Pankaj Tripathi","Anjali Patil","Raghubir Yadav","Mukesh Prajapati"], runtime: 106, year: 2017,
    platforms: ["Netflix"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["comedy","drama"], mood: ["cerebral-ideas","funny-witty"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","humor"],
  },
  {
    id: "uri-surgical-strike", name: "Uri: The Surgical Strike", type: "movie",
    plot: "Following the roguish terrorist attacks at Uri Army Base camp in Kashmir, India takes the fight to the enemy, in its most successful covert operation till date with one and only one objective of avenging their fallen heroes.",
    cast: ["Vicky Kaushal","Paresh Rawal","Yami Gautam Dhar","Mohit Raina","Kirti Kulhari"], runtime: 138, year: 2019,
    platforms: ["Netflix"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["action","drama"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "kahaani", name: "Kahaani", type: "movie",
    plot: "Pregnant and alone in the city of Kolkata, a woman begins a relentless search for her missing husband, only to find that nothing is what it seems.",
    cast: ["Vidya Balan","Parambrata Chatterjee","Nawazuddin Siddiqui","Saswata Chatterjee","Kharaj Mukherjee"], runtime: 122, year: 2012,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller","mystery"], mood: ["cerebral-mystery","dark"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "a-wednesday", name: "A Wednesday", type: "movie",
    plot: "Prakash Rathod, a retired police commissioner recounts the most memorable case of his career wherein he was informed about a bomb scare in Mumbai by an ordinary commoner.",
    cast: ["Anupam Kher","Naseeruddin Shah","Jimmy Shergill","Deepal Shaw","Aamir Bashir"], runtime: 103, year: 2008,
    platforms: ["Prime Video"], language: ["Hindi"], industry: ["Bollywood"],
    genre: ["thriller"], mood: ["intense","cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "oldboy-2003", name: "Oldboy", type: "movie",
    plot: "With no clue how he came to be imprisoned, drugged and tortured for 15 years, a desperate man seeks revenge on his captors.",
    cast: ["Choi Min-sik","Yoo Ji-tae","Kang Hye-jung","Kim Byeong-ok","Ji Dae-han"], runtime: 120, year: 2003,
    platforms: ["HBO Max"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","mystery","action"], mood: ["dark","intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","world-building"],
  },
  {
    id: "burning-2018", name: "Burning", type: "movie",
    plot: "Deliveryman Jong-su is out on a job when he runs into Hae-mi, a girl who once lived in his neighborhood. She asks if he'd mind looking after her cat while she's away on a trip to Africa. On her return, she introduces to Jong-su an enigmatic young man named Ben, who she met during her trip. One day Ben tells Jong-su about his most unusual hobby.",
    cast: ["Yoo Ah-in","Steven Yeun","Jeon Jong-seo","Kim Soo-kyung","Choe Seung-ho"], runtime: 148, year: 2018,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","mystery","drama"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "the-handmaiden", name: "The Handmaiden", type: "movie",
    plot: "1930s Korea, in the period of Japanese occupation, a new girl, Sook-hee, is hired as a handmaiden to a Japanese heiress, Hideko, who lives a secluded life on a large countryside estate with her domineering Uncle Kouzuki. But the maid has a secret. She is a pickpocket recruited by a swindler posing as a Japanese Count to help him seduce the Lady to steal her fortune.",
    cast: ["Kim Min-hee","Kim Tae-ri","Ha Jung-woo","Cho Jin-woong","Kim Hae-sook"], runtime: 145, year: 2016,
    platforms: ["Prime Video"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","romance","drama"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","world-building"],
  },
  {
    id: "decision-to-leave", name: "Decision to Leave", type: "movie",
    plot: "From a mountain peak in South Korea, a man plummets to his death. Did he jump, or was he pushed? When detective Hae-joon arrives on the scene, he begins to suspect the dead man’s wife Seo-rae. But as he digs deeper into the investigation, he finds himself trapped in a web of deception and desire.",
    cast: ["Tang Wei","Park Hae-il","Lee Jung-hyun","Go Kyung-pyo","Park Yong-woo"], runtime: 139, year: 2022,
    platforms: ["Hulu"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","romance","mystery"], mood: ["cerebral-mystery"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists","emotional-weight"],
  },
  {
    id: "mr-sunshine", name: "Mr. Sunshine", type: "show",
    plot: "Set in the early 1900s, this drama tells the story of a young man from Korea who grows up in the United States. When he returns to Korea as a US Marine Corps officer, he meets and falls in love with a noblewoman who is fighting for Korean independence. Their romance is complicated by social class and political ideology.",
    cast: ["Lee Byung-hun","Kim Tae-ri","Yoo Yeon-seok","Kim Min-joung","Byun Yo-han"], seasons: 1, episodes: 24, year: 2018,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["romance","drama","action"], mood: ["intense","feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["emotional-weight","characters"],
  },
  {
    id: "reply-1988", name: "Reply 1988", type: "show",
    plot: "Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.",
    cast: ["Lee Hye-ri","Ryu Jun-yeol","Park Bo-gum","Go Kyung-pyo","Lee Dong-hwi"], seasons: 1, episodes: 20, year: 2015,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["comedy","drama","slice-of-life"], mood: ["feel-good","funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["historical"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters","emotional-weight"],
  },
  {
    id: "vincenzo", name: "Vincenzo", type: "show",
    plot: "During a visit to his motherland, a Korean-Italian Mafia lawyer gives an unrivaled conglomerate a taste of its own medicine  with a side of justice.",
    cast: ["Song Joong-ki","Jeon Yeo-bin","Taecyeon","Kim Yeo-jin","Kwak Dong-yeon"], seasons: 1, episodes: 20, year: 2021,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","comedy","action"], mood: ["dark","funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters","plot-twists"],
  },
  {
    id: "business-proposal", name: "Business Proposal", type: "show",
    plot: "In disguise as her friend, Ha-ri shows up to a blind date to scare him away. But plans go awry when he turns out to be her CEO — and makes a proposal.",
    cast: ["Ahn Hyo-seop","Kim Se-jeong","Kim Min-gue","Seol In-a","Lee Duck-hwa"], seasons: 1, episodes: 12, year: 2022,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["romance","comedy"], mood: ["light","funny-witty"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["new-buzzy"],
    length: ["short-binge"], love: ["humor","characters"],
  },
  {
    id: "shoplifters", name: "Shoplifters", type: "movie",
    plot: "In the outskirts of Tokyo, a poor but close-knit group living on the fringes of society survives through shoplifting and odd jobs. When Osamu and his son take in a neglected young girl, their already fragile existence begins to unravel. As the family grows attached to her, buried secrets surface, forcing them to confront the true meaning of love, belonging, and what makes a family.",
    cast: ["Lily Franky","Sakura Ando","Mayu Matsuoka","Kairi Jo","Miyu Sasaki"], runtime: 120, year: 2018,
    platforms: ["Hulu"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "drive-my-car", name: "Drive My Car", type: "movie",
    plot: "Yusuke Kafuku, a stage actor and director, still unable, after two years, to cope with the loss of his beloved wife, accepts to direct Uncle Vanya at a theater festival in Hiroshima. There he meets Misaki, an introverted young woman, appointed to drive his car. In between rides, secrets from the past and heartfelt confessions will be unveiled.",
    cast: ["Hidetoshi Nishijima","Toko Miura","Masaki Okada","Reika Kirishima","Park Yu-rim"], runtime: 179, year: 2021,
    platforms: ["HBO Max"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama"], mood: ["cerebral-ideas","dark"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "seven-samurai", name: "Seven Samurai", type: "movie",
    plot: "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    cast: ["Toshirō Mifune","Takashi Shimura","Yoshio Inaba","Seiji Miyaguchi","Minoru Chiaki"], runtime: 207, year: 1954,
    platforms: ["HBO Max"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["action","drama"], mood: ["intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "ran-1985", name: "Ran", type: "movie",
    plot: "Shakespeare's King Lear is reimagined as a singular historical epic set in sixteenth-century Japan where an aging warlord divides his kingdom between his three sons.",
    cast: ["Tatsuya Nakadai","Akira Terao","Jinpachi Nezu","Daisuke Ryū","Mieko Harada"], runtime: 160, year: 1985,
    platforms: ["HBO Max"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama","action"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "departures-2008", name: "Departures", type: "movie",
    plot: "Daigo, a cellist, is laid off from his orchestra and moves with his wife back to his small hometown where the living is cheaper. Thinking he’s applying for a job at a travel agency he finds he’s being interviewed for work with departures of a more permanent nature – as an undertaker’s assistant.",
    cast: ["Masahiro Motoki","Hirosue Ryoko","Tsutomu Yamazaki","Kimiko Yo","Tetta Sugimoto"], runtime: 130, year: 2008,
    platforms: ["Prime Video"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama"], mood: ["feel-good","dark"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "midnight-diner", name: "Midnight Diner: Tokyo Stories", type: "show",
    plot: "In an otherwise mundane diner open from midnight to 7 a.m., there is no menu – but the chef cooks anything his customers want. Each episode is about different a different customer, as they find simple yet profound connections with one another based on their shared love of a particular dish.",
    cast: ["Kaoru Kobayashi"], seasons: 2, episodes: 20, year: 2016,
    platforms: ["Netflix"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama","slice-of-life"], mood: ["comfort-background","feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters","emotional-weight"],
  },
  {
    id: "pans-labyrinth", name: "Pan's Labyrinth", type: "movie",
    plot: "In post–civil war Spain, 10-year-old Ofelia moves with her pregnant mother to live under the control of her cruel stepfather. Drawn into a mysterious labyrinth, she meets a faun who reveals that she may be a lost princess from an underground kingdom. To return to her true father, she must complete a series of surreal and perilous tasks that blur the line between reality and fantasy.",
    cast: ["Ivana Baquero","Sergi López","Maribel Verdú","Doug Jones","Ariadna Gil"], runtime: 118, year: 2006,
    platforms: ["HBO Max"], language: ["Spanish"], industry: ["European Cinema"],
    genre: ["fantasy","drama","horror"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building","emotional-weight"],
  },
  {
    id: "y-tu-mama-tambien", name: "Y Tu Mamá También", type: "movie",
    plot: "In Mexico, two teenage boys and an attractive older woman embark on a road trip and learn a thing or two about life, friendship, sex, and each other.",
    cast: ["Maribel Verdú","Gael García Bernal","Diego Luna","Daniel Giménez Cacho","Diana Bracho"], runtime: 106, year: 2001,
    platforms: ["HBO Max"], language: ["Spanish"], industry: ["Latin American Cinema"],
    genre: ["drama","romance"], mood: ["dark","feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "amores-perros", name: "Amores Perros", type: "movie",
    plot: "A fatalistic car crash in Mexico city sets off a chain of events in the lives of three people: a supermodel, a young man wanting to run off with his sister-in-law, and a homeless man.",
    cast: ["Emilio Echevarría","Gael García Bernal","Goya Toledo","Álvaro Guerrero","Vanessa Bauche"], runtime: 154, year: 2000,
    platforms: ["HBO Max"], language: ["Spanish"], industry: ["Latin American Cinema"],
    genre: ["drama","thriller"], mood: ["dark","intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters","plot-twists"],
  },
  {
    id: "motorcycle-diaries", name: "The Motorcycle Diaries", type: "movie",
    plot: "Based on the journals of Che Guevara, leader of the Cuban Revolution. In his memoirs, Guevara recounts adventures he and best friend Alberto Granado had while crossing South America by motorcycle in the early 1950s.",
    cast: ["Gael García Bernal","Rodrigo de la Serna","Mercedes Morán","Mía Maestro","Jean Pierre Noher"], runtime: 126, year: 2004,
    platforms: ["Prime Video"], language: ["Spanish"], industry: ["Latin American Cinema"],
    genre: ["drama"], mood: ["feel-good","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "who-killed-sara", name: "Who Killed Sara?", type: "show",
    plot: "Hell-bent on exacting revenge and proving he was framed for his sister's murder, Álex sets out to unearth much more than the crime's real culprit.",
    cast: ["Manolo Cardona","Carolina Miranda","Ginés García Millán","Claudia Ramírez","Eugenio Siller"], seasons: 3, episodes: 25, year: 2021,
    platforms: ["Netflix"], language: ["Spanish"], industry: ["Latin American Cinema"],
    genre: ["thriller","mystery","drama"], mood: ["dark","cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists","characters"],
  },
];
