import type { RawTitle } from "../shape";

/** Batch 037 — second multi-language pass: Malayalam/Mollywood (zero titles before this
 * batch), more Tamil/Kollywood and Telugu/Tollywood, Japanese movies (live-action), Korean
 * movies, and Korean TV/K-dramas. Plot/cast/year/runtime sourced from TMDB (see
 * scripts/import-tmdb-titles-2.ts); platforms and every taxonomy tag assigned by hand. */
export const RAW: RawTitle[] = [
  {
    id: "drishyam-2013", name: "Drishyam", type: "movie",
    plot: "Georgekutty lives a happy life with his wife and daughters. Things take a turn when his daughter gets indecently filmed using a hidden camera, by the son of a police inspector.",
    cast: ["Mohanlal","Meena","Asha Sarath","Kalabhavan Shajon","Ansiba Hassan"], runtime: 164, year: 2013,
    platforms: ["Netflix"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["thriller","drama","mystery"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "premam", name: "Premam", type: "movie",
    plot: "Three stages in George's life, and three girls he encounters in each stage.",
    cast: ["Nivin Pauly","Madonna Sebastian","Sai Pallavi","Anupama Parameswaran","Shabareesh Varma"], runtime: 157, year: 2015,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["romance","comedy","drama"], mood: ["feel-good","funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "kumbalangi-nights", name: "Kumbalangi Nights", type: "movie",
    plot: "Four brothers living in the fishing hamlet of Kumbalangi share a love-hate relationship with each other. Their relationship progresses when Saji, Boney and Franky decide to help Bobby stand by his love.",
    cast: ["Shane Nigam","Soubin Shahir","Sreenath Bhasi","Mathew Thomas","Fahadh Faasil"], runtime: 135, year: 2019,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama"], mood: ["dark","feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "the-great-indian-kitchen", name: "The Great Indian Kitchen", type: "movie",
    plot: "After marriage, a woman struggles to be the submissive wife that her husband and his family expect her to be.",
    cast: ["Nimisha Sajayan","Suraj Venjaramoodu","Ajitha V M","T. Suresh Babu","Ramadevi Kannanchery"], runtime: 100, year: 2021,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "maheshinte-prathikaaram", name: "Maheshinte Prathikaaram", type: "movie",
    plot: "Mahesh, a studio photographer and owner of the studio. As the story moves on, Mahesh encounters an anonymous fight ending up with taking revenge that leads to certain realizations in his life.",
    cast: ["Fahadh Faasil","Anusree Nair","Aparna Balamurali","Alencier Ley Lopez","Jaffer Idukki"], runtime: 121, year: 2016,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["comedy","drama"], mood: ["feel-good","funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","humor"],
  },
  {
    id: "lucifer-2019", name: "Lucifer", type: "movie",
    plot: "In God's own country, the supreme leader of the ruling party dies, leaving a huge vacuum, not only in the electoral and leadership sphere of the party but also that of the state. In the inevitable succession squabble and the power struggle that ensues, the thin line that separates good and bad becomes irrecoverably blurred and out of this seemingly endless mayhem, emerge forces that are hitherto unheard of.",
    cast: ["Mohanlal","Vivek Oberoi","Manju Warrier","Tovino Thomas","Indrajith Sukumaran"], runtime: 174, year: 2019,
    platforms: ["Netflix"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["action","drama","thriller"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","plot-twists"],
  },
  {
    id: "jallikattu", name: "Jallikattu", type: "movie",
    plot: "An escaped buffalo triggers a frenzy of ecstatic violence in a remote village.",
    cast: ["Antony Varghese","Chemban Vinod Jose","Sabumon Abdusamad","Santhy Balachandran","Jaffer Idukki"], runtime: 95, year: 2019,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["thriller","drama"], mood: ["dark","intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","plot-twists"],
  },
  {
    id: "ustad-hotel", name: "Ustad Hotel", type: "movie",
    plot: "When his father refuses to support his choice of a career, an aspiring chef tries to fulfil his dream by helping his grandfather run his small eatery.",
    cast: ["Dulquer Salmaan","Thilakan","Nithya Menen","Siddique","Mamukkoya"], runtime: 150, year: 2012,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","comedy"], mood: ["feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "charlie-2015", name: "Charlie", type: "movie",
    plot: "A young, nonconforming woman named Tessa gets entangled in a cat-and-mouse chase in the by-lanes of Kerala, hunting for a mysterious artist who previously lived in her apartment.",
    cast: ["Dulquer Salmaan","Parvathy Thiruvothu","Aparna Gopinath","Chemban Vinod Jose","Nedumudi Venu"], runtime: 130, year: 2015,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["romance","drama","fantasy"], mood: ["feel-good","light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "vikram-vedha-2017", name: "Vikram Vedha", type: "movie",
    plot: "A notorious gangster Vedha surrenders himself to encounter specialist Vikram whom he challenges every step of the way by narrating his life events in the form of riddles that needs to be solved in order to capture him.",
    cast: ["R. Madhavan","Vijay Sethupathi","Shraddha Srinath","Kathir","Varalaxmi Sarathkumar"], runtime: 147, year: 2017,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","thriller","drama"], mood: ["dark","cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "pariyerum-perumal", name: "Pariyerum Perumal", type: "movie",
    plot: "A law student from a lower caste begins a friendship with his classmate, a girl who belongs to a higher caste, and the men in her family start giving him trouble over this.",
    cast: ["Kathir","Anandhi","Yogi Babu","G. Marimuthu","Lijeesh"], runtime: 155, year: 2018,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "aruvi", name: "Aruvi", type: "movie",
    plot: "A gentle girl born and brought up amidst the ever growing eco-social-consumeristic environment finds it difficult to fit in the society. She decides to take it hard on the people.",
    cast: ["Aditi Balan","Shwetha Shekar","Lakshmi Gopalaswamy","Mohammad Ali Baig","Kavitha Bharathi"], runtime: 122, year: 2017,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "karnan", name: "Karnan", type: "movie",
    plot: "Karnan, an angry young man, fights for the rights of his oppressed people. Can he save them from those who wield power and weapons?",
    cast: ["Dhanush","Rajisha Vijayan","Natarajan Subramaniam","Lal","Yogi Babu"], runtime: 152, year: 2021,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","action"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "baahubali-2", name: "Baahubali 2: The Conclusion", type: "movie",
    plot: "When Mahendra, the son of Bāhubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.",
    cast: ["Prabhas","Rana Daggubati","Anushka Shetty","Sathyaraj","Nassar"], runtime: 167, year: 2017,
    platforms: ["Netflix"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["action","fantasy","drama"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["fantasy-world"], structure: ["franchise"], recency: ["classic"],
    length: ["single-sitting"], love: ["world-building","plot-twists"],
  },
  {
    id: "jersey-2019", name: "Jersey", type: "movie",
    plot: "After his career fails to take off, a gifted cricketer in his mid-thirties decides that he’s not ready to give up quite yet.",
    cast: ["Nani","Shraddha Srinath","Ronit Kamra","Harish Kalyan","Viswant Duddumpudi"], runtime: 160, year: 2019,
    platforms: ["Prime Video"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["drama"], mood: ["feel-good","intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "mahanati", name: "Mahanati", type: "movie",
    plot: "Mahanati depicts the life and career of one of Telugu cinema's greatest and most iconic starlets, the first Indian female super star, Savitri.",
    cast: ["Keerthy Suresh","Dulquer Salmaan","Samantha Ruth Prabhu","Vijay Deverakonda","Prakash Raj"], runtime: 176, year: 2018,
    platforms: ["Prime Video"], language: ["Telugu"], industry: ["Tollywood"],
    genre: ["drama"], mood: ["dark","feel-good"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "perfect-blue", name: "Perfect Blue", type: "movie",
    plot: "Rising pop star Mima Kirigoe quits singing to pursue a career as an actress. After she takes up a role on a popular detective show, her handlers and collaborators begin turning up murdered. Harboring feelings of guilt and haunted by visions of her former self, Mima's reality and fantasy meld into a frenzied paranoia.",
    cast: ["Junko Iwao","Rica Matsumoto","Shiho Niiyama","Masaaki Okura","Shinpachi Tsuji"], runtime: 81, year: 1998,
    platforms: ["HBO Max"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["thriller","horror","mystery"], mood: ["dark","cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","world-building"],
  },
  {
    id: "hana-bi", name: "Hana-bi", type: "movie",
    plot: "Beleaguered police detective Nishi takes desperate measures to try and set things right in a world gone wrong. With his wife suffering from leukemia and his business partner paralyzed from a brutal gangster attack, Nishi borrows from a yakuza loan shark and then robs a bank to clear his debt.",
    cast: ["Takeshi Kitano","Kayoko Kishimoto","Ren Osugi","Susumu Terajima","Tetsu Watanabe"], runtime: 103, year: 1997,
    platforms: ["HBO Max"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama","thriller"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "an-2015", name: "Sweet Bean", type: "movie",
    plot: "The master of a dorayaki pastry store hires a 76-year-old woman whose talents attract customers from all over. But she's hiding a troubling secret. Life's joys are found in the little details, and no matter what may be weighing you down, everyone loves a good pastry.",
    cast: ["Kirin Kiki","Masatoshi Nagase","Kyara Uchida","Miki Mizuno","Etsuko Ichihara"], runtime: 113, year: 2015,
    platforms: ["Hulu"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama","slice-of-life"], mood: ["feel-good","dark"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "like-father-like-son", name: "Like Father, Like Son", type: "movie",
    plot: "FBI agent Malcolm Turner and his 17-year-old son Trent go undercover at an all-girls performing arts school after Trent witnesses a murder. Posing as Big Momma and Charmaine, they must find the murderer before he finds them.",
    cast: ["Martin Lawrence","Brandon T. Jackson","Jessica Lucas","Portia Doubleday","Emily Rios"], runtime: 107, year: 2011,
    platforms: ["Prime Video"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["drama"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "confessions-2010", name: "Confessions", type: "movie",
    plot: "Devastated at the death of her four-year-old daughter, a grieving middle school teacher is horrified to discover that her students aren't as innocent as she thinks.",
    cast: ["Takako Matsu","Masaki Okada","Yoshino Kimura","Yukito Nishii","Kaoru Fujiwara"], runtime: 107, year: 2010,
    platforms: ["HBO Max"], language: ["Japanese"], industry: ["Japanese Cinema"],
    genre: ["thriller","drama","mystery"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "a-tale-of-two-sisters", name: "A Tale of Two Sisters", type: "movie",
    plot: "Two sisters return home after a stay in a mental institution, only to face disturbing events and a strained relationship with their stepmother. As eerie occurrences unfold, dark family secrets begin to surface, blurring the line between reality and nightmare.",
    cast: ["Lim Soo-jung","Moon Geun-young","Yum Jung-ah","Kim Kap-soo","Park Mi-hyeon"], runtime: 115, year: 2003,
    platforms: ["Hulu"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["horror","mystery","drama"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","world-building"],
  },
  {
    id: "memories-of-murder", name: "Memories of Murder", type: "movie",
    plot: "A sadistic serial rapist and murderer of young women terrorizes a small province in 1980s South Korea. To prevent further crimes, three increasingly desperate detectives with conflicting methods race against time to unravel the violent mind of the killer in a futile effort to solve the case.",
    cast: ["Song Kang-ho","Kim Sang-kyung","Kim Roi-ha","Song Jae-ho","Byun Hee-bong"], runtime: 131, year: 2003,
    platforms: ["HBO Max"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","mystery","drama"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "the-wailing", name: "The Wailing", type: "movie",
    plot: "A stranger arrives in a little village and soon after a mysterious sickness starts spreading. A policeman is drawn into the incident and is forced to solve the mystery in order to save his daughter.",
    cast: ["Kwak Do-won","Hwang Jung-min","Chun Woo-hee","Jun Kunimura","Kim Hwan-hee"], runtime: 156, year: 2016,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["horror","mystery","thriller"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","plot-twists"],
  },
  {
    id: "i-saw-the-devil", name: "I Saw the Devil", type: "movie",
    plot: "Kyung-chul is a dangerous psychopath who kills for pleasure. Soo-hyeon, a top-secret agent, decides to track down the murderer himself. He promises himself that he will do everything in his power to take vengeance against the killer, even if it means that he must become a monster himself.",
    cast: ["Lee Byung-hun","Choi Min-sik","Jeon Kuk-hwan","Cheon Ho-jin","Oh San-ha"], runtime: 144, year: 2010,
    platforms: ["Hulu"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","horror"], mood: ["dark","intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "a-taxi-driver", name: "A Taxi Driver", type: "movie",
    plot: "May, 1980. Man-seob is a taxi driver in Seoul who lives from hand to mouth, raising his young daughter alone. One day, he hears that there is a foreigner who will pay big money for a drive down to Gwangju city. Not knowing that he’s a German journalist with a hidden agenda, Man-seob takes the job.",
    cast: ["Song Kang-ho","Thomas Kretschmann","Yoo Hai-jin","Ryu Jun-yeol","Park Hyuk-kwon"], runtime: 138, year: 2017,
    platforms: ["Prime Video"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["drama","action"], mood: ["intense","feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "hospital-playlist", name: "Hospital Playlist", type: "show",
    plot: "Every day is extraordinary for five doctors and their patients inside a hospital, where birth, death and everything in between coexist.",
    cast: ["Cho Jung-seok","Yoo Yeon-seok","Jung Kyung-ho","Kim Dae-myung","Jeon Mi-do"], seasons: 2, episodes: 24, year: 2020,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["drama","comedy","slice-of-life"], mood: ["feel-good","funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters","emotional-weight"],
  },
  {
    id: "itaewon-class", name: "Itaewon Class", type: "show",
    plot: "In a colorful Seoul neighborhood, an ex-con and his friends fight a mighty foe to make their ambitious dreams for their street bar a reality.",
    cast: ["Park Seo-jun","Kim Da-mi","Kwon Na-ra","Yoo Jae-myung","Ahn Bo-hyun"], seasons: 1, episodes: 16, year: 2020,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["drama"], mood: ["intense","feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters","plot-twists"],
  },
  {
    id: "hometown-cha-cha-cha", name: "Hometown Cha-Cha-Cha", type: "show",
    plot: "A big-city dentist opens up a practice in a close-knit seaside village, home to a charming jack-of-all-trades who is her polar opposite in every way.",
    cast: ["Shin Min-a","Kim Seon-ho","Lee Sang-yi","Gong Min-jeung","Kim Yeong-ok"], seasons: 1, episodes: 16, year: 2021,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["romance","comedy","slice-of-life"], mood: ["feel-good","light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters","emotional-weight"],
  },
  {
    id: "signal-2016", name: "Signal", type: "show",
    plot: " Detectives from the present and a detective from the past communicate via walkie-talkie to solve a long-time unsolved case.",
    cast: ["Lee Je-hoon","Kim Hye-soo","Cho Jin-woong","Jang Hyun-sung","Jung Hae-kyun"], seasons: 2, episodes: 17, year: 2016,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","mystery","sci-fi"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists","world-building"],
  },
  {
    id: "stranger-korean", name: "Stranger", type: "show",
    plot: "Hwang Shi Mok underwent brain surgery as a child to curb his violent temper, which left him devoid of emotions. Hwang becomes a prosecutor known for his piercing intelligence and logic, but he is ostracized because he lacks empathy and social skills. He is also one of only a handful of upright prosecutors who have refused to take bribes. One day, he encounters a stabbing victim while investigating corruption. He meets Lieutenant Han Yeo Jin at the crime scene. They join forces to root out corruption at the prosecutors’ office and solve a serial murder case.",
    cast: ["Cho Seung-woo","Bae Doona","Lee Jun-hyuk","Jeon Hye-jin","Choi Mu-sung"], seasons: 2, episodes: 32, year: 2017,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["thriller","mystery","drama"], mood: ["dark","cerebral-mystery"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["serialized"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["plot-twists","characters"],
  },
  {
    id: "start-up-2020", name: "Start-Up", type: "show",
    plot: "Young entrepreneurs aspiring to launch virtual dreams into reality compete for success and love in the cutthroat world of Korea's high-tech industry.",
    cast: ["Suzy","Nam Joo-hyuk","Kim Seon-ho","Kang Han-na","Kim Hae-sook"], seasons: 1, episodes: 16, year: 2020,
    platforms: ["Netflix"], language: ["Korean"], industry: ["Korean Cinema"],
    genre: ["romance","drama"], mood: ["feel-good","intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["episodic"], completion: ["completed"], recency: ["hidden-gem"],
    length: ["short-binge"], love: ["characters","emotional-weight"],
  },
];
