import type { RawTitle } from "../shape";

/** Batch 038 — Malayalam/Tamil priority expansion (per-language minimum push): these two were
 * the most underrepresented languages in the dataset. Plot/cast/year/runtime sourced from TMDB
 * (see scripts/import-tmdb-titles-3.ts); platforms and every taxonomy tag assigned by hand. */
export const RAW: RawTitle[] = [
  {
    id: "bangalore-days", name: "Bangalore Days", type: "movie",
    plot: "A fun roller coaster ride about three young people, Aju, Divya and Kuttan who are cousins, reach Bangalore to dream, discover & explore!",
    cast: ["Nazriya Nazim","Nivin Pauly","Dulquer Salmaan","Fahadh Faasil","Parvathy Thiruvothu"], runtime: 172, year: 2014,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","romance","comedy"], mood: ["feel-good","light"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "angamaly-diaries", name: "Angamaly Diaries", type: "movie",
    plot: "Six young friends in the small town of Angamaly tries their luck by starting a pork business lead by Vincent Pepe. They initially strike a business deal with Rajan and Ravi despite the duo having killed a close friend of theirs in a gang fight. Vincent is in love with Sakhi and plan to immigrate abroad with her. But their plans hit a road bump as the deal with the gangsters hits some road bumps.",
    cast: ["Antony Varghese","Sarath Kumar","Tito Wilson","Bitto Davis","Sinoj Varghese"], runtime: 132, year: 2017,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","action"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "thondimuthalum-driksakshiyum", name: "Thondimuthalum Driksakshiyum", type: "movie",
    plot: "Prasad and Sreeja are a couple planning to set up a new life in Kasargod. On a bus journey they end up being robbed by a thief also named Prasad and this lands them up in a police station.",
    cast: ["Fahadh Faasil","Suraj Venjaramoodu","Nimisha Sajayan","Alencier Ley Lopez","Vettukili Prakash"], runtime: 136, year: 2017,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","comedy","mystery"], mood: ["cerebral-ideas","funny-witty"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "virus-2019", name: "Virus", type: "movie",
    plot: "A real life account of the deadly Nipah virus outbreak in Kerala, and the courageous fight put on by several individuals which helped to contain the epidemic.",
    cast: ["Kunchacko Boban","Parvathy Thiruvothu","Tovino Thomas","Sreenath Bhasi","Madonna Sebastian"], runtime: 152, year: 2019,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","thriller"], mood: ["intense","cerebral-ideas"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "joji-2021", name: "Joji", type: "movie",
    plot: "Joji, an engineering dropout and the youngest son of a rich family lives with his aspirations of becoming super wealthy. Driven by greed and blind ambition, he decides to execute his plans following an unexpected event in the family.",
    cast: ["Fahadh Faasil","Baburaj","P N Sunny","Unnimaya Prasad","Basil Joseph"], runtime: 113, year: 2021,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","thriller"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","plot-twists"],
  },
  {
    id: "minnal-murali", name: "Minnal Murali", type: "movie",
    plot: "A tailor gains special powers after being struck by lightning but must take down an unexpected foe if he is to become the superhero his hometown in Kerala needs.",
    cast: ["Tovino Thomas","Guru Somasundaram","Aju Varghese","Vasisht Umesh","Shelly Kishore"], runtime: 158, year: 2021,
    platforms: ["Netflix"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["action","fantasy","drama"], mood: ["feel-good","intense"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "kurup-2021", name: "Kurup", type: "movie",
    plot: "The Film is based on the infamous 'Charlie Murder Case' in the Indian State of Kerala where the main culprit Sukumara Kurup has been on the run for decades and is still not been caught. The story revolves around the perspective of Sukumara Kurup and the Police officers who were investigating the case.",
    cast: ["Dulquer Salmaan","Sobhita Dhulipala","Indrajith Sukumaran","Tovino Thomas","Shine Tom Chacko"], runtime: 155, year: 2021,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["thriller","drama"], mood: ["dark","intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "bheeshma-parvam", name: "Bheeshma Parvam", type: "movie",
    plot: "Set in the backdrop of 1980s, Micheal helms his influential family in Kochi, inspiring fear and respect through his unnerving past. When a few younger members in the household feel his power over their lives too are aggravating, they join hands with foes to clamp down on him. And the story follows what’s in store for them.",
    cast: ["Mammootty","Soubin Shahir","Sreenath Bhasi","Shine Tom Chacko","Nadhiya"], runtime: 144, year: 2022,
    platforms: ["Disney+ Hotstar"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","action"], mood: ["intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "manjummel-boys", name: "Manjummel Boys", type: "movie",
    plot: "A carefree vacation turns into a desperate race against time when a group of lifelong friends must unite to save one of their own from a notoriously perilous, uncharted abyss deep within the Guna Caves.",
    cast: ["Soubin Shahir","Sreenath Bhasi","Balu Varghese","Ganapathi S. Poduval","Lal Jr."], runtime: 135, year: 2024,
    platforms: ["Disney+ Hotstar"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","thriller"], mood: ["intense","feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "2018-movie", name: "2018", type: "movie",
    plot: "A disaster film set during the 2018 Kerala Floods where people from all walks of life faced catastrophic consequences and put in collective efforts to survive the calamity.",
    cast: ["Tovino Thomas","Kunchacko Boban","Narain","Asif Ali","Lal"], runtime: 150, year: 2023,
    platforms: ["Netflix"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","action"], mood: ["intense","feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "aavesham", name: "Aavesham", type: "movie",
    plot: "Three college freshmen in Bangalore befriend an eccentric gangster to get revenge on their senior bullies.",
    cast: ["Fahadh Faasil","Hipster","Mithun Jai Sankar","Roshan Shanavas","Sajin Gopu"], runtime: 156, year: 2024,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["comedy","action"], mood: ["funny-witty","intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters","humor"],
  },
  {
    id: "bramayugam", name: "Bramayugam", type: "movie",
    plot: "A folk singer in 17th-century Kerala discovers a mansion. Inside, he encounters an enigmatic cook and a powerful master, setting in motion a chain of events that changes his life.",
    cast: ["Arjun Ashokan","Mammootty","Sidharth Bharathan","Manikandan Achari","Amalda Liz"], runtime: 139, year: 2024,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["horror","drama","fantasy"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["historical"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["world-building","plot-twists"],
  },
  {
    id: "take-off-2017", name: "Take Off", type: "movie",
    plot: "A group of Malayali nurses stranded in Iraq, must survive their capture by the extremists and reach out to the rescue team headed by the Indian government.",
    cast: ["Kunchacko Boban","Parvathy Thiruvothu","Fahadh Faasil","Divya Prabha","Prakash Belawadi"], runtime: 139, year: 2017,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","thriller"], mood: ["intense","feel-good"], pace: ["fast-paced"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "ayyappanum-koshiyum", name: "Ayyappanum Koshiyum", type: "movie",
    plot: "Ayyappan, a police officer, is an upright man who always strives to do the right thing. However, things change when a retired army havildar, Koshy, settles in his village and the two egos clash.",
    cast: ["Prithviraj Sukumaran","Biju Menon","Anil Nedumangad","Ranjith","Gowry Nandha"], runtime: 177, year: 2020,
    platforms: ["Disney+ Hotstar"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","action","thriller"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","plot-twists"],
  },
  {
    id: "nayattu", name: "Nayattu", type: "movie",
    plot: "Three police officers are forced to go on the run when they get tangled in the death of a youth, a few days before the election.",
    cast: ["Kunchacko Boban","Joju George","Nimisha Sajayan","Jaffer Idukki","Yama Gilgamesh"], runtime: 124, year: 2021,
    platforms: ["Netflix"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["thriller","drama"], mood: ["dark","intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "malik-2021", name: "Malik", type: "movie",
    plot: "A past ridden with crime, death and pain is recounted to Freddy, a juvenile criminal, who has been assigned to eliminate his estranged uncle Sulaiman, an aging patriarch, while behind bars.",
    cast: ["Fahadh Faasil","Nimisha Sajayan","Vinay Forrt","Jalaja","Salim Kumar"], runtime: 161, year: 2021,
    platforms: ["Prime Video"], language: ["Malayalam"], industry: ["Mollywood"],
    genre: ["drama","action"], mood: ["intense","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "thani-oruvan", name: "Thani Oruvan", type: "movie",
    plot: "An idealistic cop and an ambitious scientist-businessman indulge in a high-stake battle of wits.",
    cast: ["Ravi Mohan","Arvind Swamy","Nayanthara","Vamsi Krishna","Ganesh Venkatraman"], runtime: 159, year: 2015,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","thriller"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "8-thottakkal", name: "8 Thottakkal", type: "movie",
    plot: "A cop’s pistol gets stolen and even as the search for it gets underway, it ends up in the hands of someone who uses it to rob a bank.",
    cast: ["Vetri","Aparna Balamurali","M. S. Bhaskar","Nassar","Manikandan"], runtime: 145, year: 2017,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["thriller","action"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
  {
    id: "ratsasan", name: "Ratsasan", type: "movie",
    plot: "A serial killer is murdering school girls, and a newbie cop has to track him down before the victim count increases.",
    cast: ["Vishnu Vishal","Amala Paul","Suzane George","Munishkanth","Kaali Venkat"], runtime: 170, year: 2018,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["thriller","horror","mystery"], mood: ["dark","cerebral-mystery"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","world-building"],
  },
  {
    id: "sarpatta-parambarai", name: "Sarpatta Parambarai", type: "movie",
    plot: "When Sarpatta Parambarai is challenged to a do-or-die match, Kabilan, a young labourer, must choose whether to put on the gloves himself and lead his clan to victory, or be dissuaded by his disapproving mother and dangerous politics.",
    cast: ["Arya","Pasupathy","Kalaiyarasan","John Vijay","John Kokken"], runtime: 174, year: 2021,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","action"], mood: ["intense","feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "visaranai", name: "Visaranai", type: "movie",
    plot: "Pandi and his friends, immigrant workers in Andhra Pradesh, are picked up by cops for a crime they never committed. And thus begins their nightmare, where they become pawns in a vicious game where the voiceless are strangled by those with power.",
    cast: ["V R Dinesh","Samuthirakani","Anandhi","Aadukalam Murugadoss","Kishore"], runtime: 118, year: 2016,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","thriller"], mood: ["dark","intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence","heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["classic"],
    length: ["single-sitting"], love: ["characters","emotional-weight"],
  },
  {
    id: "maanagaram", name: "Maanagaram", type: "movie",
    plot: "Upon moving to Chennai, four lives get intertwined as they strive to achieve success in the city. However, when a vicious gangster threatens them, the group must work together to defeat him.",
    cast: ["Sri","Sundeep Kishan","Regena Cassandrra","Charle","Munishkanth"], runtime: 137, year: 2017,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["thriller","drama"], mood: ["dark","intense"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["plot-twists","world-building"],
  },
  {
    id: "mandela-2021", name: "Mandela", type: "movie",
    plot: "An underprivileged hairdresser becomes the game changer in a local body election in a village where caste politics rules the roost. Will he be able to bring some changes to people's lives?",
    cast: ["Yogi Babu","G. M. Sundar","Kanna Ravi","Sangili Murugan","Sheela Rajkumar"], runtime: 140, year: 2021,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["comedy","drama"], mood: ["funny-witty","feel-good"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["single-protagonist"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor","characters"],
  },
  {
    id: "peranbu", name: "Peranbu", type: "movie",
    plot: "A single father tries to raise his daughter, who has cerebral palsy, even as she is beginning to wake up to her sexuality.",
    cast: ["Mammootty","Sadhana","Anjali","Anjali Ameer","Lizzie Antony"], runtime: 147, year: 2019,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama"], mood: ["dark","cerebral-ideas"], pace: ["slow-burn"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["heavy-themes"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["emotional-weight","characters"],
  },
  {
    id: "dharma-durai", name: "Dharma Durai", type: "movie",
    plot: "A once-promising village doctor, burdened by personal loss and family betrayal, spirals into alcoholism and becomes an outcast. His journey of pain, resilience, and rediscovery takes him from despair to a chance at redemption, as he confronts his past and searches for purpose, love, and reconciliation.",
    cast: ["Vijay Sethupathi","Tamannaah Bhatia","Srushti Dange","Aishwarya Rajesh","Radhika Sarathkumar"], runtime: 167, year: 2016,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","comedy"], mood: ["feel-good","funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["family"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","humor"],
  },
  {
    id: "oh-my-kadavule", name: "Oh My Kadavule", type: "movie",
    plot: "Arjun is conveniently married to his best friend Anu and their marriage turns out to be a nightmare since he is not really in love with her. When things get tough Arjun gets a second chance in life that could change his path and perspective altogether.",
    cast: ["Ashok Selvan","Ritika Singh","Shah Ra","Vani Bhojan","Gajaraj"], runtime: 154, year: 2020,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["romance","comedy","drama"], mood: ["feel-good","funny-witty"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["humor","emotional-weight"],
  },
  {
    id: "master-2021", name: "Master", type: "movie",
    plot: "An alcoholic professor is sent to a juvenile school, where he clashes with a gangster, who uses the children of the school for criminal activities.",
    cast: ["Vijay","Vijay Sethupathi","Arjun Das","Malavika Mohanan","Andrea Jeremiah"], runtime: 179, year: 2021,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","drama"], mood: ["intense","funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","plot-twists"],
  },
  {
    id: "beast-2022", name: "Beast", type: "movie",
    plot: "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
    cast: ["Idris Elba","Leah Sava Jeffries","Iyana Halley","Sharlto Copley","Martin Munro"], runtime: 93, year: 2022,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","thriller"], mood: ["intense"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["characters","plot-twists"],
  },
  {
    id: "ponniyin-selvan-1", name: "Ponniyin Selvan: I", type: "movie",
    plot: "The Chola kingdom is under threat from forces both internal and external, and with crown prince Aaditha Karikalan, his younger brother Arunmozhi Varman and the emperor, Sundara Cholar separated by situations, it is up to a messenger to ensure the safety of the kingdom. Can he succeed in his mission, especially with Karikalan's former girlfriend, Nandhini, plotting to bring down the entire Chola empire?",
    cast: ["Vikram","Aishwarya Rai Bachchan","Ravi Mohan","Karthi","Trisha Krishnan"], runtime: 167, year: 2022,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","action","fantasy"], mood: ["intense"], pace: ["slow-burn"],
    tone: ["hopeful"], cast_style: ["ensemble"], content_rating: ["teen"], intensity: ["graphic-violence"],
    era: ["historical"], structure: ["franchise"], recency: ["hidden-gem"],
    length: ["single-sitting"], love: ["world-building","characters"],
  },
  {
    id: "maamannan", name: "Maamannan", type: "movie",
    plot: "An MLA and his son, who are from oppressed community, are forced to stand up against the privileged, arrogant scion of a late politician, who is determined to make them bow down to him.",
    cast: ["Vadivelu","Udhayanidhi Stalin","Fahadh Faasil","Keerthy Suresh","Sunil"], runtime: 156, year: 2023,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["drama","action"], mood: ["intense"], pace: ["slow-burn"],
    tone: ["gritty"], cast_style: ["ensemble"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters","world-building"],
  },
  {
    id: "jailer-2023", name: "Jailer", type: "movie",
    plot: "Muthuvel Pandian, a retired, stern yet compassionate jailer lives a peaceful life with his family, but trouble knocks his door when his cop son’s tryst with an antique mafia gang goes awry and forces Muthu to step back into a dark world he had voluntarily took a break from.",
    cast: ["Rajinikanth","Vinayakan","Vasanth Ravi","Yogi Babu","Ramya Krishnan"], runtime: 165, year: 2023,
    platforms: ["Prime Video"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","comedy"], mood: ["intense","funny-witty"], pace: ["fast-paced"],
    tone: ["mixed"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["characters","humor"],
  },
  {
    id: "leo-2023", name: "Leo", type: "movie",
    plot: "Jaded 74-year-old reptile Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.",
    cast: ["Adam Sandler","Bill Burr","Cecily Strong","Jason Alexander","Rob Schneider"], runtime: 102, year: 2023,
    platforms: ["Netflix"], language: ["Tamil"], industry: ["Kollywood"],
    genre: ["action","thriller"], mood: ["intense","dark"], pace: ["fast-paced"],
    tone: ["gritty"], cast_style: ["single-protagonist"], content_rating: ["mature"], intensity: ["graphic-violence"],
    era: ["modern"], structure: ["standalone"], recency: ["new-buzzy"],
    length: ["single-sitting"], love: ["plot-twists","characters"],
  },
];
